### ISSUE TITLE
DirectProxy and HttpProxy have names interchanged

### ISSUE THREAD

**Issue by belun** [jamesdbloom/mockserver#100]
Should _HttpProxy_ be called _DirectProxy_, since it only accepts a _port_ (thus a straight forward, local proxy)?
Same for _DirectProxy_. Should it be called _HttpProxy_, since it accepts extra_remoteHost_ and _remotePort_ (like a local wraper for remote Proxy, that in fact delegates to the remote Proxy)?

**Comment by belun** [comment]
(how the f... do you mark an issue as _question_?)

**Comment by jamesdbloom** [comment]
Well the idea is supposed to be that the HttpProxy works like a classical HTTP proxy in the sense that is forwards the request using the Host header.  However the direct proxy works as a reverse proxy that forwards all requests to the exact same host and port.  Perhaps the DirectProxy could be called ReversProxy instead as that may make it clearer.  But the HttpProxy works as a standard HTTP proxy so I think that has the correct name.
