### ISSUE TITLE
Allow configure an expectation to match only when a given parameter is not in the request

### ISSUE THREAD

**Issue by alexcojocaru** [jamesdbloom/mockserver#103]
That is, if I create two expectations:

Expectation A matches a request with path=/test and no parameters
Expectation B matches a request with path=/test and parameter 'param'='some value'

I want expectation A to not match and expectation B to match, when a request with path=/test and parameter 'param'='some value' is received.
In other words, I want to be able to create an expectation and configure it to match a request where a given parameter is not provided.

**Comment by jamesdbloom** [comment]
One option could be to use a regex matcher for 'param' that matches anything except 'some value'.

However I do agree it could be a good idea to support ```not``` behaviour to be able to specify match for anything except a specific value.  I'll leave this issue open and add support for ```not``` semantics.

**Comment by alexcojocaru** [comment]
I am not convinced I can use a regexp to achieve the same result.

Let me give you an example:
**url1** (with no param): `http://path/to`
**url2** (with param): `http://path/to?param=value2`
**url3** (with param): `http://path/to?param=value3`

How do I define an expectation to match url1, but not url2 and url3? Please take into account that, when defining the first expectation, I don't always know what value2 and value3 are.

**Comment by jamesdbloom** [comment]
So if you don't the value up front I agree that the only sensible way to match this would be using a ```not``` operator.  However do you realise that the order of matching is always in the same order that the expectation are setup.  Therefor if you setup the expectation with the `param` parameter first then it will be match first for any request to `http://path/to`.  Basically if you setup the expectations with the most specific requirements first then they'll be matched against first and only if a request does match one of the more specific expectations will it be matched against a less specific expectation.

**Comment by alexcojocaru** [comment]
Thanks for the explanation, James.

**Comment by alexcojocaru** [comment]
Thank you, James. I am looking forward to using the new 'not' operation.
