### ISSUE TITLE
Matching a urlencoded body?

### ISSUE THREAD

**Issue by jghoman** [jamesdbloom/mockserver#105]
I'm having trouble matching a POST with a Content-Type of application/x-www-form-urlencoded, where the client making the request could have encoded the parameters however they liked.  

For instance,
```Java
    HttpResponse<JsonNode> json = Unirest.post(refreshURL)
          .field("client_id", clientId)
          .field("client_secret", clientSecret)
          .field("grant_type", "refresh_token")
          .field("refresh_token", refreshToken)
          .asJson();
```
Results in a request with the body something along the lines of:
```Java
  "body" : "client_secret=client+secret&grant_type=refresh_token&refresh_token=refresh+token+key&client_id=client+id",
```
I don't want to do an exact match because different clients might encode the fields in a different order.

Is there some way currently to support the url decoding of the body that I'm missing?  It seems pretty simple to have a `URLEncodedBody<List<Param>>` that would take the raw body, urldecode and build up a list of Params from that.  However, the code right now is not user extensible for that type of functionality (custom Bodies), so I wanted to check before writing such functionality myself.

**Comment by jamesdbloom** [comment]
This is support already using ```org.mockserver.model.ParameterBody``` as follows:

```java
mockServerClient
        .when(
                request()
                        .withMethod("POST")
                        .withPath(calculatePath("some_pathRequest"))
                        .withBody(params(
                                param("bodyParameterOneName", "Parameter One Value One", "Parameter One Value Two"),
                                param("bodyParameterTwoName", "Parameter Two")
                        ))
        )
        .respond(
                response()
                        .withStatusCode(HttpStatusCode.ACCEPTED_202.code())
                        .withBody("some_bodyResponse")
                        .withHeaders(header("headerNameResponse", "headerValueResponse"))
                        .withCookies(cookie("cookieNameResponse", "cookieValueResponse"))
        );
```

*Note:* this example uses the static helper method ```org.mockserver.model.ParameterBody.params``` which creates a ```org.mockserver.model.ParameterBody```.

This will match any request with at least those parameters (extra parameters are ignored).  Each matched parameter has to have at least those values (extra values are ignored).  This is currently no support for an exact match with extra values are not ignored but this is in the pipeline and will be added soon (it has already been added for ```org.mockserver.model.JsonBody```) .  

If the ```ParameterBody``` class does not meet you needs please provide a code example then I can look at improving the ```ParameterBody``` class.

**Comment by jghoman** [comment]
OK, looks like the client was sending a malformed request (not sorting the fields as is apparently the responsibility of the client: http://stackoverflow.com/questions/14085487/order-of-http-post-parameters-changed).  Thanks for checking and sorry for the false alarm.

**Comment by jamesdbloom** [comment]
That an interesting point you make about sorting of fields in the HTTP specification, I've never picked up on that before, however, I don't believe the lack of sorting is a bug in the client.  The MockServer is designed to allow user to setup any test scenario they need.  If the client sorted the fields this would prevent users from specifying the exact order of fields they wanted.  In addition the matching in the MockServer is not order specific so I don't think any sorting would have an impact.

**Comment by EdysnayAyala** [comment]
I want to pass part of the content of the body of the request towards the body of the answer as I do thanks.
