### ISSUE TITLE
mock a request to not "localhost" domain.

### ISSUE THREAD

**Issue by ko4evnik** [jamesdbloom/mockserver#108]
Hello, James!

Sorry for possibly dumb question.
Can I mock request to specific domain? For example to http://habrahabr.ru/posts/api/

I tried smth like this, but it's not work for me:

```
xmlHttpRequest.send(JSON.stringify({
    "httpRequest": {
        "method": "GET",
		"url": "http://habrahabr.ru/",
        "path": "/posts/api"
    },
    "httpForward": {
        "host": "www.mock-server.com",
        "port": 80,
        "scheme": "HTTP"
    },
    "times": {
        "remainingTimes": 3,
        "unlimited": false
    }
}));
```

**Comment by jamesdbloom** [comment]
The correct format would be:

```js
xmlHttpRequest.send(JSON.stringify({
    "httpRequest": {
        "method": "GET", 
        "path": "/posts/api"
    }, 
    "times": {
        "remainingTimes": 3, 
        "unlimited": false
    }, 
    "httpForward": {
        "host": "www.mock-server.com", 
        "port": 80, 
        "scheme": "HTTP"
    }
}));
```

In particularly notice that there is no "url" property.  Then you will need to add an entry into you hosts file:

 1. find host file `/etc/hosts`  in mac or linux and `%systemroot%\system32\drivers\etc\hosts` in windows (where %systemroot% is usually c:\windows)

 2. Add mapping from `habrahabr.ru` to `127.0.0.1` as follows:
```bash
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
255.255.255.255	broadcasthost
fe80::1%lo0	    localhost
127.0.0.1	    localhost

127.0.0.1 		habrahabr.ru
```

Your file may look slightly different but the important thing is the line with `habrahabr.ru`.

Now you can hit the URL `http://habrahabr.ru:<MockServer Port>/` where <MockServer Port> should be the port you have started the MockServer on.

In addition you could alternatively use the following expectation:

```js
xmlHttpRequest.send(JSON.stringify({
    "httpRequest": {
        "method": "GET", 
        "path": "/posts/api", 
        "headers": [
            {
                "name": "Host", 
                "values": "habrahabr.ru"
            }
        ]
    }, 
    "httpForward": {
        "host": "www.mock-server.com", 
        "port": 80, 
        "scheme": "HTTP"
    }, 
    "times": {
        "remainingTimes": 3, 
        "unlimited": false
    }
}));
```

This expectation sets the `Host` header which will be added by any browser or standard HTTP client.  This would ensure the MockServer only responds to requests sent to `http://habrahabr.ru/posts/api` or `https://habrahabr.ru/posts/api`.

I'm going to close this issue but let me know if this is not clear.
