### ISSUE TITLE
clean shutdown of mockserver

### ISSUE THREAD

**Issue by dbyron0** [jamesdbloom/mockserver#109]
I'm looking for a way to cleanly shut down a mockserver. I'm using it in an rspec test.  At the moment, I'm starting it like this:
```
pid = Process.spawn("java -jar spec/mockserver-netty-3.9.6-jar-with-dependencies.jar -serverPort #{port}")
```

but, short of killing the process I'm not sure how to stop it cleanly.  Suggestions?

**Comment by jamesdbloom** [comment]
You can send a `PUT` request to `/stop` then the MockServer will shut itself down.

As soon as I get a chance I intend to improve the Ruby client API to add these types of calls more explicitly.  Unfortunately the Ruby client is falling behind the Java client.  Once I have finished some more documentation then I'll improve the Ruby client.

I'm closing this ticket but let me know if you need more information on shutting down MockServer.

**Comment by jamesdbloom** [comment]
The work on the ruby client is issue #84
