### ISSUE TITLE
Option to disable log files creation

### ISSUE THREAD

**Issue by maxgalbu** [jamesdbloom/mockserver#118]
Is there an option to disable the creation of log files? (for instance, mockserver.log and mockserver_request.log)

**Comment by jamesdbloom** [comment]
Currently it is not possible to disable log file creation with logback.  Unfortunately even if no lines are written to the log file logback still creates the file.  When I get time I'll create a subclass of the  `ch.qos.logback.core.rolling.RollingFileAppender` that delays the creation of files until the first log line is written.  Then when the log level is set to OFF using `-Droot.logLevel=OFF` no files would be created.

**Comment by maxgalbu** [comment]
Sounds like a lot of work... thanks :smiley:

**Comment by jamesdbloom** [comment]
This now works, so if you want to not create the log file you use `-Dmockserver.logLevel=WARN`  this way the log file will only be created for a WARN or ERROR level log message.  You could even use `-Droot.logLevel=OFF -Dmockserver.logLevel=OFF`  to ensure no log file is ever created (except the request log if you use the dumpToLog feature).

**Comment by jamesdbloom** [comment]
now fixed so closing

**Comment by maxgalbu** [comment]
Thanks for the change, really nice. I'm using the new version of the jar, but it gives me an error when i try to use it - it says i can only use these options: [-serverPort <port>] [-proxyPort <port>] [-proxyRemotePort <port>] [-proxyRemoteHost <hostname>]

**Comment by jamesdbloom** [comment]
the `-D` options are JVM options so they need to passed to the JVM before the program arguments, for an example:

```bash
java -Dmockserver.logLevel=INFO -jar ~/Downloads/mockserver-netty-3.9.17-jar-with-dependencies.jar -serverPort 1080 -proxyPort 1090
```

**Comment by maxgalbu** [comment]
Oh ok, thanks!
