### ISSUE TITLE
Request: max TTL for expectations

### ISSUE THREAD

**Issue by wvanderdeijl** [jamesdbloom/mockserver#124]
would be nice if we can set a max time to live when setting an expectation. We use a central mock-server for all our mocking by all developers and testers as it mocks requests from a central application server. 
Setting the maximum number of hits to an expectation doesn't really do the trick as the application under test is a web application with exploratory testing. No way of telling how many service calls that application will be doing. Currently people are supposed to clear their expectations when they are done but not everybody does this.
Would be very useful if we can set an expectation and have it live for a set time so it will auto-clear.

**Comment by jamesdbloom** [comment]
I have now added this I still need to a little manual testing and think about any integration tests that may be required but all the code and unit level tests are completed.

**Comment by wvanderdeijl** [comment]
Wow, that's fast after submitting the request. Thanks for that.
Looking at the code changes I can't seem to find when the expired
expectations are cleared from MockServerMatcher. Am I missing something or
will this leads to collecting (tens of) thousands of expired expectations
over time.
Clearing expired expectations based on their TTL might not be as simple as
clearing expired expectations based on their number of requests as is done
in the handle() method. The whole idea of TTL is that there are no more
requests coming in for that expectation. Perhaps we could piggyback on
other requests and have the handle() method also remove any expired
expectations that are not currently being matched.
I could also give this a try myself and submit a pull request, that's up to
you

**Comment by jamesdbloom** [comment]
Good point, I've now fixed that as per the latest commit.

**Comment by radDunin** [comment]
Hi, 
I am using ttl and remainingTimes for a while but it seems to doesn't work as expected.
I am creating two different responses for the same endpoint and one with, but the server servs only the first one, someone could help or check if it still supported?
`{
 "httpRequest": {
            "method": "GET",
            "path": "/v3/boxes"
        },
"httpResponse": {
            "statusCode": 200,
            "body": {
             "data":{}
},
"times": {
            "remainingTimes": 1,
            "unlimited": false
        },
  "timeToLive": {
            "timeUnit": "SECONDS",
            "timeToLive": 10,
            "unlimited": false
        }
}`

and screen form mock dashboard:
![image](https://user-images.githubusercontent.com/18685560/92260618-7a465e00-eed8-11ea-8a97-c0c8fa988e81.png)
