### ISSUE TITLE
test and add complete SOCKS proxy support

### ISSUE THREAD

**Issue by jamesdbloom** [jamesdbloom/mockserver#13]

**Comment by freizl** [comment]
Hi, Any update when this feature going to be released?

**Comment by jamesdbloom** [comment]
I had several other major features to add that were higher in the pipeline, those are now completed except for the documentation.  Once I have updated the documentation on the new features (such as a "not(..)" operator or support for Json Schema) then I will focus on this issue.

**Comment by jamesdbloom** [comment]
This is now fixed, still need to add more integration tests specifically for SOCKs and documentation on the website.

**Comment by freizl** [comment]
:+1:
