### ISSUE TITLE
New features: Allow disabling keep-alive and suppressing Connection and Content-Length headers

### ISSUE THREAD

**Issue by jekh** [jamesdbloom/mockserver#130]
I'm currently writing some specialized BrowserMob Proxy and LittleProxy tests, and I'd like to be able to test the proxies' behavior when the upstream server closes the connection to indicate the end of an HTTP message. This behavior is allowed by the HTTP spec, [section 4.4](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4):
> When a message-body is included with a message, the transfer-length of that body is determined by one of the following (in order of precedence):
> [...]
> 5.By the server closing the connection.

Currently MockServer doesn't allow you to force the server to close the connection when the message has finished sending, unless the client includes a Connection: close header in the request. Keep-alive is sensible and expected default behavior, but in keeping with the "sensible defaults, powerful options" philosophy, I'd like to propose adding the ability to force the server to close the connection. 

In the same vein, MockServer automatically adds the Connection header and Content-Length headers (again, very sensible default behavior), but it would be very nice to be able to force the server to _not_ add those headers, as allowed by the spec.

So I'd like to propose adding these features to MockServer. My best idea so far is to add new methods to HttpResponse that can be set when creating the expectations:
- withKeepAlive(boolean) -- default to true, but when false, MockServer closes the connection
- withSuppressConnectionHeader(boolean) -- default to false, when true do not add the Connection header in MockServerHandler.
- withSuppressContentLengthHeader(boolean) -- default to false, when true do not add the ContentLength header in MockServerHandler.

I'm open to any other alternatives, though. Does this sound reasonable? @jamesdbloom, if you are open to this and can give some feedback, I'll put together a PR.

**Comment by jamesdbloom** [comment]
This sounds like a good idea, I was already planning on doing something very similar so I have commited a working solution.

**Comment by jamesdbloom** [comment]
I covered all the features you mentioned I also added control of whether the socket is closed or not and what value to use for the Content-Length header (in addition to suppression of Connnect, Content-Length and what value the Connect header should be).

**Comment by jekh** [comment]
Wow, this is fantastic! Thanks @jamesdbloom!
