### ISSUE TITLE
Expectation for query_parameters matches when request has different value to expected value

### ISSUE THREAD

**Issue by richardPFisk** [jamesdbloom/mockserver#131]
No matter what query_parameter is sent, the request is always matched regardless of value

"queryParameters"=>[{"values"=>["zz"], "name"=>"country"}]}

matches: 
* /v2/country=iceland
* /v2/country=zz

It should only match */v2/country=zz*

URL: /expectation Payload: {"httpRequest"=>{"method"=>#<MockServer::Model::HTTPMethod:0x007f95a13c7948 @value=:GET>, "path"=>"/v2", "queryParameters"=>[{"values"=>["zz"], "name"=>"country"}]}, "httpResponse"=>blah", "delay"=>{"timeUnit"=>#<MockServer::Model::TimeUnit:0x007f95a13c5350 @value=:SECONDS>, "value"=>0}}, "times"=>{"remainingTimes"=>1, "unlimited"=>#<MockServer::Model::Boolean:0x007f95a13cc6c8 @value=false>}}

**Comment by jamesdbloom** [comment]
I assume you are using the ruby client, is that correct?

**Comment by jamesdbloom** [comment]
I have double checked this does not look like an issue with the MockServer itself so I assume it is with the ruby client itself.  I'll look into this as soon as possible.  I will also however be completely re-writting the ruby client as it has become a little out of sync with the other clients and it's model has not kept up with the latest development in the MockServer.  I want to re-write it complete in a new clean way with extremely high test coverage.

**Comment by calvinmuller** [comment]
I'm finding the same problem - it occurs when 1 GET expectation does not have any queryStringParameters.

When I give all of them a queryString then it returns the correct response. Any ideas around this?

**Comment by hobofan** [comment]
The problem is that the `query_parameters` will be converted to `queryParamters` in the registration request. However mockserver expects `queryStringParameters`.

From a quick check the javascript library seems to have the same problem.

I'll see if I can create a pull request.

**Comment by jamesdbloom** [comment]
this has now been fixed, although the new ruby client has not yet been released.  I will release it in the next couple of days.
