### ISSUE TITLE
Support MultipartBody for request matcher / expectations

### ISSUE THREAD

**Issue by ravithejaperla** [jamesdbloom/mockserver#132]
For my application, i am trying to write Mock tests for testing Upload  functionality , i am facing difficulties while writing.

//From my Application REST Client Upload functionality expects as stated below:
Remote Address:
127.0.0.1:8080
Request URL:
http://localhost:8080/pincode/upload
Request Method:
POST
Status Code:
200 OK
Response Headers
Access-Control-Allow-Headers:
x-requested-with, Content-Type, Accept
Access-Control-Allow-Methods:
POST, GET, OPTIONS, DELETE
Access-Control-Allow-Origin:
*
Access-Control-Max-Age:
3600
Content-Type:
application/json;charset=UTF-8
Date:
Wed, 20 May 2015 04:03:45 GMT
Server:
Apache-Coyote/1.1
Transfer-Encoding:
chunked
X-Application-Context:
application
Request Headers 
Accept:
_/_
Accept-Encoding:
gzip, deflate
Accept-Language:
en-US,en;q=0.8
Connection:
keep-alive
Content-Length:
1013
Content-Type:
multipart/form-data; boundary=----WebKitFormBoundary7LuAbBLvdBX2myhL
Host:
localhost:8080
Origin:
http://localhost:9000
Referer:
http://localhost:9000/
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
Request Payload
------WebKitFormBoundary7LuAbBLvdBX2myhL Content-Disposition: form-data; name="file"; filename="pincode_master_data.csv" Content-Type: text/csv 

//Please help me in writing Mock test for the above requirement
//I tried writing as below, but it is not working

new MockServerClient("127.0.0.1",1080).when(
                      request()
                      .withMethod("POST")
                      .withPath("/pincode/upload") 
                      .withHeader("Content-Type", "multipart/form-data")
                      .withHeader("Content-Disposition", "/home/ravi/Downloads/pincode_master_data.csv")

```
                  )
                 .respond(
                          response()
                          .withStatusCode(200)
                  //.withHeader("Content-Type", "application/json;charset=UTF-8")
                  .withBody("Hi file is Uploaded")


            );
```

// I am testing this Mock test, using Rest-assured as stated below
//Making Use of given().contentType().multiPart().when().post() for Testing Search with URL
com.jayway.restassured.response.Response response_Upload = given().contentType("multipart/form-data").multiPart(new File("/home/ravi/Downloads/pincode_master_data.csv")).expect().response().when().post("/pincode/upload"); 

String responseBody_Upload = response_Upload.getBody().asString();
System.out.println("Response for Upload Query");
System.out.println(responseBody_Upload);

//Data in /home/ravi/Downloads/pincode_master_data.csv
//===========================================

Pincode, Region Code, Area, Area Code, City, City Code, State, State Code, Cluster Code
110021, MLNCR, ANTARIKSH, ANT, NEWDELHI, DEL, DELHI, DEL, NULL
110022, MLNCR, CPBRANCHOFFICE, CP, NEWDELHI, DEL, DELHI, DEL, NULL
110023, MLNCR, ANTARIKSHBHAVAN, ABC, NEWDELHI, DEL, DELHI, DEL, NULL
110024, MLNCR, ANTARIKSHBHAVAN, ABC, NEWDELHI, DEL, DELHI, DEL, NULL
110025, MLNCR, RAJENDRAPLACE, RAJ, NEWDELHI, DEL, DELHI, DEL, NULL
110026, MLNCR, CPBRANCHOFFICE, CP, NEWDELHI, DEL, DELHI, DEL, NULL
110027, MLNCR, CPBRANCHOFFICE, CP, NEWDELHI, DEL, DELHI, DEL, NULL
110028, MLNCR, RAJENDRAPLACE, RAJ, NEWDELHI, DEL, DELHI, DEL, NULL
110029, MLNCR, WAZIRPUR, WZR, NEWDELHI, DEL, DELHI, DEL, NULL
110030, MLNCR, DELHICANTONMENT, DCT, NEWDELHI, DEL, DELHI, DEL, NULL
110031, MLNCR, ANTARIKSH, ANT, NEWDELHI, DEL, DELHI, DEL, NULL

**Comment by jamesdbloom** [comment]
Sorry for the delay but are you still having issues?

**Comment by jamesdbloom** [comment]
Have you tried using the MockServer Proxy to record you requests?  Although record-replay is an anti-pattern the MockServer Proxy will generate the Java code (or JSON) for expectations once requests have been recorded.  You can then modify these as required to make them suitable for test expectations and copy them into your test code or test setup code.  Please see http://www.mock-server.com/proxy/record_and_replay.html

**Comment by jamesdbloom** [comment]
Closing this ticket now

**Comment by Vampire** [comment]
I think the problem here is, that there is no `MultipartBody` that decodes a multipart body and allows to formulate expectations for the parts.
I tried this myself after a question in the Gitter room and the closest i came was a substring or regex match.
And looking at the expectation OP tried to write here, he tried to match "headers" (´Content-Disposition`) of the multipart-part, besides that the value was wrong.
Can this be opened as request to add support for multipart bodies or should a new ticket be opened?

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature can be more effectively managed, see: https://trello.com/c/zt7loffA/14-add-support-for-multipartbody
