### ISSUE TITLE
java.lang.NoSuchMethodError  When loading a Json ShemaBody from a file

### ISSUE THREAD

**Issue by jdevora** [jamesdbloom/mockserver#146]
Hi,
 When I try to load a json file I get an NoSuchMethodError 

I'm using mockserver-netty-3.9.15-jar-with-dependencies.jar 
and the code is 

JsonSchemaBody jsonSchemaBody = jsonSchemaFromResource("org/mockserver/model/testJsonSchema.json");

The stack trace is:
```
     [java] 1) testSendPushToIphoneWithMockServer(engine
.deliverers.IPhonePushDelivererTest)java.lang.NoSuchMethodError: org.apache.comm
ons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/la
ng/String;
     [java]     at org.mockserver.model.JsonSchemaBody.readFileFromClassPathOrPa
th(JsonSchemaBody.java:36)
     [java]     at org.mockserver.model.JsonSchemaBody.jsonSchemaFromResource(Js
onSchemaBody.java:27)

```

**Comment by jamesdbloom** [comment]
Which version of `commons-io` do you have in your project?  

The MockServer uses the following:

```xml
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-io</artifactId>
    <version>1.3.2</version>
</dependency>
```

If your project is importing an older version then you would likely get the `NoSuchMethodError`.

**Comment by jdevora** [comment]
No, 
I checked that that with JWhich: 
     [java] Class 'org.apache.commons.io.IOUtils' found in 'file:/Service/lib/commons-
o-1.3.2.jar!/org/apache/commons/io/IOUtils.class'


I'm getting confused with java/nio/charset/Charset , if I go to the line 36 in 
 mockserver/mockserver-core/src/main/java/org/mockserver/model/JsonSchemaBody.java   it passes in a String, not a Charset and uses the "Google's charset"

But if I "decompile" mockserver-netty-3.9.15-jar-with-dependencies.jar , it is still referencing to  the old Apache reference:

* 20: invokespecial #10                 // Method java/io/FileInputStream."<init>":(Ljava/lang/String;)V
         * 23: astore_1
         * 24: aload_1
         * 25: getstatic     #11                 // Field org/apache/commons/io/Charsets.UTF_8:Ljava/nio/charset/Charset;
         * 28: invokestatic  #12                 // Method org/apache/commons/io/IOUtils.toString:(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String; 
 
Could it be that the "jar with dependencies" was uploaded to Maven central without a clean build?


How could I generate the "jar with dependencies" locally from the a git clone?

**Comment by jamesdbloom** [comment]
It is extremely unlikely to be anything to do with the build not being cleaned, as the upload process and build is completely automated and repeatable and has run 100 or times without issue.

The Charset is also not relevant because a string is being passed to IOUtils.toString, the signature is as follows:

```java
public static String toString(InputStream input, String encoding)
```

Also how does JWich work?  What happens if you have two copies of the IOUtils class, will it show both jars?  The normal approach for a maven project to resolve this sort of dependency issue is to use:

`mvn dependency:tree`

Can you please run that command and paste the response.

**Comment by jamesdbloom** [comment]
Also I don't believe this will help you, however, if you want to run the build your self please see the instructions at: http://mock-server.com/mock_server/running_mock_server.html#build-and-run-from-source

**Comment by jamesdbloom** [comment]
Did you manage to run the `mvn dependency:tree` command?

**Comment by jdevora** [comment]
I gave up reading from a file and hardcoded the Json as a string in the test itself...

I think that the main issue is that the version mockserver-netty-3.9.15-jar-with-dependencies.jar on Maven Central is still using the Apache "Charset" and the one that I cloned from GitHub, is using Google's version.  
Due some restrictions on that project, I have to use the "jar with dependencies" one.

JWhich is an old tool that I downloaded many years ago from http://www.clarkware.com/software/JWhich.html and is now gone, the relevant method is:
```
    /**
     * Prints the absolute pathname of the class file
     * containing the specified class name, as prescribed
     * by the class path.
     *
     * @param className Name of the class.
     */
    public static String returnWhich(String className) {
        String result = "";
        String resource = new String(className);
        //
        // Format the file name into a valid resource name.
        //
        if (!resource.startsWith("/")) {
            resource = "/" + resource;
        }
        resource = resource.replace('.', '/');
        resource = resource + ".class";
        //
        // Attempt to locate the file using the class loader.
        //
        java.net.URL classUrl = JWhich.class.getResource(resource);
        if (classUrl == null) {
            result = "ERROR: Class '" + className + "' not found.";
        } else {
            result = "Class '" + className + "' found in '" + classUrl.getFile() + "'";
        }
        return result;
    }
```
It will point out the class or jar file name that has been used  to load this class.


Here is a partial  `mvn dependency:tree ` but as I said, it is not from the version that I have the problem with
```
[INFO] ------------------------------------------------------------------------
[INFO] Building MockServer 3.9.16-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ mockserver ---
[INFO] org.mock-server:mockserver:pom:3.9.16-SNAPSHOT
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MockServer Logging 3.9.16-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ mockserver-logging -
--
[INFO] org.mock-server:mockserver-logging:jar:3.9.16-SNAPSHOT
[INFO] +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] \- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO]    \- ch.qos.logback:logback-core:jar:1.1.3:compile
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MockServer Core 3.9.16-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocate
d to commons-io:commons-io:jar:1.3.2
[INFO]
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ mockserver-core ---
[WARNING] While downloading org.apache.commons:commons-io:1.3.2
  This artifact has been relocated to commons-io:commons-io:1.3.2.
  https://issues.sonatype.org/browse/MVNCENTRAL-244


[INFO] org.mock-server:mockserver-core:jar:3.9.16-SNAPSHOT

```
