### ISSUE TITLE
MockServer start gets stuck on error

### ISSUE THREAD

**Issue by BlackDr0id** [jamesdbloom/mockserver#150]
At any attempt to start a MockServer which results in an error (typically if the port is already in use), the call gets stuck and does never return. Example:
```java
ClientAndServer.startClientAndServer(1234);    // success - server started
ClientAndServer.startClientAndServer(1234);    // java.net.BindException in log - call never returns!
```
Problem is in MockServer.java. A new thread is started to start the mock server. This is done in a try/catch block. If start was successful, the SettableFuture result is set and the calling thread proceeds. If an exception occurs though, the SettableFuture is not set and the blocking outer call waits forever.

**Solution suggestion:**
Make sure in the "finally" block, that the SettableFuture actually got set. If not already set, set a value like "FAILURE" (for example). It seems, the actual value is currently not used. The outer thread would either have to check if the result is "STARTED" or "FAILURE", or the SettableFuture.cancel() could be used as well. Also, the constructor should forward the exception to give any caller the chance to react.
Example:

```java
// MockServer.java
    public MockServer(final Integer port) {
// [...]
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
// [...]
                    // Server start successful
                    hasStarted.set("STARTED");
// [...]
                } catch (InterruptedException ie) {
                    logger.error("MockServer receive InterruptedException", ie);
                } finally {
                    if (!hasStarted.isDone()) {
                        hasStarted.set("FAILED");
                    }
                    bossGroup.shutdownGracefully(0, 1, TimeUnit.MILLISECONDS);
                    workerGroup.shutdownGracefully(0, 1, TimeUnit.MILLISECONDS);
                }
            }
        }).start();

        try {
            if ("FAILED".equals(hasStarted.get())) {
                throw new SomeExpressiveConnectionException();
            }
        } catch (Exception e) {
            logger.warn("Exception while waiting for MockServer to complete starting up", e);
            throw e;
        }
    }
// [...]
    public boolean isRunning() {
        if (hasStarted.isDone() && ! "FAILED".equals(hasStarted.get())) {
```

**Comment by jamesdbloom** [comment]
This is now fixed, please retest using the latest SNAPSHOT version or wait for the next release

**Comment by BlackDr0id** [comment]
Great! Thanks a lot for the super-quick fix!
Is there a date already for the 3.9.17 release?

**Comment by jamesdbloom** [comment]
I expect the release to be in the next couple of days, just as soon #133 and #151 have been fixed / merged.

**Comment by BlackDr0id** [comment]
Cool! Thanks for the reply

**Comment by jamesdbloom** [comment]
Just releasing now, it should appear on Maven Central in the next few hours (as it take time to sync from Sonatype)

**Comment by dzmitrykashlach** [comment]
James,

I'm getting error with version 3.10.2

java.lang.RuntimeException: Exception while binding MockServer to port 1234
	at org.mockserver.mockserver.MockServer.bindToPorts(MockServer.java:108)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:61)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:20)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:29)

How can it be resolved?
