### ISSUE TITLE
Clearer command line arg docs

### ISSUE THREAD

**Issue by wildcatgerry** [jamesdbloom/mockserver#152]
Thank you for a such great software.

I spent some time trying different things to get the proxy recording working correctly in the end.

Please make the command line arg documentation clearer, providing sample input.

I found myself guessing what you meant, for example, what format is the -remoteProxyHost? I orignally tried http://localhost but got a long stacktrace with the actual descriptive error half way down, host name unresolved, so I tried localhost and it worked.

Please also use punctuation.

**Comment by jamesdbloom** [comment]
I have added an example in the usage output, I have also added argument validation.

However, I have no idea what you refer to when you say please also use punctuation, perhaps you could explain with a little detail.

**Comment by wildcatgerry** [comment]
Thanks for looking at this. Now I am afraid I sound like a grammar Nazi. 
It was just hard to read because of the line wrapping without clear grammar.

```
specifies the HTTP, HTTPS, SOCKS and HTTP
CONNECT port for proxy, port unification
supports for all protocols on the same port

specifies the HTTP and HTTPS port for the
MockServer port unification is used to
support HTTP and HTTPS on the same port
```

Could be updated to something like 
```
Specifies the HTTP, HTTPS, SOCKS and HTTP
CONNECT port for proxy. Port unification
is used to support all protocols on the same port.

Specifies the HTTP and HTTPS port for the
MockServer. Port unification is used to
support HTTP and HTTPS on the same port.
```

**Comment by jamesdbloom** [comment]
I agree with you punctuation suggestions making it clearer.  I have now updated it.  Both changes are in the current SNAPSHOT and will be in the next RELEASE.
