### ISSUE TITLE
Recorded requests timestamp

### ISSUE THREAD

**Issue by wildcatgerry** [jamesdbloom/mockserver#153]
Please timestamp the requests in a comment instead of just raw text so the whole file can be copy-pasted.

    // 2015-07-01 18:04:07,027 
        new MockServerClient("localhost", 1080)
        .when(

**Comment by jamesdbloom** [comment]
I'm not sure what you mean can you explain more...

**Comment by wildcatgerry** [comment]
In the mockserver_request.log all the requests are time stamped.

    2015-07-01 18:04:07,027 
        new MockServerClient("localhost", 1080)
        .when( 
   ...

The file has many requests which mix java and raw text. It would be nice it the whole document was just java source.

    // 2015-07-01 18:04:07,027 
        new MockServerClient("localhost", 1080)
        .when( ....

**Comment by jamesdbloom** [comment]
I have now fixed this, so closing issue, its now in the SNAPSHOT and it'll be in the next RELEASE version.

**Comment by jamesdbloom** [comment]
By the way I dropped the time stamp as it was the time that the log entry was written and no the time the request was received so it seemed pointless.

**Comment by wildcatgerry** [comment]
Thank you
