### ISSUE TITLE
Allow multiple when() cases in ForwardChainExpectation

### ISSUE THREAD

**Issue by innokenty-shuvalov** [jamesdbloom/mockserver#154]
The [docs] say that you can write expectations as follows:

```java
mockServer
        .when(request().withMethod("POST").withPath("/login"))
        .when(request().withPath("/callback"))
        .callback(callback().withCallbackClass(
                "org.mockserver.server.PrecannedTestExpectationCallback"));
```

But the though reality is that you can't. Take a look at [ForwardChainExpectation] class: there's no ```when()``` method anymore. Is that a bug or did you decide to remove this feature?

[docs]: http://mock-server.com/mock_server/creating_expectations.html
[ForwardChainExpectation]: https://github.com/jamesdbloom/mockserver/blob/master/mockserver-client-java/src/main/java/org/mockserver/client/server/ForwardChainExpectation.java

**Comment by jamesdbloom** [comment]
That's a typo in the documentation, the first '.when(...)' should not be there. I'll fix it next week once I'm back at my computer.

**Comment by jamesdbloom** [comment]
this is now fixed on the website
