### ISSUE TITLE
Feature request: mock "close without response"

### ISSUE THREAD

**Issue by flozano** [jamesdbloom/mockserver#155]
I'm trying to harness the behaviour of my client under a failure condition of the remote server, in which the server just drops the connection after some time, without returning any HTTP response.

I can do it now with my own on-purpose server, but it'd be great if something like this was available in mockserver:
```java
		mockServer
				.when(request()
						.withMethod("GET")
						.withPath("/something")
				.dropConnection(TimeUnit.SECONDS, 10)
``` 
or
```java
		mockServer
				.when(request()
						.withMethod("GET")
						.withPath("/something")
				.respond(response().withDelay(TimeUnit.SECONDS, 10).dropConnection())
```
or whatever makes the most sense.

**Comment by jamesdbloom** [comment]
I think I already support the use case you need, via the ConnectionOptions, for example:

```java
response()
        .withStatusCode(500)
        .withBody("some_body")
        .withDelay(new Delay(TimeUnit.MICROSECONDS, 1))
        .withConnectionOptions(
                new ConnectionOptions()
                        .withCloseSocket(true)
        )
``` 

See: http://www.mock-server.com/mock_server/creating_expectations.html#connection_options

Please test this and see if it fits your use case.  If not I can improve the ConnectionOptions to fit your use case.

**Comment by flozano** [comment]
I think what I'm trying to mock here is slightly different. In your example you're actually returning an status code. What I need (unfortunately from a real-world use-case that I'm trying to protect my http client against) is that the server doesn't even respond with an HTTP answer, just drops the connection after some timeout.

**Comment by jamesdbloom** [comment]
Yes that makes sense. Having thought about it, I'll add an HttpError with will be another type of response (in addition to HttpResponse, HttpForward and Callback).  Currently I'm thinking to add: delay, dropConnection and rawResponse (byte[]) to this object.  This would then support after a delay dropping the connection or after a delay returning any sequence of raw bytes (including invalid HTTP responses).

I think this should meet your requirement?

**Comment by flozano** [comment]
definitely, that would be great for my test

**Comment by jamesdbloom** [comment]
I'm completed a first cut of HttpError, it should have all the features and support you need.  The only remaining work is to double check I have all the test coverage I need and to do extra more rigerous manually testing.  Please try it out using the SNAPSHOT version: http://www.mock-server.com/where/maven_central.html#sonatype_snapshot

**Comment by jamesdbloom** [comment]
This should now be completed.  Once I updated the documentation I'll release it.  I want to wait until I've done the documentation as sometimes minor improvements / tweaks come to mind when documenting and having to explain a new feature.  I'll do that in the next 4 or 5 days, but in the mean time please try the SNAPSHOT version.
