### ISSUE TITLE
Transferring values from the request to the response

### ISSUE THREAD

**Issue by fatihtekin** [jamesdbloom/mockserver#158]
Hi 

Is it possible to return the response body by using one of the request parameters? 

For example I have a request below as below and /catalog/book/id parameter is unique per request.

```
<catalog>
   <book id="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
   </book>
</catalog>
```
Now i  want to use /catalog/book/id parameter in the response like below.

```
<Response>
   <book id="bk101" status='SUCCESS' desc='Book added successfully'>
</Response>
```

And i want to have above response changing based on the request /catalog/book/id parameter dynamically. Is this possible with mock-server or can you guide how to design this type of functionality?

Cheers

**Comment by jamesdbloom** [comment]
The best way to do this would be to use an Action of type HttpCallback.  You would then provide a class to the callback which could read the request and format a dynamic response.  For more information on callbacks see: http://mock-server.com/mock_server/creating_expectations.html#callback.

I'm going to close this ticket as I think this answers your question if not please re-open of pose the question on: https://gitter.im/jamesdbloom/mockserver

**Comment by fatihtekin** [comment]
is tihs also possible to do with java script i could not find any proper example
