### ISSUE TITLE
Verify no interactions with mock server

### ISSUE THREAD

**Issue by Unisay** [jamesdbloom/mockserver#171]
For the negative test case I need to verify there were no interactions with the mock server.
Analog of `Mockito.verifyZeroInteractions()`

Currently I can only verify interactions for some `HttpRequest[s]`.
Is it possible to do something like `MockServerClient.verify(request(), VerificationTimes.exactly(0))` ?

**Comment by jamesdbloom** [comment]
It should be possible to do

```java
MockServerClient.verify(request(), VerificationTimes.exactly(0))
```

I have added an extra test to cover that scenario however the test passed as soon as I added it.

This will ensure that a request that matches all requests has been seen exactly zero times.  I have also added a syntactic sugar method to the client that underneath does the same thing:

```java
MockServerClient.verifyZeroInteractions()
```

**Comment by jamesdbloom** [comment]
I'm going to close this ticket
