### ISSUE TITLE
Where is the proper channel to get community support for mockserver?

### ISSUE THREAD

**Issue by poiuytrez** [jamesdbloom/mockserver#173]
Hi guys, 

I have a user oriented question on how to use mockserver. Where is the "official" channel to get some community support? I have not found any newsgroup and there is not any tag on stackoverflow. I am not sure where to post my question. I am aware that github is only to report issues.

Thank you for your help
poiuytrez

**Comment by brcolow** [comment]
Most likely the gitter channel, which is linked to at the top of README.md:

https://gitter.im/jamesdbloom/mockserver
