### ISSUE TITLE
using cookies with "=" and ";" creates extra broken cookies in ClientAndProxy

### ISSUE THREAD

**Issue by NobleWong** [jamesdbloom/mockserver#177]
When Mockserver ClientAndProxy interacts with cookies containing "=" or ";", in the Responses, the HttpClient creates additional cookies when it has "=" , or multiple parts in the cookie split by ";" 

[Problem maybe @ org.mockserver.codec.MockServerRequestDecoder.setCookies(HttpRequest, FullHttpRequest)]

i.e.

{
  "name" : "Set-Cookie",
  "values" : 
  [ {"sid=5vyA7NXdQQruLV9c-TrHr6xqYOblqV3j4ak; Path=/"},
{"securetoken_ea7b7bb578b2e33c9766d37f1867e906=M6nZmPcNYUowA8FdFvg6X32d4Uclhggt9w==; Version=1; Path=/; Secure; HttpOnly"} ]
} 

is set as: 

"cookies" : 
[ {
  "name" : "securetoken_ea7b7bb578b2e33c9766d37f1867e906",
  "value" : "M6nZmPcNYUowA8FdFvg6X32d4Uclhggt9w=="
  }, {
  "name" : "sid",
  "value" : "5vyA7NXdQQruLV9c-TrHr6xqYOblqV3j4ak"
} ]

**Comment by jamesdbloom** [comment]
I believe this should now be fixed in the latest commit, which I will release very shortly

**Comment by NobleWong** [comment]
Hi James,

Thanks for the really quick response / fix. Unfortunately, it didn't work for us, since we have multiple cookies that get sent with multiple components / options. With your latest, only the last sent cookie doesn't get mangled.

For example, the cookies in bold get mangled, but the one in italics does not:

curl -k -s -D - "http://localhost:9080/s/TestWA/help" -o /dev/null
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
*Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0; Path=/*
*Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/*
*Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am; Version=1; Comment="Anonymous cookie for site"; Max-Age=15552000; Expires=Sat, 19-Mar-2016 18:43:26 GMT; Path=/*
*Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0*
*Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=*
*Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am*
Cache-Control: no-cache,no-store,must-revalidate
Pragma: no-cache
Expires: Thu, 01 Dec 1994 16:00:00 GMT
_Set-Cookie: dsid=HGz7yBVqXibT-knVyFcXvbvKKdbzfItNQj-f6N8uv7aZZ802x9soLHFiLUKmKiTT-rpFndCIE5XFG5xV7cpmGA==; Path=/; HttpOnly_
Content-Type: text/html;charset=UTF-8
Content-Length: 8134
Date: Mon, 21 Sep 2015 18:43:26 GMT

**Comment by jamesdbloom** [comment]
I am currently using Netty to parse the cookies which is a shared library used by a large number of applications (for example Play).  It may be missing a feature or have a bug but that would surprise me.

Can you please tell me how you expect the cookies to be consumed as I suspect your cookies do not conform to the cookie standard. 

Thanks

**Comment by NobleWong** [comment]
I have multiple set-cookie values set by the server. The example above is a curl command against the Mockserver proxy. This is just like the example here: https://github.com/jnunemaker/httparty/issues/384. In it, it says that rfc6265 says that multiple set-cookie values should not be folded into one call.

Also, in Netty 4.1, there should be support for https://github.com/netty/netty/pull/3239

Thanks again for your attention!

**Comment by jamesdbloom** [comment]
I'm a little confused as I thought you said the cookies were getting mangled.  Is the problem actually that multiple Set-Cookie headers are getting put into a single header or that the cookies are not being parsed correctly as the solution for each of these is very different.

I'm interested to see you point about RFC6265 however unfortunately Netty 4.1 is only in Alpha at present so I don't want to upgrade yet.  Once it's in Final then I'll upgrade and I can use the new cookie parsing logic.

**Comment by NobleWong** [comment]
They're mangled in the sense that some are being cut and resent as different cookies.

The result should be:

```
Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0; Path=/
Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am; Version=1; Comment="Anonymous cookie for site"; Max-Age=15552000; Expires=Sat, 19-Mar-2016 18:43:26 GMT; Path=/
Set-Cookie: dsid=HGz7yBVqXibT-knVyFcXvbvKKdbzfItNQj-f6N8uv7aZZ802x9soLHFiLUKmKiTT-rpFndCIE5XFG5xV7cpmGA==; Path=/; HttpOnly
```

but came out to be
```
Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0; Path=/
Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am; Version=1; Comment="Anonymous cookie for site"; Max-Age=15552000; Expires=Sat, 19-Mar-2016 18:43:26 GMT; Path=/
------- Here are the extra cookies, which are the first part of the cookies above. ------
Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0
Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=
Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am
------- This one below did not get duplicated / mangled.
Set-Cookie: dsid=HGz7yBVqXibT-knVyFcXvbvKKdbzfItNQj-f6N8uv7aZZ802x9soLHFiLUKmKiTT-rpFndCIE5XFG5xV7cpmGA==; Path=/; HttpOnly
```

**Comment by jamesdbloom** [comment]
ok now I understand can you show me the full expectation you sending.  It looks like the cookies are being duplicated as the Set-Cookie header is in the expectation but this is also contributing toward a `cookie` being added to the expectation so there are two entries appearing the one with the full header details and the simple `cookie`.

**Comment by NobleWong** [comment]
Just copying the above

what I receive without the proxy:

```
$ curl -k -s -D - "http://localhost:9080/s/TestWA/help" -o /dev/null

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0; Path=/
Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am; Version=1; Comment="Anonymous cookie for site"; Max-Age=15552000; Expires=Sat, 19-Mar-2016 18:43:26 GMT; Path=/
Cache-Control: no-cache,no-store,must-revalidate
Pragma: no-cache
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Set-Cookie: dsid=HGz7yBVqXibT-knVyFcXvbvKKdbzfItNQj-f6N8uv7aZZ802x9soLHFiLUKmKiTT-rpFndCIE5XFG5xV7cpmGA==; Path=/; HttpOnly
Content-Type: text/html;charset=UTF-8
Content-Length: 8134
Date: Mon, 21 Sep 2015 18:43:26 GMT
```

with the proxy:
```
$ curl -k -s -D - "http://localhost:9080/s/TestWA/help" -o /dev/null

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0; Path=/
Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am; Version=1; Comment="Anonymous cookie for site"; Max-Age=15552000; Expires=Sat, 19-Mar-2016 18:43:26 GMT; Path=/
Set-Cookie: sid=la7KEwU_yKXgiLD1AL0OEDIIGA3jKR3OcU0
Set-Cookie: personalization_59996b985e24ce008d3df3bd07e27c1b=
Set-Cookie: anonymous_59996b985e24ce008d3df3bd07e27c1b=acgzEaAKOVRmAY9yJhP7IrC9Am
Cache-Control: no-cache,no-store,must-revalidate
Pragma: no-cache
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Set-Cookie: dsid=HGz7yBVqXibT-knVyFcXvbvKKdbzfItNQj-f6N8uv7aZZ802x9soLHFiLUKmKiTT-rpFndCIE5XFG5xV7cpmGA==; Path=/; HttpOnly
Content-Type: text/html;charset=UTF-8
Content-Length: 8134
Date: Mon, 21 Sep 2015 18:43:26 GMT
```

**Comment by jamesdbloom** [comment]
oops sorry I stupidly missed you where using the proxy, I was thinking in terms of the mock server, I think I should be able to solve this

**Comment by jamesdbloom** [comment]
I believe this commit should now at last fix you problem, once I've fixed a few more of the current open issues I will do another release.

**Comment by NobleWong** [comment]
Hi James,

It's still doing the same sort of thing in 3.10.1. Here's an output of the log, where the cookies are being stripped down and sent again (sent properly in the Set-Cookies section, and broken apart in the Cookies section).

```
17:02:36.923 [nioEventLoopGroup-3-2] DEBUG o.m.client.netty.NettyHttpClient - Received response: {
  "headers" : [ {
    "name" : "X-IS-SITESTATUS",
    "values" : [ "live" ]
  }, {
    "name" : "X-IS-CUSTOMERGROUPS",
    "values" : [ "8de1eb" ]
  }, {
    "name" : "Server",
    "values" : [ "Apache-Coyote/1.1" ]
  }, {
    "name" : "X-IS-INTERNAL-PIPELINE",
    "values" : [ "/Sites-TestWA-Site/default/Test-Help" ]
  }, {
    "name" : "Set-Cookie",
    "values" : [ "sid=EIhTojgJyYui6LtFLlx-pvBJMJWbNX-4Wmo; Path=/", "personalization_59996b985e24ce008d3df3bd07e27c1b=\"\"; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/", "anonymous_59996b985e24c
e008d3df3bd07e27c1b=abGXbBh00Khg7Yv5r7hjIBG33J; Version=1; Comment=\"Anonymous cookie for site Sites-TestWA-Site\"; Max-Age=15552000; Expires=Tue, 05-Apr-2016 21:02:36 GMT; Path=/" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "0" ]
  }, {
    "name" : "Date",
    "values" : [ "Thu, 08 Oct 2015 21:02:36 GMT" ]
  }, {
    "name" : "X-IS-DO-INCLUDE",
    "values" : [ "1" ]
  }, {
    "name" : "Content-Type",
    "values" : [ "text/html;charset=UTF-8" ]
  } ],
  "cookies" : [ {
    "name" : "personalization_59996b985e24ce008d3df3bd07e27c1b",
    "value" : ""
  }, {
    "name" : "anonymous_59996b985e24ce008d3df3bd07e27c1b",
    "value" : "abGXbBh00Khg7Yv5r7hjIBG33J"
  }, {
    "name" : "sid",
    "value" : "EIhTojgJyYui6LtFLlx-pvBJMJWbNX-4Wmo"
  } ]
}
17:02:36.938 [nioEventLoopGroup-3-2] INFO  o.m.proxy.http.HttpProxyHandler - returning response:

{
  "headers" : [ {
    "name" : "X-IS-SITESTATUS",
    "values" : [ "live" ]
  }, {
    "name" : "X-IS-CUSTOMERGROUPS",
    "values" : [ "8de1eb" ]
  }, {
    "name" : "Server",
    "values" : [ "Apache-Coyote/1.1" ]
  }, {
    "name" : "X-IS-INTERNAL-PIPELINE",
    "values" : [ "/Sites-TestWA-Site/default/Test-Help" ]
  }, {
    "name" : "Set-Cookie",
    "values" : [ "sid=EIhTojgJyYui6LtFLlx-pvBJMJWbNX-4Wmo; Path=/", "personalization_59996b985e24ce008d3df3bd07e27c1b=\"\"; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/", "anonymous_59996b985e24
ce008d3df3bd07e27c1b=abGXbBh00Khg7Yv5r7hjIBG33J; Version=1; Comment=\"Anonymous cookie for site Sites-TestWA-Site\"; Max-Age=15552000; Expires=Tue, 05-Apr-2016 21:02:36 GMT; Path=/" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "0" ]
  }, {
    "name" : "Date",
    "values" : [ "Thu, 08 Oct 2015 21:02:36 GMT" ]
  }, {
    "name" : "X-IS-DO-INCLUDE",
    "values" : [ "1" ]
  }, {
    "name" : "Content-Type",
    "values" : [ "text/html;charset=UTF-8" ]
  } ],
  "cookies" : [ {
    "name" : "personalization_59996b985e24ce008d3df3bd07e27c1b",
    "value" : ""
  }, {
    "name" : "anonymous_59996b985e24ce008d3df3bd07e27c1b",
    "value" : "abGXbBh00Khg7Yv5r7hjIBG33J"
  }, {
    "name" : "sid",
    "value" : "EIhTojgJyYui6LtFLlx-pvBJMJWbNX-4Wmo"
  } ]
}
```

**Comment by jamesdbloom** [comment]
This log output does not show that the cookies are being sent twice.  

It only show that the `Set-Cookie` head is being sent and separately that the cookie have been identified from the `Set-Cookie` header.  

The bug fix is not related to this output.  Instead the process that encodes the response ignores any cookie values that already have the same name and value in the `Set-Cookie` header, this means you would always expect to see both the `Set-Cookie` header and the cookies in the `"cookies" : [` section.

If you think the bug is still there can you please provide a curl output to show the duplicate `Set-Cookie` headers.

Also let me know if my explanation is not clear.

**Comment by NobleWong** [comment]
Actually, I just realized that I didn't rebuild my environment. 177 is fixed!

An aside, I'm using the gradle plugin in Eclipse and only updated gradle on command line and not in eclipse.

Much thanks for your help!

-Noble
