### ISSUE TITLE
MockServer 3.10.1 not available as Homebrew package

### ISSUE THREAD

**Issue by adammichalik** [jamesdbloom/mockserver#206]
Can you please add the newest MockServer as Homebrew package? There are some differences I'm experiencing comparing to the runnable JAR.

**Comment by jamesdbloom** [comment]
I have now created the following pull request for homebrew, once the build has run and the PR has been accepted the new version will be available via homebrew.  From experience this can take up to two weeks.  https://github.com/Homebrew/homebrew/pull/49818

I am going to close this ticket, please refer to the other ticket for progress on when the new version will be available.

**Comment by jamesdbloom** [comment]
The homebrew PR has now been merged so the latest version should now be available

**Comment by adammichalik** [comment]
Yes it is, thanks!
