### ISSUE TITLE
xml compare issue

### ISSUE THREAD

**Issue by fatihtekin** [jamesdbloom/mockserver#207]
Hi

How can i compare 2 xml string ?

		String prod1 ="<product dept='MEN' id='P123'><number>784</number></product>";
		String prod2 ="<product id='P123' dept='MEN'>"
				+ "<number>784</number>"
				+ "</product>";
		
       Assert.assertTrue(new XPathStringMatcher(prod1).matches(prod2)); 

Can you change the code so that we can plugin our own matchers or can you show us a way?

I cant use callback since i need the objects for the request body.

**Comment by fatihtekin** [comment]
i had to solve the issue using aspectj 
fyi

**Comment by jamesdbloom** [comment]
So am I correct to say that you would like an XmlMatcher in addition to the XPathStringMatcher?  That should not be too hard to add.

**Comment by jamesdbloom** [comment]
there is now a new matcher that matches xml and ignores attribute order or white-space, new lines, etc

once I have fixed a couple of other bugs I will release MockServer, in the meantime you could use the latest SNAPSHOT dependency

**Comment by fatihtekin** [comment]
Hi James that is really good indeed but i think we can even make it more advanced and useful by adding some parameters in xml like to be ignored as below processId which can always be changed randomly. 
                    <ReferenceNumber>#[processID]</ReferenceNumber>
Also we can have below type parameters which we can give in a kind of velocity template as i use currently. You can use velocity context send to the func as map parameters which can be used to construct the elements. I think this 2 together would make it awesome. I also have CDATA comaparison capablity in case you have xml data in CDATA which is not that necessary but also useful.

            <Parameter name="MSISDN">${msisdn}</Parameter>


Below class compares xmls as order independendent and ignores #[] parameters and also replaces parameters.

 [XPathStringMatcherAspect.txt](https://github.com/jamesdbloom/mockserver/files/786142/XPathStringMatcherAspect.txt)
