### ISSUE TITLE
File serving through mock server without mocking data

### ISSUE THREAD

**Issue by RaghuTrivandrum** [jamesdbloom/mockserver#218]
I am using mockserver-netty-3.10.1-jar for my web application to automate UI testing.
How could I server my webapplication html pages through mockserver without mocking.
I have running mockserver in 1080 port and I would like to open login.html 
"http://localhost:1080/login.html", but by doing so it is looking for expectations and returning 404

**Comment by jamesdbloom** [comment]
I think all you need to implement is an instance of `org.mockserver.mock.action.ExpectationCallback`, this will allow you to dynamically create a response based on data in the request and therefore have a single expectation and instance of `org.mockserver.mock.action.ExpectationCallback` that supports any path you like and can then return the response you want (by loading it from a file) dynamically.  For more details see: http://www.mock-server.com/mock_server/creating_expectations.html#callback

I'm going to close this ticket as I think this give you everything you need, please feel free to re-open if you have further queries.
