### ISSUE TITLE
StringBody contains matcher

### ISSUE THREAD

**Issue by rmahnovetsky** [jamesdbloom/mockserver#222]
I'm using mockserver to mock soap responses. In order for me to mock an individual request I need to match on the contents of the body as the path is the same for most of my services.

So I'm using the RegexBody.regex to do the matching. Now I'm no regex guru so it took me a while to figure out how to match using the java pattern matcher(as this is what you use). When I test using normal regex my pattern was working but not with RegexBody. After diving into your code to figure it out I found it was the way java pattern matching was working. Because the request body(see below) contains newline characters it was not matching until I added (?s) - tells Java to allow the dot to match newline characters. 
e.g.
request()
  .withPath("/B2BGateway/service/XMLSelect")
  .withBody(RegexBody.regex("(?s)._fqs:StartPtSYD/fqs:StartPt._"))

in addition I had to add .\* 

I found most of the solution to my problem from this link http://stackoverflow.com/questions/3651725/match-multiline-text-using-regular-expression.

So since I found this difficult to use I guess there may be other out there having the same problem. maybe you can make a string contains matcher? or make this matcher more intuitive, i.e no need to add (?s) and .\* ?

otherwise it works perfectly, nice tool :)

e.g. body
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" >
   <soapenv:Header/>
   <soapenv:Body>
      <SubmitXml >
  <Profile></Profile>
  <Request>
    <ldt:LocalDateTimeCT_6_0>
      <ldt:LocalDateTimeMods>
        <ldt:ReqCity>SYD</ldt:ReqCity>
      </ldt:LocalDateTimeMods>
    </ldt:LocalDateTimeCT_6_0>
  </Request>
</SubmitXml>
   </soapenv:Body>
</soapenv:Envelope>`

**Comment by jamesdbloom** [comment]
That's a sensible idea I'll try to think of a way to make this more intuitive and simple.

**Comment by rmahnovetsky** [comment]
thanks :)

**Comment by marklieberman** [comment]
+1

Please just give us a boolean to make StringBody do a contains instead of an exact match.

**Comment by jamesdbloom** [comment]
Yes that makes sense, I'll look to add that shortly.

**Comment by jakob-o** [comment]
How about passing a matcher? That would enable independent implementations.

**Comment by jamesdbloom** [comment]
I have now implemented support for sub-string matches.  For XML you may also find XML or XMLSchema matchers easier to use.  This new feature will be available in the 5.3.0 release which will be released within in the next week.

**Comment by glopeso** [comment]
If you want to use a regex rule in a json property, you can choose to use the Json Schema that allows the use of a regex in a property pattern. Here is an example of using javascript:

`httpRequest: {
            "method": "POST",
            "path": "/user",
            "body": {
                "type": "JSON_SCHEMA",
                "jsonSchema": JSON.stringify({
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "User",
                    "description": "User data",
                    "type": "object",
                  
                    "properties": {
                        "document": {
                            "type": "string",
                            "pattern": "^9\\d{10}$"
                        },
                        "username": {
                            "type": "string"
                        }
                    }
                })
            }
        },
        httpResponse: {
            "statusCode": 202,
            "body": JSON.stringify({
                "message": "success"
            })
        }`
