### ISSUE TITLE
www.mock-server.com website down? (403)

### ISSUE THREAD

**Issue by jan-molak** [jamesdbloom/mockserver#225]
Hey @jamesdbloom, is it me being silly or is the http://www.mock-server.com/ website down?
I'm getting a 403.

```
Forbidden
You don't have permission to access / on this server.
Apache/2.2.22 Server at www.mock-server.com Port 80
```

Best,
Jan

**Comment by jamesdbloom** [comment]
Yes the service provider destroyed the server by mistake.  It has now been resolved.

Thanks,

James

**Comment by jan-molak** [comment]
Awesome, cheers mate!
