### ISSUE TITLE
Ruby client does not accept PATCH (Or custom) HTTP methods

### ISSUE THREAD

**Issue by joseprl89** [jamesdbloom/mockserver#228]
The mockserver-client library for Ruby is currently not allowing to provide PATCH (or any HTTP verb outside of GET POST PUT and DELETE).

The error message raised when trying to use a PATCH verb is:

> Supplied value: PATCH is not valid. Allowed values are: [:GET, :POST, :PUT, :DELETE] (RuntimeError)

I think I'll be able to work around that by embedding the code for now in my ruby workspace and edit the files, however it would be preferable to have a fix. Could you add this to your roadmap?

**Comment by joseprl89** [comment]
I'll start a pull request to include the PATCH verb (which is the one I need), however I think you should plan on accepting any verb, since non standard verbs could also be used.

**Comment by jamesdbloom** [comment]
I am actually planning on re-writting the entire ruby client to bring it more inline with the way other client's are written and to significantly simplify it, for example by not restricting specific values for HTTP methods when this is not required, etc.  I am therefore going to close this ticket as the immediate support for PATCH has been provided in the PR and the more flexible will be introduced once I re-write the ruby client.

**Comment by joseprl89** [comment]
@jamesdbloom when are you planning to release this code? I'd like to swap back to importing a gem rather than keeping a copy of the code in my repo.
