### ISSUE TITLE
Setting up multiple expectations in a single call

### ISSUE THREAD

**Issue by abhi92** [jamesdbloom/mockserver#230]
Is there a way to set up multiple expectations with a single call (with something like an array of JSON expectation objects)?

**Comment by abhi92** [comment]
To clarify further, instead of using a client, I was setting up the mocks by storing the expectations in a JSON array & making a series of PUT calls. Just wanted to know if there is already a way to handle multiple expectations in a single call.

**Comment by jamesdbloom** [comment]
There is no current way to setup multiple expectations by passing in an array of expectations.  This is currently not a planned feature, although there is nothing specifically wrong with this currently there are two many important extensions that need to be implemented.  Therefore I will close this ticket.

**Comment by gokareless** [comment]
sad :(

**Comment by jamesdbloom** [comment]
This feature is in fact implemented and supported but only by the REST API and not via the MockServerClient.

**Comment by leozilla** [comment]
@jamesdbloom should this also work with an `ExpectationInitializer`? like so:

```
public class SecupayExpectationInitializer implements ExpectationInitializer {
    @Override
    public Expectation[] initializeExpectations() {
        return new Expectation[]{
                new Expectation(
                        request().withMethod("POST").withPath("/api/v2/Payment/Secupaycreditcards"))
                        .thenRespond(callback().withCallbackClass(PostPaymentSecupaycreditcardsHandler.class.getName())
                ),
                new Expectation(
                        request().withMethod("POST").withPath("/api/v2/Payment/Secupaycreditcards"))
                        .thenForward(callback().withCallbackClass(PostSecupayWebhookHandler.class))
        };
    }
}
```

My use case is that I would like to both return a HTTP response and invoke a webhook.
