### ISSUE TITLE
Retrieve unmatched expectations?

### ISSUE THREAD

**Issue by gabrielf** [jamesdbloom/mockserver#236]
Hi, I want to assert that all expectations that I've setup has been matched. Is there a way to do this? I'm looking at the code and it looks to me that `curl -XPUT 'http://localhost:8046/retrieve?type=expectation'` should return the expectations that haven't been matched yet (since they are removed when matched https://github.com/jamesdbloom/mockserver/blob/daf5be4ef0e730144aefdbc4e6e0e38126598b66/mockserver-core/src/main/java/org/mockserver/mock/MockServerMatcher.java#L63-L66 )

But the behavior I'm seeing it the complete opposite. Retrieving expectations seem to return only matched expectations.

Am I using the API in the wrong way or just misinterpreting the code or both? Is there another way to see if all expectations have been used without having to know how many of them I set up in the first place?

**Comment by jamesdbloom** [comment]
The `/retrieve?type=expectation` endpoint returns all current expectations in the MockServer, i.e. any expectation that has been created and hasn't yet been removed.

I would suggest if you want to verify that you expectations have been matched I would suggest you use the `/verify` or `/verifySequence` endpoints (see https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/4.0.0).  These endpoints however don't exactly verify which expectation has been matched, instead they verify what requests MockServer has received, which is logically the same thing.

I'm closing the issue, but if you need more information or have another suggestion please re-open or open another different issue.

**Comment by akefirad** [comment]
> These endpoints however don't exactly verify which expectation has been matched, instead they verify what requests MockServer has received, which is logically the same thing.

I’m not sure if I can agree with that. If I write my expectations properly, a single call to get “unmatched expectations” would be enough to verify all the requests. Adding verification for every single expectation involves a lot of duplicate code. I guess it’s possible to reuse the request match objects but it’s a bit too much of noise in  test main body IMO. Does that make sense you @jamesdbloom?
If not, is there any workaround/hack for this functionality? (Happy to help if needed)

**Comment by akefirad** [comment]
Just found something by trail-n-error: does `mockserver.retrieveActiveExpectations(request())` does the trick? Meaning, the method should return empty array if all expectations are used (and removed) on the server? (I guess for exceptions with unlimited `times` it's a bit tricky, but I can live with that.)
