### ISSUE TITLE
Retrieve expectations are not working with grunt task

### ISSUE THREAD

**Issue by GiritharanR** [jamesdbloom/mockserver#237]
I have created the grunt task to set an expectations and tried to retrieve the same. 

```
var path = '/somePathOne';
var client = mockServerClient("localhost", 9000);
client.mockSimpleResponse(path, {name: 'one'}, 201);
client.mockSimpleResponse('/somePathTwo', {name: 'two'}, 202);
var expectations = client.retrieveExpectations(path);
console.log(expectations);
```

but it is not returning the expectations matched for the path. instead it is always returned as below

``` json
{ state: 'pending' }
```

I have verified in the mockserver.log after made the expectations. Expectations can be found at mockserver log, but it is not returning while calling with `retrieveExpectations`.

[mockserver.txt](https://github.com/jamesdbloom/mockserver/files/206247/mockserver.txt)

Advice me how to retrieve expectations with in javascript. I have tried `retrieveExpectations` for all too. Still the same. For me, it looks like `retrieveExpectations` didn't made contact at all.

**Comment by GiritharanR** [comment]
@jamesdbloom - Could you please guide me on this?

**Comment by jamesdbloom** [comment]
The client returns promises so the following code should fix your issue:

```js
var mockServer = require('mockserver-client'),
  mockServerClient = mockServer.mockServerClient;

var path = '/somePathOne';
var client = mockServerClient("localhost", 9000);
client.mockSimpleResponse(path, {name: 'one'}, 201)
  .then(function () {
      client.mockSimpleResponse('/somePathTwo', {name: 'two'}, 202)
        .then(function () {
            client.retrieveExpectations(path).then(
              function (expectations) {
                console.log(expectations);
              },
              function () {

              }
            );

          }, function (error) {
            console.log("Error creating /somePathTwo " + error);
          }
        );
    },
    function () {
      console.log("Error creating " + path + " " + error);
    }
  );
```

Please try this and re-open the issue if it is not working for you.
