### ISSUE TITLE
Ruby client doesn't correctly retrieve requests with a body

### ISSUE THREAD

**Issue by jnormington** [jamesdbloom/mockserver#239]
Here is a very basic reproducible rspec

```
RSpec.describe 'Mockserver retrieve requests' do
  it 'returns requests' do
    `curl -XPOST localhost:2000/message -d 'Hello this is a message'`

    msc = MockServer::MockServerClient.new('localhost', 2000)
    req = MockServer::Model::Request.new(method: :POST, path: '/message')

    #It will error on the below line    

    puts msc.retrieve(req)
   end
end
```

The error that comes out from retrieving the request from mockserver is 

```
Hashie::CoercionError: Cannot coerce property :body from String to MockServer::Model::Body: undefined method `each_pair' for "Hello this is a message":String
```

It appears that the coercian isn't possible because the mockserver isn't sending the body type along to the request.

There is a PR which fixes the ruby client https://github.com/jamesdbloom/mockserver/pull/238 but my gut feeling tells me it ideally should returned from the overridden toString method in all the classes extending Body like StringBody below

```
https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/model/StringBody.java#L65-L68
```

**Comment by jamesdbloom** [comment]
Closing as this issue will be fixed once the ruby client is re-written, that will happen once support for generating clients from Open API 3.0 becomes available https://github.com/swagger-api/swagger-codegen. Closing this issue as related to #182.
