### ISSUE TITLE
API for configuring client to return different responses to the same request

### ISSUE THREAD

**Issue by smutalik** [jamesdbloom/mockserver#242]
Here is my requirement:
When i send a request with some path - "/abc", i expect that it returns a 404 the first 2 times. The 3rd time i want to return a 200.

Is there any existing API for the same? I am not finding any APIs related to that.

I am using mockserver-netty-3.10.2-jar-with-dependencies.jar for my testing.

@jamesdbloom , can you please suggest/take a look?

**Comment by notecode** [comment]
> MockServer will play expectations in the exact order they are setup. For example, if an expectation A is setup to response (or forward) 3 times then expectation B is setup to response (or forward) 2 times for the same request MockServer will response (or forward) in the following order A, A, A, B, B.

How to configure this? Can you give me an example code? Thanks.

**Comment by jamesdbloom** [comment]
For details on how to do this please http://www.mock-server.com/mock_server/creating_expectations.html

In your case the following code should work:

```java
MockServerClient mockServerClient = new MockServerClient("localhost", 1080)

mockServerClient
    .when(
        request()
            .withPath("/abc"),
        Times.exactly(2)
    )
    .respond(
        response()
            .withStatusCode(404)
    );

mockServerClient
    .when(
        request()
            .withPath("/abc"),
        Times.exactly(1)
    )
    .respond(
        response()
            .withStatusCode(200)
    );
```
