### ISSUE TITLE
Verification of PATCH produces an error

### ISSUE THREAD

**Issue by mbrodie617** [jamesdbloom/mockserver#244]
When I run the ruby code:  
ProxyClient.new('localhost', 9090).verify(request(:POST, '/login') do |request|
    request.body = exact("{username: 'foo', password: 'bar'}")
    request.cookies = [cookie("sessionId", ".*")]
end)

And I change POST to PATCH and add the path and a userId as needed, I receive the following error within the terminal:
Supplied value: PATCH is not valid. Allowed values are: [:GET, :POST, :PUT, :DELETE](RuntimeError)

Can you point me to a solution or am I doing something wrong?
Thank you.

**Comment by mbrodie617** [comment]
I was able to solve this myself by adding :PATCH to the list of valid values within the /.rvm/gems/ruby-2.3.0/gems/mockserver-client-1.0.7/lib/mockserver/model/request.rb file.

If there's anything else I'm missing to make this fully funcational, please advise.

**Comment by fislam** [comment]
@jamesdbloom : I don't see the updates made [here](https://github.com/jamesdbloom/mockserver/blob/master/mockserver-client-ruby/lib/mockserver/model/request.rb) when I look at the GEM locally.  Is this version not released yet?

**Comment by jamesdbloom** [comment]
The ruby client was written by someone who has had no longer maintains it.  It will be complete replaced as soon as possible to bring it inline with all the recently and latest features that have been added but unless you submit a PR there will be no further work on the current version of the client, because it needs to be completely re-written.

**Comment by jamesdbloom** [comment]
Closing as this issue will be fixed once the ruby client is re-written, that will happen once support for generating clients from Open API 3.0 becomes available https://github.com/swagger-api/swagger-codegen. Closing this issue as related to #182.
