### ISSUE TITLE
Allow Proxy to handle expectations

### ISSUE THREAD

**Issue by eee94180** [jamesdbloom/mockserver#257]
Hi James,
I have a use case and I could not figure from documentation whether it is achievable or there is any workaround for it. Also, not sure if writing an issue is the right approach for asking this question. Could not find any mailing group in the wiki for this sort of discussion.

Use Case:
- Mock-server started as proxy using java -jar <jar_path> -serverPort <port> -proxyPort <port>
- Service/system under tests would be configured to talks to other services/systems via this proxy
- All requests are getting proxy-ed through mock-server

Question/Expectation:
- Is it possible to configure Mock-server proxy, so that some requests from service under test to other servers can be intercepted and responded back with a mock content?
- example: request going out to xyz.com/some_path will be intercepted by mock-server and a dummy response will be sent out. For all other requests, response will come from actual endpoints
- is there any workaround to achieve this use case

Context:
- I don't want to change my 'servers/system under test' code to point to mock-server URLs instead of actual endpoints
- Setting up proxy host and port can be dynamically done in my http client and that would be a small common change for all my services

Hope I am able to explain the scenario that I am struggling with. Any help would be really appreciated.

Thanks a lot,
Abhijit

**Comment by LusciousPear** [comment]
Did you ever find an answer for this? I have the same issue.

**Comment by vicbell** [comment]
Did you ever find an answer for this? I also have the same issue.

**Comment by jamesdbloom** [comment]
This isn't currently strictly supported.  It is possible to setup a forward action with an expectation that would forward calls (like a proxy), however this requires the system under test to point to MockServer explicitly, which you have stated you don't want to do.

However, I think it wouldn't be too hard to make it so that this was possible.  In summary I could make so that if you configured an expectation that matched the action from the expectation was performed (such as a mock response returned), but if there was no expectation the request was proxied.  I'll look into doing this over the next few days.

**Comment by jamesdbloom** [comment]
It is now possible to submit expectations to the MockServer Proxy.  Alternatively normal MockServer now also supports HTTP, HTTPS (i.e. HTTP CONNECT) and SOCKS style proxying.

I'm closing this ticket but once I have done some more harmonisation of the features to reduce some duplicate code, I will update the documentation.

**Comment by cosemachi** [comment]
Hi,

We are trying to use mockserver 5.3.0 to test some edge cases scenario.

I want the test cases similar to @eee94180 require.

Scenario:
1. By default, all the requests are forwarded though the proxy.
2. I want to set some expectation, and if the request match those expectation then mockserver will mock the response.

I cannot get the request to forward though the proxy.

I brew install the mock server, and start the server:
mockserver -logLevel INFO -serverPort 1080 -proxyPort 1090 -proxyRemotePort 8084 -proxyRemoteHost <the default server that response to the request's IP>

When I send a request in code (request though port 1080), then I get the log from mockserver saying that there is no expectation.

I could get around by set a default expectation by forward the request to the remote host with the remote port, and then filter the certain request by other expectation.

But by looking the comments above, it looks like I should be able use the proxy to forward the request. Just want to check if you could spot anything wrong by the way I am doing now? 

Thanks!

**Comment by orkomlosh** [comment]
> Hi,
> 
> We are trying to use mockserver 5.3.0 to test some edge cases scenario.
> 
> I want the test cases similar to @eee94180 require.
> 
> Scenario:
> 
> 1. By default, all the requests are forwarded though the proxy.
> 2. I want to set some expectation, and if the request match those expectation then mockserver will mock the response.
> 
> I cannot get the request to forward though the proxy.
> 
> I brew install the mock server, and start the server:
> mockserver -logLevel INFO -serverPort 1080 -proxyPort 1090 -proxyRemotePort 8084 -proxyRemoteHost <the default server that response to the request's IP>
> 
> When I send a request in code (request though port 1080), then I get the log from mockserver saying that there is no expectation.
> 
> I could get around by set a default expectation by forward the request to the remote host with the remote port, and then filter the certain request by other expectation.
> 
> But by looking the comments above, it looks like I should be able use the proxy to forward the request. Just want to check if you could spot anything wrong by the way I am doing now?
> 
> Thanks!

hey, did you manage to get an answer for this?
i get the same issue, 
i'm trying to get the mockserver to forward all the requests.
when im using the ecosystem (client -> mock -> server) all on my pc in localhost it's working,
but when changing to the real server it's not working.
