### ISSUE TITLE
Update docs to describe how server supports multiple ports

### ISSUE THREAD

**Issue by bjhartin** [jamesdbloom/mockserver#259]
In my case I needed the SSL port, 443, and found I can do this by providing a list of ports in the CLI, e.g. 

``` bash
java [...] org.mockserver.cli.Main -serverPort 80,443 [...]
```

Something in my stack was explicitly adding ":443" to the host and mock-server would not accept the connection.  I was happy to find that multiple ports are supported, but not documented (that I saw).

**Comment by jamesdbloom** [comment]
closing as duplicate of #115 which is currently in progress
