### ISSUE TITLE
Way to whitelist / blacklist domains for SSL proxying?

### ISSUE THREAD

**Issue by schwarzmann** [jamesdbloom/mockserver#262]
Is there a way to whitelist or blacklist a set of hosts / domains to either opt-in or opt-out of having certain domain traffic be eavesdropped on?  As a simple use case, if I'm proxying through a mockserver proxy instance, I'd like to exclude "mail.yahoo.com" so I don't accidentally record my own password exchange.

I didn't see a way to do this in the docs or in the code, but I may have missed it.  If it's currently not possible this would be a great enhancement.

**Comment by jamesdbloom** [comment]
I don't believe technically what your asking for is possible in MockServer Proxy. 

If the concern is logging / recording requests, theoretically this could be done.  However, if you want certain domains to be excluded from the proxying all together then that needs to be done at the operating system level (or where ever your configuring the proxy).

For example in Mac this can be done by filling in the section "Bypass proxy settings for these Hosts & Domains" under `System Properties` -> `Network` -> `Advanced...` as shown in the following diagram:

<img width="780" alt="screen shot 2017-06-22 at 5 15 42 pm" src="https://user-images.githubusercontent.com/733179/27444561-aafeb0a6-576e-11e7-8dda-bcb49db73836.png">

There is a similar facility in Windows and I'm sure all other OSes support this.

For this reason I'm going to close this issue, but if you can provide more information then please re-open the issue.
