### ISSUE TITLE
Override truststore and keystore from command line

### ISSUE THREAD

**Issue by james-boswell** [jamesdbloom/mockserver#263]
Hi,

When running mock server standalone from the command line, is it possible to override the keystore/truststore in use? I have tried passing the necessary system properties - ...-Djavax.net.ssl.keyStore=... - but I always receive the error "SSLException: Received fatal alert: certificate_unknown" when trying to connect which suggests it is using its own truststore.

I am using Java 1.7.0_75-b13 and mockserver-netty-3.10.4.

Thanks,
James

**Comment by bjhartin** [comment]
@james-boswell We have been able to do this by simply prepending the classpath.  We created org/mockserver/socket/... and changed the 'jar' command to include the current directory first on the classpath, e.g. "jar -cp .:REST_OF_CLASSPATH".

**Comment by james-boswell** [comment]
@bjhartin Cheers for the reply, I will give this a try tomorrow. Shame there isn't a way to achieve this through parameters or config. I am currently trialling mock server against wiremock.

**Comment by jamesdbloom** [comment]
This should now have been fixed in release 3.10.8. Please retest with that version.

I'm going to close this ticket but if you are still having the issue with that version please re-open.
