### ISSUE TITLE
Send SSL client certificate from proxy

### ISSUE THREAD

**Issue by nyx** [jamesdbloom/mockserver#267]
There's a web service I'm trying to hit via the Mock Server Proxy that requires a specific SSL client certificate (else it just doesn't answer requests and they timeout). In brief testing it appears that the SSL client certificate that I have setup might not be being sent along to the service. I didn't see any documentation indicating specifically if this is supported, however it did seem that the SSL CONNECT method should pass the client certificate along to the service (based on my somewhat limited understanding of this method). I believe in my testing I was using this method as I connect to the proxy over SSL and had to turn off server certificate validation (because I didn't want to mess with trusting the proxy CA). Please advise. Thanks!

**Comment by jamesdbloom** [comment]
It is a sensible idea to support this feature.  Once I have finished re-working / updating the documentation I will add support for client certificates in the proxy.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/41yjTwB4/17-mutual-tls-authentication-from-proxy

**Comment by jamesdbloom** [comment]
This is now implemented, once I have updated the documentation in the next week I will release a new version with this feature completed.
