### ISSUE TITLE
Option to send CORS Header?

### ISSUE THREAD

**Issue by BernhardBln** [jamesdbloom/mockserver#276]
We're starting the mock server with grunt, I'd however like to program it with javascript embedded in a HTML file that I open from the local file system.

That doesn't work due to CORS issues. 

How about adding a command-line option that allows sending custom CORS headers for the programming of expectations? (Like, support OPTIONS and send the header that e.g. allows access from all sources).

**Comment by jamesdbloom** [comment]
its not a bad idea, I have nearly finished implementing a solution that would enable CORS for the MockServer API including settings expectations, verifying requests, etc.  It won't cover the expectation responses though because that would be up to who ever is creating the expectation.

**Comment by jamesdbloom** [comment]
CORS headers are now added by default, but they can be disabled if required.

**Comment by BernhardBln** [comment]
Sweet thanks a lot :)

**Comment by rochdev** [comment]
@jamesdbloom I am facing the same issue. Any idea when the fix will be released?

**Comment by rochdev** [comment]
Also, from reading the code, it seems that you are only handling `PUT` method, and do not support custom headers, so CORS is effectively not implemented.
