### ISSUE TITLE
Allow clearing the request log only in order to use the same expectations across multiple test cases

### ISSUE THREAD

**Issue by oded-goldstein** [jamesdbloom/mockserver#281]
It would be great to add the ability to clear only the request log (and not the expectations).
This will enable setting the expectations once without reconfiguring the expectations between test scenarios.

**Comment by jamesdbloom** [comment]
how are you clearing the log / expectations, I have added support to control clearly either logs or expectations or both, as follows:

```js
"\clear?type=expectations" -- clears only expectations
"\clear?type=logs" -- clears only logs
"\clear" -- clears both logs and expectations
```

**Comment by jamesdbloom** [comment]
I have added support to the java client but not the javascript client or added documentation on the website

**Comment by jamesdbloom** [comment]
done and documentation updated, this will be in the new release which will be released in the next few days

**Comment by Tandolf** [comment]
Im still waiting for the release of this feature. Is there any date set for the new build?
