### ISSUE TITLE
Add REST API documentation

### ISSUE THREAD

**Issue by jamesdbloom** [jamesdbloom/mockserver#287]

**Comment by Cameron-C-Chapman** [comment]
@jamesdbloom Just curious, with this are you looking for a section in the documentation that describes the calls available in the ProxyClient (I'm assuming these are the endpoints you are referring to; dumpToLog, status, etc) so that someone can leverage Postman or a similar tool, are you thinking of implementing something like swagger, or are you thinking of a custom UI?

**Comment by jamesdbloom** [comment]
Initial version of the REST API can be found at https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/10.8

**Comment by jamesdbloom** [comment]
I'm closing this as the REST API is currently documented using swagger and open api.  I am in the process of re-writing the documentation on the main website so I will also produce a "nicer" version of the REST API documentation there.

Date       | Version | Java API                                                              | REST API
:--------- |:------- |:--------------------------------------------------------------------- |:-----------
12-Dec-17  | 5.2.2	 | [Java API](http://mock-server.com/versions/5.2.2/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.2.x)
11-Dec-17  | 5.2.1	 | [Java API](http://mock-server.com/versions/5.2.1/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.2.x)
10-Dec-17  | 5.2.0	 | [Java API](http://mock-server.com/versions/5.2.0/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.2.x)
06-Dec-17  | 5.1.1	 | [Java API](http://mock-server.com/versions/5.1.1/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.1.x)
05-Dec-17  | 5.1.0	 | [Java API](http://mock-server.com/versions/5.1.0/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.1.x)
05-Dec-17  | 5.0.1	 | [Java API](http://mock-server.com/versions/5.0.1/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.0.x)
04-Dec-17  | 5.0.0	 | [Java API](http://mock-server.com/versions/5.0.0/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.0.x)
30-Nov-17  | 4.1.0	 | [Java API](http://mock-server.com/versions/4.1.0/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/4.x.x)
28-Nov-17  | 4.0.0	 | [Java API](http://mock-server.com/versions/4.0.0/apidocs/index.html)  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/4.x.x)
16-Nov-17  | 3.12	 | [Java API](http://mock-server.com/versions/3.12/apidocs/index.html)   | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
10-Sep-17  | 3.11	 | [Java API](http://mock-server.com/versions/3.11/apidocs/index.html)   | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
22-Jun-17  | 3.10.8	 | [Java API](http://mock-server.com/versions/3.10.8/apidocs/index.html) | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
02-May-17  | 3.10.7	 | [Java API](http://mock-server.com/versions/3.10.7/apidocs/index.html) | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
27-Apr-17  | 3.10.6	 | [Java API](http://mock-server.com/versions/3.10.6/apidocs/index.html) | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
25-Apr-17  | 3.10.5	 | [Java API](http://mock-server.com/versions/3.10.5/apidocs/index.html) | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
06-Mar-16  | 3.10.4	 |  | [REST API](https://app.swaggerhub.com/apis/jamesdbloom/mock-server_api/3.x.x)
