### ISSUE TITLE
Downloading jar-with-dependencies from Maven using gradle

### ISSUE THREAD

**Issue by cezarykluczynski** [jamesdbloom/mockserver#289]
Is this even possible?

I tried many variants, and with no luck. Is there a way to do it?

**Comment by jamesdbloom** [comment]
As soon as I get a chance I'll add an example of how to do this.

**Comment by khmarbaise** [comment]
Have you checked to correctly use a classifier for downloading that artifact in Gradle? Would you like to download the artifact only ? I can remember there is something like `"groupId:artifactId:version:classifier@jar" (for the classifier I'm not sure).

**Comment by jamesdbloom** [comment]
I have now added documentation for this, the website will be updated in the next few days when the next release is done.
