### ISSUE TITLE
Unable to forward request to a different path

### ISSUE THREAD

**Issue by AndySeymour** [jamesdbloom/mockserver#293]
When using httpForward, if the path comes through as "/path1" it would be nice to be able to forward this to "host:port/path2" where path2 could equal something like /api/path1

**Comment by jamesdbloom** [comment]
I am currently working on (90% completed) a mechanism to template responses.  It should be fairly easy to extend this to support filter / modification of forward requests.  For more information see #240.

The main idea is that if the request being forwarded is templated either it can be forwarded exactly as it is received, by MockServer, or any part of the request can be modified, such as the path, as in your request.

**Comment by jamesdbloom** [comment]
I have now implemented a way to template a forward request.  If you want to modify the location of the request please edit the `Host` header, making sure to add `hostname:port` as the value.

*JavaScript templates*

```java
ClientAndServer.startClientAndServer(1080)
        .when(
                request()
                        .withPath(calculatePath("some_path"))
        )
        .forward(
                template(
                        HttpTemplate.TemplateType.JAVASCRIPT,
                        "return {" + NEW_LINE +
                                "     'statusCode': 200," + NEW_LINE +
                                "     'cookies': request.cookies," +
                                "     'body': JSON.stringify(" + NEW_LINE +
                                "               {" + NEW_LINE +
                                "                    method: request.method," +
                                "                    path: request.path," +
                                "                    body: request.body" +
                                "               }" + NEW_LINE +
                                "          )" + NEW_LINE +
                                "};" + NEW_LINE
                )
        );
```

*Velocity templates*

```java
ClientAndServer.startClientAndServer(1080)
        .when(
                request()
                        .withPath(calculatePath("some_path"))
        )
        .forward(
                template(
                        HttpTemplate.TemplateType.VELOCITY,
                        "{" + NEW_LINE +
                                "     \"statusCode\": 200," + NEW_LINE +
                                "     \"headers\": $!request.headers," + NEW_LINE +
                                "     \"cookies\": $!request.cookies," + NEW_LINE +
                                "     \"body\": \"$!request.body\"" + NEW_LINE +
                                "}" + NEW_LINE
                )
                .withDelay(TimeUnit.SECONDS, 5)
        );
```

When I update the documentation shortly I will add extensive documentation of how to use this feature and what the limitations / debugging approaches are.

If this is not clear please reach out before I update the documentation and I can provide some more examples.  However, the new documentation will include several examples, including how to update the `Host` header.
