### ISSUE TITLE
Longs URL aren't matched. (Greater than 4096 Bytes) 

### ISSUE THREAD

**Issue by pabloandres13** [jamesdbloom/mockserver#297]
Urls bigger that 4096 Bytes won't be matched, because in org.mockserver.server.unification.PortUnificationHandler#switchToHttp the HttpServerCodec uses the default constructor which is 4096.

I'm currently using __MockServerRule__ and after debugging I see the following error

`An HTTP line is larger than 4096 bytes.`

I cloned mockserver an changed __PortUnificationHandler__ locally to test if by increasing the __maxInitialLineLength__ the url would be matched or not, and it does work.

The change looks as follows:
```
 private void switchToHttp(ChanelHandlerContext ctx, ByteBuf msg) {
        ChannelPipeline pipeline = ctx.pipeline();
        addLastIfNotPresent(pipeline, new HttpServerCodec(8192, 8192, 8192));
        addLastIfNotPresent(pipeline, new HttpContentDecompressor());
        addLastIfNotPresent(pipeline, new HttpContentLengthRemover());
        addLastIfNotPresent(pipeline, new HttpObjectAggregator(Integer.MAX_VALUE));
        if (logger.isDebugEnabled()) {
            addLastIfNotPresent(pipeline, new LoggingHandler());
        }
        configurePipeline(ctx, pipeline);
        pipeline.remove(this);
        // fire message back through pipeline
        ctx.fireChannelRead(msg);
    }
```

I came with 2 possible solutions:
1) Overload the constructor _org.mockserver.junit.MockServerRule_ and take another parameter that could be Property object which it could be use to set the desired values.

2) Read properties from the system, something like
  `System.getProperty("netty.httpservercodec.maxInitialLineLength")`
 That would mean the person using mockserver, would have to set those properties before starting mockserver.

I'm not sure if those are valid solutions at all.

Could anyone help me?

**Comment by jamesdbloom** [comment]
Both of those solutions sounds sensible, another option would also be just to increase the default maximum.  When I get a chance I'll took into implementing increasing the default maximum and possible also the system property option.

**Comment by pabloandres13** [comment]
Ok thanks for the Feedback.

**Comment by jamesdbloom** [comment]
Sorry for the delay, but this has now been fixed and will be available in the next release, or the current SNAPSHOT version.
