### ISSUE TITLE
Remove "entrophy" warning by upgrading netty dependency

### ISSUE THREAD

**Issue by dmohs** [jamesdbloom/mockserver#299]
Seeing this warning in test logs: "Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?"

This is [fixed in netty](https://github.com/netty/netty/pull/5345), so we may only need a version bump of that dependency.

**Comment by jamesdbloom** [comment]
Closing as now resolved, but not yet released, once I finish an issue with badly behaving TLS servers then I'll release, likely in the next 2/3 days.
