### ISSUE TITLE
is there any UI  to list all expect rules or plan to do these if no existed

### ISSUE THREAD

**Issue by jiafu1115** [jamesdbloom/mockserver#301]
as titled.

**Comment by jamesdbloom** [comment]
The following REST API lists all the existing expectations: 

`/retrieve?type=expectation`

The following method on the java client lists all the existing expectations:

```java
Expectation[] retrieveExistingExpectations(HttpRequest httpRequest)
```

**Comment by jiafu1115** [comment]
@jamesdbloom I know the apis, but more guys may need one UI page to list or add or delete one rule instead write code or using tools to call the api. WDYT? any plan for it?

**Comment by jamesdbloom** [comment]
A ticket for this already exists #287
