### ISSUE TITLE
Is it possible to have a response that depends on the number of request invocations?

### ISSUE THREAD

**Issue by sorokod** [jamesdbloom/mockserver#302]
The scenario I'd like to set up is that a first triggering of an expectation returns non empty content and emulates a *"delete"* so that consequent invocations return empty content.

**Comment by sorokod** [comment]
Oh I see, this is addressed in the answer to https://github.com/jamesdbloom/mockserver/issues/280 .
Perhaps should be documented on http://mock-server.com

**Comment by jamesdbloom** [comment]
this issue is now covered under #115 so closing as duplicate
