### ISSUE TITLE
Matching delimited unordered query/form parameters

### ISSUE THREAD

**Issue by MrCreosote** [jamesdbloom/mockserver#305]
Hi,

Firstly mockserver is great, it's saved me a ton of time.

I've looked through the documentation and the various Parameter and ParameterMatcher classes but so far I haven't found what I'm looking for, which is a case like:

`&ids=id1,id4,id3,id42,id10&...`

In other words, a query or form parameter with an unordered set/list of character delimited values. For a small number of parameters it's possible to construct a lookahead regex to match but that quickly becomes unwieldy.

Is there any way to match a parameter value like this? 

Thanks.

**Comment by jamesdbloom** [comment]
Please see the example code at http://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_cookies_and_query_parameters that shows how to match parameters.  If you provide multiple values then you will be able to match query parameters with multiple values.  For example use one of the following methods:

```java
public static Parameter param(String name, String... value);
public static Parameter param(NottableString name, NottableString... value);
public static Parameter param(String name, Collection<String> value);
public static Parameter param(NottableString name, Collection<NottableString> value);
```

If that is not clear please re-open the issue.
