### ISSUE TITLE
Publish Docker tags

### ISSUE THREAD

**Issue by bsideup** [jamesdbloom/mockserver#306]
Hi!
Could you please publish Docker tag for the latest release?
We can't use `:latest` because of our policy. Thanks!

**Comment by rnavarropiris** [comment]
Same issue over here, we cannot use moving targets. Any plans on providing them in the near future?

**Comment by jamesdbloom** [comment]
Its a fair point I'll look to do this asap

**Comment by bsideup** [comment]
Hi @jamesdbloom,

Thanks! Any news regarding that?

**Comment by jamesdbloom** [comment]
This is now done, please check the docker hub for tags for most version of MockServer
