### ISSUE TITLE
add new api to batch create rules.

### ISSUE THREAD

**Issue by jiafu1115** [jamesdbloom/mockserver#316]
@jamesdbloom when I use the mock server. 
I create a lots of rules and can download all the rules by **list** method. but one day, all rules are lost by other's reset command. So I want to import the existed backup downloaded list of rule to the mockserver, Then I must import the request one by one by put method due to the put expectation method doesn't support array.

So I want to add one API to batch created rules with json body array responded by list.

WDYT?  It is one requirement for many user shared one mockserver with existed fixed rules. 

Thanks.

**Comment by jamesdbloom** [comment]
I'm happy to extend the existing logic to accept either a single exception or a list of exceptions.  I think this should be fairly trivial to do.  Then you should be able to upload a JSON list of expectations using the REST API.

**Comment by jiafu1115** [comment]
@jamesdbloom  Thanks. It is very good method to support Array.

**Comment by jiafu1115** [comment]
expect get this function ASAP. Thanks

**Comment by jamesdbloom** [comment]
this is now complete, as soon as I finishing resolve an issue a TLS issue with some badly behaving servers then I'll do a release, with this fix.  I would guess in the next 2/3 days that will happen.

Its available now in the SNAPSHOT release.

**Comment by jiafu1115** [comment]
@jamesdbloom Thank you very much!
