### ISSUE TITLE
Support  literal object as body in json in expectation

### ISSUE THREAD

**Issue by gorshkov-leonid** [jamesdbloom/mockserver#328]
Hello,
I used expectation's deserializers in java. If I specifig body as literal object then body in expectation is null. But stringified object ('xxx \n xxx\n xxx\n') is not human readable.  
 I saw issue #204. And I decide that body can be stringified object only, and cannot be literal object. How hardly is to support deserialization from object?
It it true place?:
https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/client/serialization/deserializers/body/BodyDTODeserializer.java#L78 ?

**Comment by jamesdbloom** [comment]
What type of client are you using, javascript, java, ruby, etc?

Objects need to be serialised so they can be sent to MockServer over the network so they will always need to be converted into a string.

I have add some static build methods so you can specify the json body as an object as follows:

```java
json(new TestObject())
```

**Comment by jamesdbloom** [comment]
In addition if you want to avoid specifying the object as a string literal using something to convert the object to a string literal, for example:

in java:

```java
new ObjectMapper().writeValueAsString(...)
```

in javascript:

```js
JSON.stringify(...)
```

I'm going to close this issue as there is nothing further to add.  The next release in the next week or so will include the static json builder methods that now accept object, as follows:

```java
json(new TestObject())
```

**Comment by gorshkov-leonid** [comment]
We used logged json files for testing in java. This test data is not readable.
