### ISSUE TITLE
Make MockServerRule.setMockServerClient protected or change to support inheritance

### ISSUE THREAD

**Issue by taylormathewson** [jamesdbloom/mockserver#330]
I keep the rule in a super class for my API tests.

MockServerRule.setMockServerClient only looks at the declared fields in the test class, not super classes.

I had to copy the entire rule class to modify setMockServerClient to support looking at super classes.

I'd like to request making this method protected so it can be overridden.  It might also be worthwhile to have setMockServerClient iterate over superclasses

**Comment by taylormathewson** [comment]
I've added a text file with my customization of setMockServerClient, in case it helps
[setMockServerClient snippet.txt](https://github.com/jamesdbloom/mockserver/files/973916/setMockServerClient.snippet.txt)

**Comment by jamesdbloom** [comment]
I have updated the MockServerRule to scan super classes as you suggested.  This will be in the next release in the next week or so.
