### ISSUE TITLE
Static parameters to callback class

### ISSUE THREAD

**Issue by TheShanMan** [jamesdbloom/mockserver#332]
I was reading issue https://github.com/jamesdbloom/mockserver/issues/120 and I've got something that's a little less dynamic than was requested there. I'd like to be able to pass hard coded parameters to my callback class so I can make a callback that's somewhat generic. My use case is I'd like to either return a json file or a value from within a json file. So for instance my path would be "/users" to return a json array of users or "/users/myuser" to return the "myuser" user from the json file.

Here's how I envision setting up the mock responses:
`mockServer.when(request().withPath("/users"))
        .callback(HttpCallback.callback().withCallbackClass("MyGeneralCallback", "users.json"));

mockServer.when(request().withPath("/users/.+"))
        .callback(HttpCallback.callback().withCallbackClass("MyGeneralCallback", "users.json", "username"));
`

And in the latter case, MyUserCallback would pull the user name from getPath() and then find a user record in the json where the username property equals what was pulled off of the path.

Ideally this would allow for passing an Object which would mean I could pass a map containing whatever I want in it. That could even mean passing in a custom class that has a more dynamic nature to it. Not sure if it would meet the use case described in issue 120 (I didn't read the use case closely enough to tell), but at any rate it would increase the flexibility of mockserver.

This would mean not having to spend so much time creating lots of callback classes that do similar stuff!

**Comment by jamesdbloom** [comment]
#120 is now pretty much complete and released as detailed in the last comments on that issue. 

Adding static parameters is none trivial because the type would also need to be provided and would need to be a type that could be serialised, etc.  I would suggest just using the new callback method logic.  Does that meet your use case?

**Comment by TheShanMan** [comment]
It meets it in a better way! Instead of having to pass a map I can just add constructor parameters for my callback class. Thank you for this improvement and for updating issue 120 with an example!
