### ISSUE TITLE
Commit e1fe5155c37eac2ba27228ca4fbf940e2d4d1956 breaks backward compatibility

### ISSUE THREAD

**Issue by wasyl77** [jamesdbloom/mockserver#335]
Hi,
Commit: https://github.com/jamesdbloom/mockserver/commit/e1fe5155c37eac2ba27228ca4fbf940e2d4d1956
breaks the backward compatibility. 
When using RELEASE version all projects using https://github.com/jamesdbloom/mockserver/blob/mockserver-3.10.4/mockserver-core/src/main/java/org/mockserver/model/HttpCallback.java class will no longer compile.

At least there should be some information that this class is deprecated to use, and maybe should be removed later, which will give all time to change their code.

Cheers,
Mike

**Comment by jamesdbloom** [comment]
Unfortunately doing that would introduce complexity, duplicate fields with confusing use cases and more confusion around releases.  

I don't understand why this would be an advantage?  Instead the pattern followed here is the pattern used by many modern libraries such as Netty.  This pattern is to update fields and expect those who want to update to migrate their code to the new version.  

If the code is not compiling please don't upgrade to version 3.10.4 or update the code to reflect that this field has changed.
