### ISSUE TITLE
A single ExpectationCallback expectation can't service 2 simultaneous requests

### ISSUE THREAD

**Issue by TheShanMan** [jamesdbloom/mockserver#342]
One of the requests will hang if I call a single expectation that uses an ExpectationCallback twice simultaneously. I have some sample code to demonstrate:

>        Callback callback = new Callback();
>        // works:
>        mockServer.when(request().withPath("/foobar").withQueryStringParameter("param", "call1"))
>                .callback(callback);
>        mockServer.when(request().withPath("/foobar").withQueryStringParameter("param", "call2"))
>                .callback(callback);
>        // doesn't work:
>        mockServer.when(request().withPath("/abc").withQueryStringParameter("param"))
>                .callback(callback);

And the Callback method is defined thusly:

>    public HttpResponse handle(HttpRequest httpRequest) {
>        String body = "";
>        for (Parameter parameter : httpRequest.getQueryStringParameters()) {
>            if (parameter.getName().getValue().equals("param")) {
>                List<NottableString> values = parameter.getValues();
>                if (values.size() > 0) {
>                    body = "{ \"data\": \"" + values.get(0).getValue() + "\"}";
>                    break;
>                }
>            }
>        }
>        try {
>            return HttpResponse.response()
>                    .withStatusCode(200)
>                    .withHeaders(
>                            header("Content-Type", "application/json"),
>                            header("Access-Control-Allow-Origin", "*"),
>                            header("Content-Length", body.getBytes("UTF-8").length)
>                    ).withBody(body);
>        } catch (UnsupportedEncodingException e) {
>            logger.error("Unable to process the response body", e);
>            return HttpResponse.response()
>                    .withStatusCode(HttpStatusCode.INTERNAL_SERVER_ERROR_500.code())
>                    .withHeaders(header("Access-Control-Allow-Origin", "*"));
>        }
>    }

I am running this from an angularjs page with the following method:

>        $window.getUsersAndGroups = function(path, which) {
>            if (!which || which == 1) {
>                console.log(path + " call 1");
>                $http.get(backendServer + '/' + path + '?param=call1')
>                    .then(function (response) {
>                        console.log(path + " call 1:");
>                        console.log(response.data);
>                    }, function (response) {
>                        console.log(path + " call 1 failure");
>                    });
>            }
>            if (!which || which == 2) {
>                console.log(path + " call 2");
>                $http.get(backendServer + '/' + path + '?param=call2')
>                    .then(function (response) {
>                        console.log(path + " call 2:");
>                        console.log(response.data);
>                    }, function (response) {
>                        console.log(path + " call 2 failure");
>                    });
>            }
>        };

If I call window.getUsersAndGroups("foobar") from the console it works all day long. If I call window.getUsersAndGroups("abc") I only get 1 response and the other request hangs until I kill mock-server.

Mock-server *thinks* it has responded if you go by the info level logging so it must be getting hung up somewhere in the closing of the response.

[sample.zip](https://github.com/jamesdbloom/mockserver/files/1045854/sample.zip)

**Comment by jamesdbloom** [comment]
I can't reproduce you issue.  

I have used the following code to demonstrate that the issue you are experiencing doesn't appear to be in MockServer.  This test passes successfully and shows that the callbacks you have defined are working exactly as expected.

If you disagree please re-open this ticket with a fully executable test so that I can re-produce you issue completely.

```java
package example;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockserver.client.netty.NettyHttpClient;
import org.mockserver.client.server.MockServerClient;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.mock.action.ExpectationCallback;
import org.mockserver.model.*;

import java.io.UnsupportedEncodingException;
import java.net.InetSocketAddress;
import java.util.List;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;
import static org.mockserver.integration.ClientAndServer.startClientAndServer;
import static org.mockserver.model.Header.header;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;
import static org.mockserver.model.OutboundHttpRequest.outboundRequest;


public class MockServerClientTest {

    public class GeneralJsonCallback implements ExpectationCallback {

        @Override
        public HttpResponse handle(HttpRequest httpRequest) {
            String body = "";
            // TODO - add getFirstQueryStringParameter and getQueryStringParameter methods to HttpRequest
            for (Parameter parameter : httpRequest.getQueryStringParameters()) {
                if (parameter.getName().getValue().equals("param")) {
                    List<NottableString> values = parameter.getValues();
                    if (values.size() > 0) {
                        body = "{ \"data\": \"" + values.get(0).getValue() + "\"}";
                        break;
                    }
                }
            }
            try {
                return response()
                        .withStatusCode(200)
                        .withHeaders(
                                header("Content-Type", "application/json"),
                                header("Access-Control-Allow-Origin", "*"),
                                header("Content-Length", body.getBytes("UTF-8").length)
                        )
                        .withBody(body);
            } catch (UnsupportedEncodingException e) {
                System.err.println("Unable to process the response body");
                e.printStackTrace();
                return response()
                        .withStatusCode(HttpStatusCode.INTERNAL_SERVER_ERROR_500.code())
                        .withHeaders(header("Access-Control-Allow-Origin", "*"));
            }
        }
    }

    private ClientAndServer mockServer;

    @Before
    public void startMockServer() {
        mockServer = startClientAndServer(8080);
    }

    @After
    public void stopMockServer() {
        mockServer.stop();
    }

    @Test
    public void testJsonCallback() {

        // given

        GeneralJsonCallback generalJsonCallback = new GeneralJsonCallback();

        // works:
        mockServer
                .when(
                        request()
                                .withPath("/foobar")
                                .withQueryStringParameter("param", "call1")
                )
                .callback(generalJsonCallback);
        mockServer
                .when(
                        request()
                                .withPath("/foobar")
                                .withQueryStringParameter("param", "call2")
                )
                .callback(generalJsonCallback);
        // doesn't work:
        mockServer
                .when(
                        request()
                                .withPath("/abc")
                                .withQueryStringParameter("param")
                )
                .callback(generalJsonCallback);

        // then

        assertThat(
                new NettyHttpClient().sendRequest(
                        outboundRequest(
                                new InetSocketAddress("localhost", mockServer.getPort()),
                                "",
                                request()
                                        .withPath("/foobar")
                                        .withQueryStringParameter("param", "call1")
                        )
                ).getBodyAsString(),
                is("{ \"data\": \"call1\"}")
        );

        assertThat(
                new NettyHttpClient().sendRequest(
                        outboundRequest(
                                new InetSocketAddress("localhost", mockServer.getPort()),
                                "",
                                request()
                                        .withPath("/foobar")
                                        .withQueryStringParameter("param", "call2")
                        )
                ).getBodyAsString(),
                is("{ \"data\": \"call2\"}")
        );

        assertThat(
                new NettyHttpClient().sendRequest(
                        outboundRequest(
                                new InetSocketAddress("localhost", mockServer.getPort()),
                                "",
                                request()
                                        .withPath("/abc")
                                        .withQueryStringParameter("param", "random")
                        )
                ).getBodyAsString(),
                is("{ \"data\": \"random\"}")
        );

        assertThat(
                new NettyHttpClient().sendRequest(
                        outboundRequest(
                                new InetSocketAddress("localhost", mockServer.getPort()),
                                "",
                                request()
                                        .withPath("/abc")
                                        .withQueryStringParameter("param", "")
                        )
                ).getBodyAsString(),
                is("{ \"data\": \"\"}")
        );
    }
}
```
