### ISSUE TITLE
Plexus-related build issues in mockserver-netty

### ISSUE THREAD

**Issue by dfparker2002** [jamesdbloom/mockserver#353]
Thank you for an interesting toolkit.

It looks like plexus tools do not play well (master branch/latest release). Perhaps interactions with JDK8?
Please advise.
Viz,  https://issues.apache.org/jira/browse/MASSEMBLY-742

**Local conditions**
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

**Problems**
Maze of plexus & related libs start here.

> [INFO] --- maven-assembly-plugin:2.5.1:single (default) @ mockserver-netty ---
> [INFO] Reading assembly descriptor: src/main/assembly/jar-with-dependencies/jar-with-dependencies.xml
> [INFO] Reading assembly descriptor: src/main/assembly/brew-tar/brew-tar.xml
> [WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver
> java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipArchiveEntry
>         at java.lang.Class.getDeclaredConstructors0(Native Method)
>         at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
>         at java.lang.Class.getDeclaredConstructors(Class.java:2020)
>         at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
>

**Comment by jamesdbloom** [comment]
What version of Maven are you using?  Plexus is part of maven so I think that is likely to have changed and perhaps broken backwards compatibility with the version of maven I am using to build the plugin.

**Comment by dfparker2002** [comment]
$ mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T13:58:10-07:00)
Maven home: C:\OtherJava\apache-maven-3.2.3
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by dfparker2002** [comment]
redo with maven-3.0.5
$ /cygdrive/c/OtherJava/apache-maven-3.0.5/bin/mvn.bat clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] MockServer
[INFO] MockServer Logging
[INFO] MockServer Core
[INFO] MockServer Java Client
[INFO] MockServer Integration Test
[INFO] MockServer & Proxy Netty
[INFO] MockServer Maven Plugin
[INFO] MockServer Ruby Client
[INFO] MockServer Web Archive
[INFO] MockServer Proxy Web Archive
[INFO] MockServer Maven Plugin Integration Tests
[INFO] MockServer JavaScript Client
[INFO] MockServer Example
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MockServer 3.10.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ mockserver ---
[INFO] Deleting C:\Users\User\mars-workspace (includes = [**/*.log, **/keystore.jks, **/keystore.p12], excludes = [])
[INFO] Deleting file C:\Users\User\mars-workspace\angular\node_modules\karma\console.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MockServer ......................................... FAILURE [01:19 min]
[INFO] MockServer Logging ................................. SKIPPED
[INFO] MockServer Core .................................... SKIPPED
[INFO] MockServer Java Client ............................. SKIPPED
[INFO] MockServer Integration Test ........................ SKIPPED
[INFO] MockServer & Proxy Netty ........................... SKIPPED
[INFO] MockServer Maven Plugin ............................ SKIPPED
[INFO] MockServer Ruby Client ............................. SKIPPED
[INFO] MockServer Web Archive ............................. SKIPPED
[INFO] MockServer Proxy Web Archive ....................... SKIPPED
[INFO] MockServer Maven Plugin Integration Tests .......... SKIPPED
[INFO] MockServer JavaScript Client ....................... SKIPPED
[INFO] MockServer Example ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2017-07-03T04:00:32-07:00
[INFO] Final Memory: 10M/224M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "autoInstallBundle" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.6.1:clean (default-clean) on project mockserver: Failed to clean project: Failed to delete C:\Users\User\mars-workspace\angular\node_modules\karma\console.log -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by dfparker2002** [comment]
mvn 3.0.5, 3.2.3, 3.3.9, 3.5.0 also fail at the same step
[INFO]
[INFO] --- maven-assembly-plugin:2.5.1:single (default) @ mockserver-netty ---
[INFO] Reading assembly descriptor: src/main/assembly/jar-with-dependencies/jar-with-dependencies.xml
[INFO] Reading assembly descriptor: src/main/assembly/brew-tar/brew-tar.xml
[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver
java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipArchiveEntry

**Comment by khmarbaise** [comment]
I have tested the current master (5812910f549f8f84df7e617d56e8c931e1189b21) with Maven 3.5.0 with JDK 1.7 and JDK 1.8 without any problems...
@dfparker2002 please delete the local cache `$HOME/.m2/repository/org.codehaus/plexus` completely and retry the build.

**Comment by dfparker2002** [comment]
Nailed it! There were a backlog of plexus artifacts over several years, releases & vendors. Once cleared, the project compiled (tests=false) no issues.

Tests still halt the build but I can live with that

Thank you!
