### ISSUE TITLE
Synchronous server reset/clear

### ISSUE THREAD

**Issue by rnavarropiris** [jamesdbloom/mockserver#356]
Taking a look at the [MockServerServlet class](https://github.com/jamesdbloom/mockserver/blob/3060bbb872feb8e417c2e4b8e0f19ea5faa6890e/mockserver-war/src/main/java/org/mockserver/server/MockServerServlet.java) I noticed, that both for `clear` and `reset` request the HTTP status code 202 (Accepted) is returned.

As stated by the [HTTP specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html), "*The request has been accepted for processing, but the processing has not been completed... The 202 response is intentionally non-committal*".

This is very inconvenient for testing, as after the execution of such a request, if it is not clear if the expectations & request logs where deleted, posterior checks might (or might not, depending on when the requests are actually executed) fail.

The mock server should either:
- execute this requests in a blocking manner (return 200 once finished, preferred), or
- provide some endpoint to check the process status of the accepted requests

**Comment by jamesdbloom** [comment]
This is now fixed

**Comment by rnavarropiris** [comment]
nice, thanks! 👍
