### ISSUE TITLE
Add support for Two-Way TLS

### ISSUE THREAD

**Issue by carlomorelli** [jamesdbloom/mockserver#357]
I configured MockServer to receive `HttpRequest` expectation with a JSON string as body, which is intended to be a "relaxed" filter (the actual message is going to arrive with two more parameters in the JSON object, and of course the order of the serialized parameters can differ).
So I'm using syntax `HttpRequest req = request().withHeader(...).withBody(json(bodyString, MatchType.ONLY_MATCHING_FIELDS));` , where `String bodyString` is coming from a Jackson dump of an object. 

As you can see from the example below, the actual message will transport an additional property (the uuid), and with a random order of properties, so I assumed that `json(...)` in body would have done the trick. However the expectation is not satisfied.
I suspect that the reason is that the actual incoming message is the mismatching `"type" : "STRING"` versus the expected `"type" : "JSON"` ? Is this because of the "text/plain" content type? How can i tell MockServer to interpret the incoming body correctly as JSON string?

This is what is printed on the console (cutting away not relevant info):
```
[nioEventLoopGroup-3-3] INFO org.mockserver.matchers.HttpRequestMatcher - request:

	{
	  "method" : "POST",
	  "path" : "/myapi",
	  "headers" : [ ... ],
	  "keepAlive" : true,
	  "secure" : false,
	  "body" : {
	    "contentType" : "text/plain; charset=utf-8",
	    "type" : "STRING",
	    "string" : "{\"a\":\"YzdrOGp0djl0MWM0djB2b3U5NXJzY3BuMGU=\",\"c\":\"t9vii3sut37fuc71i0qe75r6si\",\"uuid\":\"0a0fd13b-069c-1062-0ff0-13326525851d\"}"
	  }
	}

 did not match expectation:

	{
	  "method" : "POST",
	  "path" : "/myapi",
	  "headers" : [ ...],
	  "body" : {
	    "type" : "JSON",
	    "json" : "{\"c\":\"t9vii3sut37fuc71i0qe75r6si\",\"a\":\"YzdrOGp0djl0MWM0djB2b3U5NXJzY3BuMGU=\"}"
	  }
	}

 because:

	method matches = true
	path matches = true
	query string parameters match = true
	body matches = false
	headers match = true
	cookies match = true
	keep-alive matches = true
	ssl matches = true
```

**Comment by jamesdbloom** [comment]
Can you please provide more detail because I don't appear to have any issue with the exact example you specified as shown by the following log:

```bash
2017-07-10 14:58:25,983 INFO o.m.m.HttpRequestMatcher request:

	{
	  "method" : "POST",
	  "path" : "/myapi",
	  "headers" : [ {
	    "name" : "Host",
	    "values" : [ "localhost:1080" ]
	  }, {
	    "name" : "Connection",
	    "values" : [ "keep-alive" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "123" ]
	  }, {
	    "name" : "Origin",
	    "values" : [ "chrome-extension://aejoelaoggembcahagimdiliamlcdmfm" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" ]
	  }, {
	    "name" : "Content-Type",
	    "values" : [ "application/json" ]
	  }, {
	    "name" : "Accept",
	    "values" : [ "*/*" ]
	  }, {
	    "name" : "Accept-Encoding",
	    "values" : [ "gzip, deflate, br" ]
	  }, {
	    "name" : "Accept-Language",
	    "values" : [ "en-US,en;q=0.8,fa;q=0.6" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false,
	  "body" : {
	    "contentType" : "text/plain; charset=utf-8",
	    "type" : "STRING",
	    "string" : "{\"a\":\"YzdrOGp0djl0MWM0djB2b3U5NXJzY3BuMGU=\",\"c\":\"t9vii3sut37fuc71i0qe75r6si\",\"uuid\":\"0a0fd13b-069c-1062-0ff0-13326525851d\"}"
	  }
	}

 matched expectation:

	{
	  "method" : "POST",
	  "path" : "/myapi",
	  "body" : {
	    "type" : "JSON",
	    "json" : "{\"c\":\"t9vii3sut37fuc71i0qe75r6si\",\"a\":\"YzdrOGp0djl0MWM0djB2b3U5NXJzY3BuMGU=\"}"
	  }
	}
```

**Comment by carlomorelli** [comment]
Hi! Thanks for helping!
I suppose then that there is some problem with my headers in the incoming request? I'll try to add as much as details as I can.

This is the detail on how I generate the expectation:

```
private static HttpRequest formatExpectation(String bodyString) {
    return HttpRequest.request()
        .withMethod("POST")
        .withPath("/myapi")
        .withHeader(new Header("Content-Type", "application/json; charset=utf-8"))
        //TODO commenting this line makes the expectation work
        .withBody(json(bodyString, MatchType.ONLY_MATCHING_FIELDS));
}
```

And this is the full tracing with MockServer logging, I'm also including the header details now:

```
[nioEventLoopGroup-3-3] INFO org.mockserver.matchers.HttpRequestMatcher - request:

	{
	  "method" : "POST",
	  "path" : "/myapi",
	  "headers" : [ {
	    "name" : "Content-Type",
	    "values" : [ "application/json; charset=utf-8" ]
	  }, {
	    "name" : "Host",
	    "values" : [ "localhost:1080" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "648" ]
	  }, {
	    "name" : "Expect",
	    "values" : [ "100-continue" ]
	  }, {
	    "name" : "Connection",
	    "values" : [ "Keep-Alive" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false,
	  "body" : {
	    "contentType" : "text/plain; charset=utf-8",
	    "type" : "STRING",
	    "string" : "{\"a\":\"YzdrOGp0djl0MWM0djB2b3U5NXJzY3BuMGU=\",\"c\":\"t9vii3sut37fuc71i0qe75r6si\",\"uuid\":\"0a0fd13b-069c-1062-0ff0-13326525851d\"}"
	  }
	}

 did not match expectation:

	{
	  "method" : "POST",
	  "path" : "/myapi",
	  "headers" : [ {
	    "name" : "Content-Type",
	    "values" : [ "application/json; charset=utf-8" ]
	  } ],
	 "body" : {
	    "type" : "JSON",
	    "json" : "{\"c\":\"t9vii3sut37fuc71i0qe75r6si\",\"a\":\"YzdrOGp0djl0MWM0djB2b3U5NXJzY3BuMGU=\"}"
	  }
	}

 because:

	method matches = true
	path matches = true
	query string parameters match = true
	body matches = false
	headers match = true
	cookies match = true
	keep-alive matches = true
	ssl matches = true

[nioEventLoopGroup-3-3] INFO org.mockserver.mockserver.MockServerHandler - returning response:

	{
	  "statusCode" : 404
	}
```
What other details could be useful to add?

**Comment by carlomorelli** [comment]
Hi @jamesdbloom thanks for helping. Well this is embarassing :-( but I just found out that the problem was an actual mismatch in an additional parameter in the body (the mismatch was an uppercase letter instead of a lowercase). Totally my fault, not MockServer's. Thanks anyway for the support.

I have another question for you, sorry if this is not the relevant place.
Does MS support client side certificates in SSL? I know it supports traditional server-side SSL certificate handshaking when the requests are sent to MS with "https://" addresses. I would also need to validate a certificate on the client side, ibut I did not find a way to do it (yet).

**Comment by jamesdbloom** [comment]
Can you please explain more about the use case to support client side certificates.  Why is required?

**Comment by carlomorelli** [comment]
I found the use of "two-way SSL" (that means, both server-side and client-side certificate exchange) twice up until now. In my latest observation, it is used for distributed applications targeting content security. The server does not trust a client without valid certificate.

I use MockServer a lot when testing distributed applications like this, but I hit the wall of using it in mocking a 2-way SSL connection.

**Comment by jamesdbloom** [comment]
I agree it could be useful to support two-way TLS.

I'm happy to add this, although I need to first improve the documentation so it may take a month or so before it is released.

**Comment by carlomorelli** [comment]
Hi! Just pinging to ask if by any chance this feature is being worked?

**Comment by chomatdam** [comment]
Hey @jamesdbloom - I see this moved to milestone `5.5.2`. We are at `5.6.1`, I would be very interested in this feature, is it implemented or can I help?

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/ZecFz4Dx/19-authenticate-clients-with-mutual-tls

**Comment by jamesdbloom** [comment]
This is now implemented, once I have updated the documentation in the next week I will release a new version with this feature completed.
