### ISSUE TITLE
Support WebSockets mocking

### ISSUE THREAD

**Issue by VictorPascualV** [jamesdbloom/mockserver#360]
What do you think about being able to also mock WebSockets traffic?

It should be possible to instruct the MockServer to send a message (via the API).

Not sure how complex would be to do that, I offer myself to help on the implementation.

WDYT?

**Comment by jamesdbloom** [comment]
Sounds like a good idea.  

I have added already support for dynamic method callbacks which use WebSockets under the hood.  These allow you to provide a Java object or JS function, in the client, that is called back from MockServer when an expectation is matched.

I see the main issue with Web Sockets is that there are several different standards and this would need to be presented / handled is a simple way to make it practical to use.

I'm definitely open to suggestions.  Perhaps if you took a look at how you think you would implement it and then we could talk more about where it would fit in in this bug?  Does that work for you?

**Comment by andrcuns** [comment]
Our project could benefit from this enhancement greatly as well. Would be glad to help in any way possible!

**Comment by jamesdbloom** [comment]
Currently I’m working on a UI for MockServer so it is possible to see what expectations are setup and requests that are passed to MockServer. Once I have finished and released that I will look into adding support for WebSockets. That would realistically be around the 1-2 month timeline, possibly sooner.

**Comment by deepinthesystem** [comment]
Any pointers to the documentation for using web sockets?

**Comment by jamesdbloom** [comment]
This is still not yet implemented

**Comment by vvargas90** [comment]
Any update on this one @jamesdbloom? I would really love this feature 😄

**Comment by rafavisa** [comment]
@jamesdbloom any update on this? 🙏

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/IDdtHpxt/20-support-websockets-mocking

**Comment by colin-young** [comment]
If one wanted to look into adding WebSocket mocking on their own, where would be the best place to start looking in the code?
