### ISSUE TITLE
Outdated dependency that brakes SAXParserFactory (if it used in the project)

### ISSUE THREAD

**Issue by pshvets** [jamesdbloom/mockserver#362]
https://github.com/jamesdbloom/mockserver/blob/0a3474d3609a3e0a7f35f804b422281d31794796/pom.xml#L288

Industry standart is https://mvnrepository.com/artifact/xerces/xercesImpl/2.11.0

my workaround is excluding it from pom.xml 
```
 <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>3.10.8</version>
            <exclusions>
                <exclusion>
                    <artifactId>xercesImpl</artifactId>
                    <groupId>xerces</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by jamesdbloom** [comment]
The project no longer depends on Xerces.  This was refactored because with Java 9 Xerces seems to cause a number of different issues.  I'm closing this ticket because it is already fixed.
