### ISSUE TITLE
Mock response to web browser

### ISSUE THREAD

**Issue by jun1983** [jamesdbloom/mockserver#365]
Hi author, many thanks for providing this amazing tool.

I am testing with selenium webdriver and want to Mock http(s) response to specific requests when submit a form. Is that possible to make Mock Server work as a browser proxy and bypass all irrespective requests to the real destination? In official docs and your previous response to other threads, It only talks about how to do so on a MAC OS. I need to run tests locally on windows laptop and also run it on CI with linux build agents. 

Appreciate If you can provide some code examples.

**Comment by jamesdbloom** [comment]
Yes it is absolutely possible to do this.

I would suggest you use desired capabilities in selenium to configure a proxy for the browser, see: 

- https://sites.google.com/a/chromium.org/chromedriver/capabilities,
- https://github.com/mozilla/geckodriver/issues/97 or
- https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities.

This will ensure all calls from the browser go via the proxy.  The MockServer can then be used to proxy all the calls by using forward actions, see: 

- http://mock-server.com/mock_server/creating_expectations.html#mock_forward, or
- https://github.com/jamesdbloom/mockserver/blob/94e6446c91b83b7d8d7998d14c2ff9c48afc2981/mockserver-client-java/src/test/java/org/mockserver/client/server/MockServerClientIntegrationTest.java#L125

The links above should provide you with the code examples and details you need.  I am going to close this ticket.

**Comment by Galileo1** [comment]
@jun1983 I am trying something similar that you mentioned in this issue. Could you please care to share your learning or solution for this problem. Thanks
