### ISSUE TITLE
How to enable HTTPS in excpectation

### ISSUE THREAD

**Issue by aterhzaz** [jamesdbloom/mockserver#366]
Hello Everybody,

I want to call my mock with HTTPS, i don't know howa to do it on mock server.
Thank you for your help.

Regards.

**Comment by jamesdbloom** [comment]
There is nothing to do, you just need to call MockServer on using HTTPS.

MockServer supports both HTTP and HTTPS from the same port.

It is also possible to ensure an expectation only matches on an incoming request that is done over HTTPS or HTTP by setting the `secure` property to `true` or `false` for the `HttpRequest` (i.e. `request`) field of an expectation.
