### ISSUE TITLE
Path decoding changed between 3.10 and 3.11

### ISSUE THREAD

**Issue by checat** [jamesdbloom/mockserver#374]
Hello!
We used mockserver-netty 3.10.4 previously and there is a test that passed with expectation:
```
mockServer.when(
    request().withPath("/api/testByteEncodingInPath/dWM%2FdWM+ZA==")
).respond(response().withStatusCode(200));
```
Here you see, %2F is an encoded / in the path segment.
I've tried to use 3.11 and this expectation fails.
I've looked in a debugger and I see that the path string in HttpRequestMatcher contains %2F, but the request passed to the matcher contains %2F decoded to /
Is it something that was specifically changed between 3.10.4 and 3.11 or is it an unintentional change and is a bug?

**Comment by jamesdbloom** [comment]
Nothing has changed in the MockServer code specifically but perhaps the Netty QueryStringDecoder behaves differently, anyway I will fix this issue shortly.

**Comment by jamesdbloom** [comment]
This issue is now fixed and will be available in the next released version.

**Comment by checat** [comment]
Thanks for the update! But I think decoded and encoded path segments should not match. In my case the test was specifically written to verify that slash was properly encoded in the variable path segment. Looking to the added tests in your commit I see that now there is no difference between encoded and decoded form, I think now I just can't verify my case.
While for query string elements slash does not have a special meaning and encoded and decoded form must be interpreted as equal, in the path slash is a special characters and so encoded should not match the decoded slash and vice versa.

**Comment by jamesdbloom** [comment]
That is a fair point so I have improved the fix to cover your valid use case.  Take a look.
