### ISSUE TITLE
Documentation link missing

### ISSUE THREAD

**Issue by partizanos** [jamesdbloom/mockserver#375]
Hello I am following the getting started section and i couldnt find the
"2. Run Test Scenario" Section it seems to be missing. 
http://www.mock-server.com/mock_server/getting_started.html

Maybe I am looking in wrong place?
Thank you in advance

**Comment by jamesdbloom** [comment]
The `Run Test Scenario` item in the list is when someone using Mock Server would run they're own test scenarios.  The list shown on that page is a list of steps not a list of links.  It just happens that steps 0, 1 and 3 also have corresponding pages.

Does that make sense?

This isn't a bug so closing it now.
