### ISSUE TITLE
SSL certificate 

### ISSUE THREAD

**Issue by fbg1907** [jamesdbloom/mockserver#381]
I'm new to SSL certificates, so my question may be odd.

I've downloaded  MockServer root CA certificate from the website and installed the .pem file (with the help of "update-ca-certificates" command on the Linux machine). Installed MockServer and it runs perfectly. 

I have an REST client application which is able to make HTTPS calls to the MockServer (on the same machine) via "localhost". That is, I'm able to run/test my application https://localhost/api/blablabla with MockServer .

Whenver I install MockServer on another machine (and install MockServer root CA certificate), my application fails to access MockServer because of SSL certification. That is, I'm unable to run/test my application https://192.168.1.3/api/blablabla with MockServer . MY app's running on 192.168.1.2...

Were you able to have MockServer & REST client on different machines?

**Comment by fbg1907** [comment]
Hi all,
I've accomplished the setup with the help of mockserver.properties file.
"mockserver.sslSubjectAlternativeNameIps" saved my life :)

 jamesdbloom , you may close this issue. Thanks.

**Comment by jamesdbloom** [comment]
Ok good, thanks
