### ISSUE TITLE
Ability to mock http reason phrase

### ISSUE THREAD

**Issue by arudge** [jamesdbloom/mockserver#393]
I had a scenario where I needed to mock the http response reason phrase, but I do not see support for this. 

https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html

Is this something you would consider adding? 
I can attach a PR to this issue if you are open to the idea.

**Comment by jamesdbloom** [comment]
I would certainly consider adding this, and I agree there is currently no support for this.

I'm very happy if you raise a PR.  If the build fails in the PR please use `scripts\local_docker_build.sh` to run the build locally to see what the failure is.  Currently [BuildKite](https://buildkite.com/mockserver/mockserver) doesn't support the ability for unauthenticated users to see a  build log.

**Comment by jamesdbloom** [comment]
The current focus starting tomorrow the next week or two.  Once that is completed I will look to add this support unless you want to submit a PR.

**Comment by arudge** [comment]
I was starting to dig into, but if you have bandwidth I'll let you run with it.
If that changes, let me know and I can issue a PR.

**Comment by jamesdbloom** [comment]
Support for reasonPhrase has now been added.  This will be available in the next release 5.2.4.
