### ISSUE TITLE
Create a Python Client

### ISSUE THREAD

**Issue by armona** [jamesdbloom/mockserver#394]
Create a python client for the mock-server.

**Comment by jamesdbloom** [comment]
I'm happy to do this once https://github.com/swagger-api/swagger-codegen release 3.0.0 has been completed.  Currently there is no listed release date.

**Comment by lindycoder** [comment]
Hi, here's a new one that i made https://github.com/internap/python-mockserver-client

The usage is a little different than other clients, let me know what you think.  It's an early version that suits my needs so far, but i'd love to see it grow :)

**Comment by lindycoder** [comment]
Oh, that's interesting...  and will be a bad surprise to whoever uses this package if we just swap them :-/

I will move mine then, I'll add a warning to my lib, if we could leave it a week or 2 that'd be great.

About your client, code generation is all fun and game but your test suite is completely empty.

Also it could be nice to provide a working example of a complete request with response because it doesn't seem to work like either the javascript or the java client.

I made my client different because i use it in tests and a mock cannot take more than 2-3 lines or else tests become unreadable so i hope i can use your client with a simple minimal information or else i'll have to be build a readable client around it like i did with the javascript version (privately).

**Comment by jamesdbloom** [comment]
I agree it would a nasty shock but I'll realise a new version with a major version change so only those people who don't specify the version would get the new code generated version.

I agree also that I'll need to add tests before I release the pip package and add code examples.  Once I've written some tests for the python and ruby version I'll add code examples to the web site.

**Comment by lindycoder** [comment]
Did you delete my last comment?  (I don't know how to contact you otherwise)

**Comment by lindycoder** [comment]
Do you mind if i move my client to `mockserver-friendly-client` or that would be pejorative towards yours?

**Comment by jamesdbloom** [comment]
I can't see my last comment either.  I also notice that some of the way the code generator has generated the API is not very nice.  I'll play with and see if I can fix that before I release this client library, including adding tests that may take a little while.

**Comment by jamesdbloom** [comment]
I think that shouldn't be a problem, although hopefully I'll make the client friendly enough

**Comment by lindycoder** [comment]
Started!
https://github.com/internap/python-mockserver-client/pull/18

**Comment by 53066191** [comment]
@jamesbloomnektan @lindycoder   hi, my response is dependance with request ,but i dont know  how to use callback with python client ,  could you give me a example, thanks

**Comment by lindycoder** [comment]
Hi @53066191   :P . 

Documentation sais a client side callback can be configured via websocket.  http://mock-server.com/mock_server/creating_expectations.html#callback

Both or our clients don't seem to have implemented it right now, you could try to look at how the java client does.

**Comment by eracle** [comment]
Hello guys! 
What's the actual status of this?

**Comment by lindycoder** [comment]
Right, i had forgotten about this... will move asap
@jamesdbloom can you give me your pypi username i will give you the ownership of https://pypi.org/project/mockserver-client/

**Comment by lindycoder** [comment]
Officially moved to my new spot https://pypi.org/project/mockserver-friendly-client/ .  ready to transfer ownership

**Comment by jamesdbloom** [comment]
Sorry for the delayed response my pypi username is jamesdbloom

**Comment by lindycoder** [comment]
There you go, you are now an owner of this package, i can't seem to find out how to remove my organization from the owners though... :-/

**Comment by jamesdbloom** [comment]
Thanks

**Comment by jeff9finger** [comment]
You might consider using openapi-code-generator instead of swagger-codegen as this project has much more active feature development

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/PvQ3kbDg/22-create-a-python-client
