### ISSUE TITLE
Logs are not shown anymore since 5.0.1

### ISSUE THREAD

**Issue by timtkachenko** [jamesdbloom/mockserver#396]
After 5.0.1 change logs do not appear. running in docker container.
```docker run -i -t --name mockserver -p 443:443  jamesdbloom/mockserver:mockserver-5.0.0```
the output for 5.0.0
```
java  -Dfile.encoding=UTF-8 -Dmockserver.logLevel=INFO -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar -serverPort 443

2017-12-14 09:16:18,925 INFO o.m.m.MockServer MockServer started on port: 443
2017-12-14 09:17:25,186 INFO o.m.m.HttpStateHandler resetting all expectations and request logs
```
output for versions greater or equal to 5.0.1 (tested 5.1.1, 5.2.2)
```docker run -i -t --name mockserver -p 443:443  jamesdbloom/mockserver:mockserver-5.0.1```
```
java  -Dfile.encoding=UTF-8 -Dmockserver.logLevel=INFO -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar -serverPort 443
```
but looks like mockserver works as expected though

**Comment by jamesdbloom** [comment]
This is now fixed.

I will release a new version tomorrow or you can use the `5.2.3-SNAPSHOT` version.

In addition in the mean time you could use the `/retrieve?type=logs` endpoint as described at https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.2.2#/control/put_retrieve

The `/retrieve?type=logs` allow you to retrieve logs on a per request basis.  Using a request matcher you can retrieve all logs that are relevant to that request or if you don't provide any request matcher all logs will be returned.

I am currently working on update the documentation to include details of this and loads of other features that are not currently documented well enough.
