### ISSUE TITLE
CORS issue when doing XMLHttpRequest having withCredentials

### ISSUE THREAD

**Issue by martinhristov** [jamesdbloom/mockserver#401]
"Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:5555' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

A possible solution to this issue is to dynamically set the value of Access-Control-Allow-Origin in the response headers to the one of Origin request header.

**Comment by jamesdbloom** [comment]
Good point, I can fix this.

**Comment by jamesdbloom** [comment]
On further research I'm not sure what you are saying is correct, because the withCredentials attribute is a client side attribute and is not controlled on the server side.  Can you please provide a link the CORS specification describing this behaviour as I can't find any mention of it in the CORS RFC.  https://www.w3.org/TR/cors/#access-control-allow-credentials-response-header

**Comment by jamesdbloom** [comment]
I have found details of how this should work and have implemented the support for `access-control-allow-credentials` and `null` `origin` headers.

**Comment by cristopher0820** [comment]
Hi bro, i couldnt solve this problem. I have a client code and i cant take the cookies (credentials) from a external server by using web services. 
Im using javascript.
Can you help me pls.

Best regards.

**Comment by jamesdbloom** [comment]
Have you tried using the CORS configuration settings in MockServer see: http://mock-server.com/mock_server/configuration_properties.html#button_configuration_enable_cors_for_all_responses

**Comment by eweap** [comment]
@jamesdbloom Hi, I think this issue should be re-opened, there is still no configuration option to tell mock-server to stop using `access-control-allow-origin: *` 

Something like `mockserver.corsAllowOrigin` would be great !

For the moment I still don't found any workaround to this error:
```
Access to XMLHttpRequest at 'https://api.mysite.home:1080/token' from origin 'https://app.mysite.home:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

Best regards
