### ISSUE TITLE
Incorrect X-CORS header message

### ISSUE THREAD

**Issue by martinhristov** [jamesdbloom/mockserver#402]
Currently at https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/cors/CORSHeaders.java#L29 it says:
```
response.withHeader("X-CORS", "MockServer CORS support enabled by default, to disable ConfigurationProperties.enableCORSForAPI(false) or -Dmockserver.disableCORS=false");
```
I believe you meant `-Dmockserver.enableCORS=false` at the end, because I can't find any references to disableCORS in the code and generally disableCORS=false doesn't make sense for disabling CORS.

**Comment by jamesdbloom** [comment]
Your right I'll fix this

**Comment by jamesdbloom** [comment]
fixed, so closing issue
