### ISSUE TITLE
Limited Throughput when Response Delay is not Zero

### ISSUE THREAD

**Issue by mauaht** [jamesdbloom/mockserver#403]
We are using the mock-server to stub downstream web service dependencies in our load tests. Some of those downstream services have response times in excess of 500ms and we need to run the tests to 100+ TPS. When I tested the mock server in isolation, using a mock with a 500ms delay, I observed response times growing as I increased load from 4 to 20 TPS (transactions per second) using JMeter. The throughput capped at about  16 TPS. I also noticed a higher than expected spread in response times (high 95th-percentile relative to average) at low load (4 TPS). We are using the Netty implementation embedded in a Java application.  

# Cause:
I found the cause to be the way in which response delays are implemented, namely by calling Thread.sleep() in the applyDelay() method of the org.mockserver.model.Delay class. This is not compatible with Netty as follows:

- The default Netty worker thread pool consists of 2 x num-proccesssor-cores threads, eg 8 threads on 4 core machine.
- Each thread is allocated to one, and only one, Netty event loop.
- HTTP connections are distributed across the event loops (threads), for example 800 HTTP connections => 100 connections for each of the 8 event loops on a 4 core machine.
- Each event loop handles the processing of requests for all of the connections associated with it.
- Calling Delay.applyDelay(), ie. Thread.sleep(), in the event loop blocks the event loop from handling requests for other connections which share that event loop.  

The Netty guidelines recommend that the event loop should not block. (It is also noted that the HttpForward handler blocks while waiting for the response from the target server, but that is another issue)   

# Current Workaround
We are currently using the following solution whereby we have moved the delay implementation to the 
org.mockserver.responsewriter.NettyResponseWriter class by adding the following method to call writeAndCloseSocket() indirectly,  rather than calling it directly from other methods in that class:

```
    private void scheduleResponse(final ChannelHandlerContext ctx, 
                                  final HttpRequest request, 
                                  final HttpResponse response) {
        Delay delay = response.getDelay();
        if (delay == null || delay.getValue() <= 0) {
          // No delay so write response immediately  
          writeAndCloseSocket(ctx, request, response);
        } else {
          // Schedule writing of response after delay  
          ctx.executor().schedule(
            new Runnable() {
              @Override
              public void run() {
                writeAndCloseSocket(ctx, request, response);
              }
            }, 
            delay.getValue(), 
            delay.getTimeUnit());
        }
    }
```

This approach schedules the response to be written by the event loop after the delay without blocking the event loop itself.
This solution achieved 250 TPS for 500ms delay and 1000 HTTP connections spread across 8 event loops 
(worker threads), compared with 16 TPS for the blocking call to Delay.applyDelay(). In addition, the spread in the response time is significantly improved (min: 502, ave: 507, median: 506, 95-percentile: 518). The throughput for this modified approach was CPU limited as the machine reached 85% utilisation at 250 TPS. JMeter was running on the same machine.

# Additional Issues to Resolve/Consider
I have not attempted a pull request because a full solution requires consideration of other use cases that I am not familiar with. So to start the conversation, here are some further thoughts that come to mind:  

- The scheduled task approach works for the NettyResponseWriter but is Netty specific. Similar solutions for other cases also need to be considered:
    - Web socket: ?
    - WAR (servlet): Thread.sleep() may be OK if a dedicated-thread-per-request model is assumed.
    - Other?    
- Backwards compatibility
    - The simplest solution is is to remove the call Thread.sleep() in Delay.applyDelay() and defer the delay implementation to the ResponseWriter implementations as described above for the Netty case. This should be transparent in most cases but has the potential to break others. 
    - Backwards compatibility can be maintained by introducing a 'delayOnWrite' flag into the Delay class. If delayOnWrite=true then Delay.applyDelay() will be a noop and ResponseWriter delay is active. If delayOnWrite=false then Delay.applyDelay() will operate as now and ResponseWriter delay will be noop.  The Expectation.withDelay() method will need to be modified to allow setting the 'delayOnWrite' flag.- -
- Consistency in passing delay values to responses
    - The ResponseWriter extracts the delay from the HttpResponse instance
    - All Expectation Action handlers (HttpResponse, HttpResponseTemplate, HttpForward, HttpForwardTemplate, HttpError, HttpClassCallback, HttpObjectCallback) must ensure a delay is provided where needed.

**Comment by jamesdbloom** [comment]
Yes this is a very valid point, I completely agree with your points, i’m Just disappointed I never realised this in the first place :-(. I am just working on improving build time and stability by separating out the maven plugin logic into a separate project (its integration builds are fairly slow) once that is completed I will look into this. 

I suspect (of the top of my head) I’ll use a single addition ExecutorService from the JDK.  In addition to the delay tasks a MockServer UI being build needs tasks scheduled asynchronously for websocket updates.  The ExecutorService would use an additional fixed set of threads but would be generic across both Netty based and JEE / WAR based deployments as it would only rely on the JDK and could be used for any required aschronous task.

**Comment by mauaht** [comment]
Thanks James, reach out if you want to discuss further or would like help testing this.

**Comment by jamesdbloom** [comment]
I have implemented these improvements to ensure that the event loop is never blocked either for delays or HttpForward / proxied requests.

I'm going to close this issue, the changes will be release soon once I have completed a few other bugs.  However you can use it immediately by using the latest SNAPSHOT version (see http://mock-server.com/where/maven_central.html#sonatype_snapshot)

**Comment by mauaht** [comment]
Hi @jamesdbloom, just looking over the code and the Class callback option is not being scheduled like the others, extract from org.mockserver.mock.action.ActionHandler:

```
                case CLASS_CALLBACK: {
                    httpStateHandler.log(new ExpectationMatchLogEntry(request, expectation));
                    HttpResponse response = httpClassCallbackActionHandler.handle((HttpClassCallback) action, request);
                    responseWriter.writeResponse(request, response, false);
                    logFormatter.infoLog(request, "returning response:{}" + NEW_LINE + " for request:{}" + NEW_LINE + " for class callback action:{}", response, request, action);
                    break;
                }
```
This is the main one we use for performance testing because we need our mocks to generate a lot of random, but related, field values.

**Comment by jamesdbloom** [comment]
Ok fair point I can cover that one as well.
