### ISSUE TITLE
Brew only latest version of mockserver is available

### ISSUE THREAD

**Issue by paulbrittain** [jamesdbloom/mockserver#407]
It would be very nice to have previous versions of mockserver available to install via Brew. I have ran into problems with the newest version 5.1.1 and have no way to easily install older versions.

Downloading an older version of mockserver locally and installing the archive file has so far failed, the fix for this would be to keep older versions available to download to avoid upgrade issues.

**Comment by jamesdbloom** [comment]
Can you please give some more information on `Downloading an older version of mockserver locally and installing the archive file has so far failed`.

I'm not adverse to supporting older versions via homebrew, although I'm not sure of a good standard way to do this.  None of the homebrew installations I use support multiple versions.

**Comment by paulbrittain** [comment]
Hi James, I haven't been able to install an older version of mockserver from a local archive file yet. Brew has failed to find the archive file in the homebrew cache, I've also attempted to manually install mockserver into /usr/local/Cellar/mockserver/<version_number> without success. Have you successfully done this recently? I will keep trying..

`brew search postgresql@` should yield 4 different version of postgres which would be ideal for mockserver. I don't know whether this would be a large task but I assume it would be a matter of altering the current formula
```
==> Searching local taps...
postgresql@10.1          postgresql@9.4           postgresql@9.5           postgresql@9.6
==> Searching taps on GitHub...
caskroom/cask/navicat-for-postgresql               caskroom/cask/photo-supreme-postgresql
==> Searching blacklisted, migrated and deleted formulae...
```

**Comment by paulbrittain** [comment]
Has something happened between v5.1.1 and v3.10.8 with how we're to define our expectations?

**Comment by jamesdbloom** [comment]
There has been some minor breaking changes, thus the reason why it is a major version change.  I think the main change that is likely to affect you is that support for the `value` field in a body was removed.  This was removed because now expectation created is fully validated using swagger and detailed error messages are returned.  

If you are having difficulties when creating an expectation please look at the body of the 400 response because this will inform you exactly which fields MockServer has validated as incorrect.

**Comment by jamesdbloom** [comment]
Support for multiple version has now been released in homebrew, as per PR: https://github.com/Homebrew/homebrew-core/pull/34252
