### ISSUE TITLE
Prevent mockserver from stopping after tests

### ISSUE THREAD

**Issue by sfeinstein** [jamesdbloom/mockserver#409]
Couldn't find a way to accomplish this in documentation.  We're starting a mockserver via docker prior to integration tests being executed (via maven).  When the tests finish, the mockserver container is stopped but this is not the desired behavior.  We're not using a MockServerRule.  Is there any way to prevent the mockserver / container from stopping after tests complete?

**Comment by jamesdbloom** [comment]
There is currently no MockServer logic that starts or stops a docker container.

However if one of your tests or cleanup logic (i.e. an @AfterSuite method) is calling stop on the MockServer this will stop the JVM process running MockServer which will then cause the docker container to stop.

The only automated stopping logic (beyond explicitly calling `stop`) exists in the maven plugin.  However the maven plugin doesn't launch a docker container so I suspect you can't be using that.

Can you give some more details about your project and environment.

**Comment by sfeinstein** [comment]
Thanks @jamesdbloom , and for this excellent project.  I see what's going on here.  I'm using a Spring Boot project and in my integration test configuration am making a MockServerClient bean.  When the bean is destroyed, the close() method on MockServerClient is invoked and it stops the server (and hence container).  Thought I was being clever with the bean since many tests need to make use of the client but I'll design that a different way.  Feel free to close.

**Comment by sfeinstein** [comment]
I know this is closed, but just for the sake of pointing it out...isn't it odd that close() on a client invokes stop() on its server?  Not hard to work around, just seems strange to me.

**Comment by jeffjensen** [comment]
How do we work around this behavior so a Spring managed MockServerClient doesn't stop MockServer?

**Comment by jamesdbloom** [comment]
There is no reason to call stop on the client unless you want to stop the server.

**Comment by jeffjensen** [comment]
Agreed. However, Spring automatically does this at shutdown.  This is a client shutdown and the MockServer instance stops too (although the process still runs).

How do we work around this behavior so a Spring managed MockServerClient doesn't stop MockServer?

**Comment by jamesdbloom** [comment]
If the process is still running have you checked that your using the latest version?

Not. sure how you can prevent Spring from calling the stop method.  It looks like "A Spring-managed bean may also implement Java's AutoCloseable interface for the same purpose. An alternative to implementing an interface is specifying a custom destroy method, for example in an XML bean definition. For a list of all bean lifecycle methods, see the BeanFactory javadocs." from https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/DisposableBean.html

A none idea solution would be to sub class the MockServerClient and override the stop method.  Although I could implement a better solution.  Do you have any ideas?

**Comment by jeffjensen** [comment]
Thanks for the suggestions.  Just found and verified a workaround.  Tell Spring what "destroy method" to use, and for `MockServerClient`, use empty string for "none":
`@Bean(destroyMethod = "")`

Docs:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html#destroyMethod--

Thank you for your very fast responses.  This info will help the next users that encounter this problem.

**Comment by gpsmit** [comment]
Thanks Jeff, this solved it for me as well.

**Comment by SButterfly** [comment]
Update on this old thread.

We run mockserver in our k8s testing environment for integration tests. Once the integration tests are finished Spring calls `close()` on MockServerClient, which **stops the testing cluster in k8s**. And we had to wait backoff-time until k8s restarts the container.

Actually, it's quite **counterintuitive** that _client_ will stop a _server_ by calling `Closeable.close()`. I would expect that `close()` will only free opened connections to the server, but not shutdown the server itself.

**Comment by tmueller64** [comment]
Another reason to close the client without stopping the server is to get the threads in the MockServerClient.eventLoopGroup shutdown between tests. 

We have a test suite that consists of several hundred test classes that run against a docker-compose environment that includes Mockserver. Everytime a test sends a request to Mockserver using the MockServerClient, a new netty thread is created in the eventLoopGroup. As the tests run, the number of threads keeps growing; there are several thousand at the end of the suite. After each test class, we call reset on Mockserver. I'd like to also start with either a new MockServerClient or a reset client so that the threads are cleaned up after each test class. It would be great if MockServerClient.reset would call eventLoopGroup.shutdown and then reinitialize the threads on the client side. 

MockServerClient.eventLoopGroup is private, so I cannot extend MockServerClient to redefine stop to shutdown the eventLoopGroup without stopping MockServer or to redefine reset to have this behavior.
