### ISSUE TITLE
MockServerClient method/closure callback not works as given in doc

### ISSUE THREAD

**Issue by govindndr** [jamesdbloom/mockserver#412]
I have used example given under the method/closure callback java 7 section in http://mock-server.com/mock_server/getting_started.html#button_method_or_closure_callback. I face type mismatch error for callback method which accepts HttpCallback

new MockServerClient("localhost", 1080)
.when(
request()
.withPath("/some/path")
)
.callback(
new ExpectationCallback() {
@override
public HttpResponse handle(HttpRequest request) {
if (request.getMethod().getValue().equals("POST")) {
return response()
.withStatusCode(ACCEPTED_202.code())
.withHeaders(
header("x-object-callback", "test_object_callback_header")
)
.withBody("an_object_callback_response");
} else {
return notFoundResponse();
}
}
}
);

Not sure why example shows object creation for  interface ExpectationCallback class.

I get
2 errors:
- object instance has properties which are not allowed by the schema: ["httpCallback"]
- oneOf of the following must be specified "httpResponse" "httpResponseTemplate" "httpForward" "httpForwardTemplate" "httpClassCallback" "httpError" "httpObjectCallback"

for below callback . The same works fine for ClientandServer callback.
new MockServerClient("localhost", 1080).when(request().withQueryStringParameter("MeasureName",".*"))
.callback(new HttpCallback().withCallbackClass(metricCallBack.class.getName()));

**Comment by jamesdbloom** [comment]
Can you please specify which version of MockServer you are using?  As per your other issue #411, it seems the version of MockServer you are using is over 2 years out of date.  The current documentation is valid of the current version of MockServer.  The current documentation specifies version 5.3.0, please update your version of MockServer and your problem will be resolved.
