### ISSUE TITLE
Enable CORS for docker

### ISSUE THREAD

**Issue by jameslive** [jamesdbloom/mockserver#422]
Everything is working for me, but how do I enable CORS for mockserver docker?   I don't seem to have a clean way to do this... can this be something that I can do at the time I up the docker container?  I have tried running some commands that I read from docs, but nothing is working yet.

thanks

**Comment by jamesdbloom** [comment]
Please use the following command:

```bash
docker run -p 1080:1080 jamesdbloom/mockserver /opt/mockserver/run_mockserver.sh -logLevel INFO -serverPort 1080 -genericJVMOptions "-Dmockserver.enableCORSForAllResponses=true"
```
