### ISSUE TITLE
Allow extra headers with default cors headers

### ISSUE THREAD

**Issue by skimi** [jamesdbloom/mockserver#429]
Currently, the default CORS `Access-Control-Allow-Headers` are `Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary`.

It's very common to also require an `Authorization` header + any project might use some other headers.

We need to be able to add extra headers or simply override the cors headers.

I've tried creating a global `OPTIONS` expectation that overrides the default with mine but that did not work ;(
```
{
  httpRequest: {
    method: 'OPTIONS',
  },
  httpResponse: {
    headers: [
      { name: 'Access-Control-Allow-Origin', values: ['*'] },
      { name: 'Access-Control-Allow-Methods', values: ['DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH'] },
      { name: 'Access-Control-Allow-Headers', values: ['Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization'] },
      { name: 'Access-Control-Expose-Headers', values: ['Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization'] },
      { name: 'Access-Control-Max-Age', values: ['300'] },
      { name: 'connection', values: ['close'] },
    ]
  },
}
```

**Comment by jamesdbloom** [comment]
I have now fixed it so it is easy to override the CORS response by creating an expectation.  The fix will be available in the next release or in the current SNAPSHOT version.

In the meantime you should still be able to override the CORS request with the above expectation if you specify the following System Property `-Dmockserver.enableCORSForAPI=false` which will disable the default CORS support for the MockServer API.
