### ISSUE TITLE
CORS: allowed-headers missing authorization header

### ISSUE THREAD

**Issue by on-delete** [jamesdbloom/mockserver#434]
If we do a request, where the request-header "authorization" is set, we get an error with following message:

> Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

That is due to the fact, that the authorization header is not returned in the standard CORS response from the mockserver:

> Access-Control-Allow-Headers: "Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary"

Are these headers configurable and if not, can they be added?

**Comment by jamesdbloom** [comment]
I have added the `Authorization` header to the list.  This is available in the SNAPSHOT version or alternatively I will be making a new release as soon as I have completed the MVP for a new UI that will show active expectations, recorded request and logs dynamically.
