### ISSUE TITLE
Adding httpForward expectation with JavaScript API fails

### ISSUE THREAD

**Issue by edilaver** [jamesdbloom/mockserver#437]
I'm trying to add a simple httpForward expectation using JavaScript API (v. 5.3.0) but it fails with an error message : _oneOf of the following must be specified "httpResponseTemplate" "httpForwardTemplate" "httpClassCallback" "httpError" "httpObjectCallback"_

The reason is _mockServerClient.mockAnyResponse()_ adds all expectations pre-defined default response headers. Although i want to add a forward expectation with: 

```
    {
        "httpRequest": {
          "path": "/some/path"
        },
        "httpForward": {
          "host": "mock-server.com",
          "port": 8080,
          "scheme": "HTTP"
        }
      }
```

the generated request with JavaScript API is:

```
[{
		"httpRequest" : {
			"path" : "/some/path"
		},
		"httpForward" : {
			"host" : "mock-server.com",
			"port" : 8080,
			"scheme" : "HTTP"
		},
		"httpResponse" : {
			"headers" : [{
					"name" : "Content-Type",
					"values" : ["application/json; charset=utf-8"]
				}, {
					"name" : "Cache-Control",
					"values" : ["no-cache, no-store"]
				}
			]
		}
	}
]
```

which is, i think, not allowed.

**Comment by jamesdbloom** [comment]
yes that looks like a bug, it should be fairly easy to fix by check for the presence of `httpResponse` in the expectation and only adding those headers if it exists.

**Comment by mlessd** [comment]
In mockServerClient.js, we have the following comment for the setDefaultHeaders function:

- default headers that are used to specify the response headers in mockSimpleResponse(...)
         *   (note: if you use mockAnyResponse(...) the default headers are not used)

The mockAnyResponse does add the default headers:

``var mockAnyResponse = function (expectation) {
            return makeRequest(host, port, "/expectation", addDefaultExpectationHeaders(expectation));
        };
``

Should we simply remove the call to addDefaultExpectationHeaders here?

**Comment by andygaga2018** [comment]
I modified the mockServerClient.js as follow, when i execute "node http-forward.js", it was blocked. Seems not work for me?

        var mockAnyResponse = function (expectation) {
            return makeRequest(host, port, "/expectation");
        };

**Comment by mlessd** [comment]
makeRequest(host, port, "/expectation", expectation);

**Comment by ronayadid** [comment]
Hi, 

was this issue resolved?
I'm working with mockserver-client version 5.3.0

Thanks

**Comment by mocheng** [comment]
@ronayadid Not yet. 
For the time being, use the trick proposed by @andygaga2018 and @mlessd .

**Comment by ronayadid** [comment]
@mocheng But the 'makeRequest' function is not exposed.

**Comment by edilaver** [comment]
For my case, i have overcome the issue for now by adding an extra check to `addDefaultExpectationHeaders` so that default headers will not be added if the expectation is a forward exp.

**Comment by ronayadid** [comment]
But where did you add this check?

**Comment by edilaver** [comment]
Here it is:

` var addDefaultExpectationHeaders = function (expectation) {
            if (Array.isArray(expectation)) {
                for (var i = 0; i < expectation.length; i++) {
                    expectation[i].httpRequest = addDefaultRequestMatcherHeaders(expectation[i].httpRequest);
                    if(!expectation[i].httpForward) {
                      expectation[i].httpResponse = addDefaultResponseMatcherHeaders(
                          expectation[i].httpResponse);
                    }
                }
            } else {
                expectation.httpRequest = addDefaultRequestMatcherHeaders(expectation.httpRequest);
              if(!expectation[i].httpForward) {
                expectation.httpResponse = addDefaultResponseMatcherHeaders(
                    expectation.httpResponse);
              }
            }
            return expectation;
        };`

**Comment by mocheng** [comment]
@ronayadid Yes. Unfortunately the `makeRequest` is not exposed. So, I have to do dirty hack by modifying given file under `node_modules` folder.

**Comment by ronayadid** [comment]
@edilaver @mocheng 
But this needs to be done in mockServerClient.js inside the 'mockserver-client' package, right?

Is there a way to handle this without changing the package?

**Comment by mocheng** [comment]
@ronayadid Your are right. This is the drawback. I cannot figure out a way to handle this without changing the package. 

Now, I gave up on proxying feature of 'MockServer' and fill expectations with content from another proxy.

**Comment by ronayadid** [comment]
Thanks @mocheng 
Probably that's what I'll do

**Comment by pludov** [comment]
I 've created a pull request to optionally disable any default header, by passing null to setDefaultHeaders. This workaround works for me in the case of this issue, is backward compatible and breaks zero unit test.

https://github.com/jamesdbloom/mockserver-client-node/pull/26

**Comment by jamesdbloom** [comment]
this is now fixed and will be in the next release
