### ISSUE TITLE
mockserver does not respond when using callback

### ISSUE THREAD

**Issue by vorstenbosch-pwc** [jamesdbloom/mockserver#438]
I am trying to return an OTP that is placed in a file when a specific endpoint is being called on the mockserver. This means the response needs to be dynamic. I am trying to get this to work by using a callback action in the response as stated on http://mock-server.com/mock_server/creating_expectations.html#callback_action. 

I am using the following expectation inside an initializationClass run via maven. 

                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>5.3.0</version>
 

mockServerClient.when(
                request()
                        .withPath("GET")
                        .withPath(".*/getLastOtp.*")
        )
                .callback(
                        request -> response()
                                .withStatusCode(200)
                                .withBody(retrieveLastOtpFromDebugFile())
                );

and when it is called the mockserver seems to freeze. In the mockserver.log I can see:

2018-02-20 10:13:58,736 INFO [nioEventLoopGroup-3-2] o.mockserver.mock.HttpStateHandler [?:?] request:

        {
          "method" : "GET",
          "path" : "/getLastOtp",
          "headers" : {
            "content-length" : [ "0" ],
            "Connection" : [ "Keep-Alive" ],
            "User-Agent" : [ "Apache-HttpClient/4.5.5 (Java/1.8.0_101)" ],
            "Host" : [ "openam.dev.com:1080" ],
            "Accept-Encoding" : [ "gzip,deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 matched expectation:

        {
          "path" : ".*/getLastOtp.*"
        }

But then nothing happens. It seems my tests just wait indefinitely on the response from the mockserver.

When I stop my tests and restart without hitting this endpoint it works like it should, so it seems the mockserver is not frozen but just failes to respond. When I remove the logic in the above callback by a static String it has the same behaviour so it looks like its not my logic that breaks the mockserver.

What am I doing wrong?

**Comment by jcogilvie** [comment]
It's not just you.  Lambda callbacks in mockserver are broken in 5.2.0+.  Works on 5.1,1.

**Comment by vorstenbosch-pwc** [comment]
@jcogilvie thanks. But I am getting the same behaviour on 5.1.1 (or 5.1.0) so I am wondering if I am doing something else wrong..

**Comment by JimBobJohn** [comment]
I have the same issue still on version 5.3.0.

**Comment by JimBobJohn** [comment]
I have had the same/a similar issue. The reason in my case seemed to be that too many callbacks were created. Since the data structure holding registered references to created callbacks is limited to 100. So, if you have created more than 100 callbacks, the older ones got deleted and thus were not available anymore to respond. (seen in version 5.3.0)

**Comment by gboorse** [comment]
I am having the exact same issue describe above. Bump.

**Comment by abadarinath** [comment]
having same issue. I am using 5.3.0 is there any solution to this or work around?

**Comment by zhang8473** [comment]
Same issue. It happens more frequently in Docker container. Using 5.3.0. I am unable to use the software any more because of this issue.

**Comment by jamesdbloom** [comment]
Please upgrade to version 5.4.1 for both MockServer and mockserver-client-node and this is now fixed.

**Comment by jamesdbloom** [comment]
I have also increased the maximum number of supported callback this will be available in the next release.

**Comment by Hendrione** [comment]
Hii... I got this issue on version 5.5.1. I am running mockserver using docker and when I using callback(), it is not working.

**Comment by Hendrione** [comment]
It is not working even I tried using simple function:
```
        client.when(request()
            .withPath("/xlog")
            .withMethod("POST")
            .withHeaders(
                new Header(CONTENT_TYPE.toString(), "application/json")
            )).respond(new ExpectationResponseCallback() {
            @Override
            public HttpResponse handle(HttpRequest httpRequest) {
                if (httpRequest.getMethod().getValue().equals("POST")) {
                    return response()
                        .withBody("hello coy");
                } else {
                    return notFoundResponse();
                }
            }
        });
```

Here is the log:

```
2019-01-17 07:41:05,315 INFO o.m.m.HttpStateHandler request:

        {
          "method" : "POST",
          "path" : "/xlog",
          "headers" : {
            "Content-Type" : [ "application/json" ],
            "cache-control" : [ "no-cache" ],
            "Postman-Token" : [ "afe69cb2-bf64-4892-abd4-a60001b95831" ],
            "User-Agent" : [ "PostmanRuntime/7.6.0" ],
            "Accept" : [ "*/*" ],
            "Host" : [ "127.0.0.1:1080" ],
            "accept-encoding" : [ "gzip, deflate" ],
            "content-length" : [ "77" ],
            "Connection" : [ "keep-alive" ]
          },
          "keepAlive" : true,
          "secure" : false,
          "body" : {
            "type" : "STRING",
            "string" : "{  \"awbNumbers\": [\r\n    \"JNE0129834765\"\r\n  ],\r\n  \"logisticProvider\": \"JNE\"\r\n}",
            "contentType" : "text/plain; charset=utf-8"
          }
        }

 matched expectation:

        {
          "httpRequest" : {
            "method" : "POST",
            "path" : "/xlog",
            "headers" : {
              "content-type" : [ "application/json" ]
            }
          },
          "times" : {
            "unlimited" : true
          },
          "timeToLive" : {
            "unlimited" : true
          },
          "httpResponseObjectCallback" : {
            "clientId" : "ca58bacc-b71d-415f-9f27-33554f5810bd"
          }
        }
```

**Comment by Hendrione** [comment]
One question: 
If in my callback I using method that need dependencies like Jackson.. this callback still can running or not?

**Comment by jamesdbloom** [comment]
When you say it is not working, what do you mean?  Can you please provide more information so I can understand what problem you are having.

**Comment by Hendrione** [comment]
@jamesdbloom Here is what I do:

1. I run mock server using docker. I am using command `docker run -d -p 1080:1080 --name mockserver jamesdbloom/mockserver`
2. I check using `docker container ls` and see the mock server already running.
3. I tried adding simple mock using `MockServerClient` Object. Doesn't use method/closure callback for the response.
4. I tried hit the mockserver by using the API spec that I already defined and mockserver return the response (Still run smoothly)
5. I tried more advanced one to create mock using method/closure callback for the response. I just copy paste the sample code on the documentation page. 
```
new MockServerClient("localhost", 1080)
    .when(
        request()
            .withPath("/test")
    )
    .respond(
        new ExpectationResponseCallback() {
            @Override
            public HttpResponse handle(HttpRequest httpRequest) {
                if (httpRequest.getMethod().getValue().equals("POST")) {
                    return response()
                        .withBody("an_object_callback_response");
                } else {
                    return notFoundResponse();
                }
            }
        }
    );
```
6. I tried hit the API again using postman. The mock server seems doesn't return anything until the request timeout. I already check the log using `docker container logs mockserver` command and getting the log like this:
2019-01-17 07:41:05,315 INFO o.m.m.HttpStateHandler request:

```
        {
          "method" : "POST",
          "path" : "/xlog",
          "headers" : {
            "Content-Type" : [ "application/json" ],
            "cache-control" : [ "no-cache" ],
            "Postman-Token" : [ "afe69cb2-bf64-4892-abd4-a60001b95831" ],
            "User-Agent" : [ "PostmanRuntime/7.6.0" ],
            "Accept" : [ "*/*" ],
            "Host" : [ "127.0.0.1:1080" ],
            "accept-encoding" : [ "gzip, deflate" ],
            "content-length" : [ "77" ],
            "Connection" : [ "keep-alive" ]
          },
          "keepAlive" : true,
          "secure" : false,
          "body" : {
            "type" : "STRING",
            "string" : "{  \"awbNumbers\": [\r\n    \"JNE0129834765\"\r\n  ],\r\n  \"logisticProvider\": \"JNE\"\r\n}",
            "contentType" : "text/plain; charset=utf-8"
          }
        }

 matched expectation:

        {
          "httpRequest" : {
            "method" : "POST",
            "path" : "/xlog",
            "headers" : {
              "content-type" : [ "application/json" ]
            }
          },
          "times" : {
            "unlimited" : true
          },
          "timeToLive" : {
            "unlimited" : true
          },
          "httpResponseObjectCallback" : {
            "clientId" : "ca58bacc-b71d-415f-9f27-33554f5810bd"
          }
        }
```

**Comment by SandorDobos** [comment]
I had the same issue as some of posters here (found matching expectation but no response).
My solution was a `try-catch` block inside `ExpectationResponseCallback.handle()` and log exceptions.
MockServer runs the callback via `scheduler.submit()`, and nobody handles nor logs exceptions on actual callstack. See: issues #606
The `try-catch` block reveals problem in my code and thatswhy client never got a response.
Hendrione may have a different issue, but others may have this tipp useful.
S
