### ISSUE TITLE
Allow all CORS header values to be configurable

### ISSUE THREAD

**Issue by nkguoym** [jamesdbloom/mockserver#441]
I use the mockserver to support custom ACCESS_CONTROL_ALLOW_HEADERS header in preflight request, but it not work. Maybe I used the wrong way, please do me a favor. thanks

**Request Headers**
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
**Access-Control-Request-Headers:x-csrf-token,x-requested-with**
Access-Control-Request-Method:GET
Cache-Control:no-cache
Connection:keep-alive
Host:localhost:1080
Origin:http://localhost:3000

**Response Headers**
**Access-Control-Allow-Headers:Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary**
Access-Control-Allow-Methods:CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, TRACE
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary
Access-Control-Max-Age:300
connection:keep-alive
content-length:0
X-CORS:MockServer CORS support enabled by default, to disable ConfigurationProperties.enableCORSForAPI(false) or -Dmockserver.disableCORS=false

**Comment by nkguoym** [comment]
use the solution you mentioned before. sorry for this.

**Comment by jamesdbloom** [comment]
I will look to add configuration options to override all CORS header values shortly.

**Comment by jamesdbloom** [comment]
This is a high priority feature and will be worked on very soon but new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/tmLO2bEE/24-allow-all-cors-header-values-to-be-configurable

**Comment by jamesdbloom** [comment]
This is now implemented and will be in the next RELEASE at that point the website documentation will also be updated.
