### ISSUE TITLE
HttpForward doesn't update request Host header

### ISSUE THREAD

**Issue by mocheng** [jamesdbloom/mockserver#442]
The default behavior of `httpForward` doesn't update forward-request host header. Given below config of mock server on `localhost:1080`, a request sent to mock server is forwarded with `host` still as `localhost:1080`. In case the target server `localhost:9000` has validation of Host name, it fails.

```
      httpForward: {
        host: 'localhost',
        port: 9000,
      },
```
It is preferable to have some way to customize forward request. I know that `httpForwardTemplate` can do the trick. But, the requirement is to just tweak one header, using `httpForwardTemplate` means to move all info from `request`. It is clumsy.

Is there any better solution?

**Comment by whites11** [comment]
Any news on this? I need to update the Host header, too.

**Comment by maksmi** [comment]
Hi, for the moment it is not working for me , so i use nginx proxy instead. so it will be like Mock-server -> nginx (header updae) -> proxy_host

**Comment by jamesdbloom** [comment]
Please use one of the other forwarding mechanisms.  The mechanism you have used is not designed to update the request in any way.  It is possible to this using either a templated forward or a callback as described on the website http://mock-server.com/mock_server/creating_expectations.html#actions
