### ISSUE TITLE
Verifying method & path at the same time does not work?

### ISSUE THREAD

**Issue by tomekbielaszewski** [jamesdbloom/mockserver#445]
Hi,

I might have found a bug in request verification or I don't fully get how it works. Or maybe builder-ish architecture is misleading here?

Let me present this on an example:

I've added two URLs to the mockserver:
`GET: /foo/bar`
`PUT: /foo/bar`
then I call those endpoinds and everything is working as expected. But when I want to verify if my PUT endpoint was called exactly X times (having my GET endpoint called also before) I get following assertion error:
```
java.lang.AssertionError: Request not found exactly once, expected:<{
"method" : "PUT",
  "path" : "/foo/bar"
}> but was:<{
  "method" : "GET",
  "path" : "/foo/bar",
  "queryStringParameters" : {
    //does not matter
  },
  "headers" : {
    //does not matter
  },
  "keepAlive" : true,
  "secure" : false
}>
  at org.mockserver.client.AbstractClient.verify(AbstractClient.java:277)
  at utilities.MockService.assertPUTWasCalled(MockService.java:86)
```

my verification code looks like this:

```java
    public void assertPUTWasCalled(String path, int numberOfTimes) throws AssertionError {
        new MockServerClient("localhost", runningPort)
                .verify(
                        request()
                                .withPath(path)
                                .withMethod("PUT"),
                        VerificationTimes.exactly(numberOfTimes)
                );
    }
```

**Comment by jamesdbloom** [comment]
I can't reproduce this error.  Please retest with the latest version.  If it is still a problem please reopen the issue with the full log.
