### ISSUE TITLE
export & import expectations

### ISSUE THREAD

**Issue by deq9z** [jamesdbloom/mockserver#450]
it would be **nice** if mock-server would support **exporting** and **importing** expectations.

**Comment by rajendrapenumalli** [comment]
yes

**Comment by jamesdbloom** [comment]
This is already possible using the REST API.

## Export

`PUT /mockserver/retrieve?type=active_expectations` returns a JSON array of the active expectations.

## Import

`PUT /mockserver/expectation` endpoint accept a JSON array of expectations (or a single expectation).
