### ISSUE TITLE
Support Server-sent events

### ISSUE THREAD

**Issue by DanielMSchmidt** [jamesdbloom/mockserver#453]
Hey there,

I would like to mock [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events). Is there currently a way to do it and if not, how hard would it be to add support? Would be willing to dig in and do a PR if it's not near an entire rewrite ;)

Thank you for the passion you put into this project, it's highly appreciated 👍

**Comment by jamesdbloom** [comment]
A PR on Server-Sent Event would be happily received.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/VhZCtmAo/25-support-server-sent-events
