### ISSUE TITLE
Unable to set velocity template location when using the war, using REST.

### ISSUE THREAD

**Issue by Some-Java-Developer** [jamesdbloom/mockserver#459]
Hello,

we are using the mockserver on a tomcat server to allow easy installation of mocks for our applications.
This is working fine for more static content, but we would like to use Velocity templates through the REST API.
The issue is that there is no way to set the velocity template location.
I tried setting the java property 'file.resource.loader.path' on the tomcat JVM, but it is not picked up by the war.
How can I set the location where the Velocity templates are searched?
I do not want to define the entire template in the JSON of the rest call, as this is simply too complex to handle all the escaping for the JSON.

Kind regards

**Comment by Some-Java-Developer** [comment]
Looking at the code, I think there is something missing to set the system.properties in the context of the scripting engine. In the class org.mockserver.templates.engine.velocity.VelocityTemplateEngine:

public <T> T executeTemplate(String template, HttpRequest request, Class<? extends DTO<T>> dtoClass) {
        T result = null;
        try {
            Writer writer = new StringWriter();
            ScriptContext context = engine.getContext();
            context.setWriter(writer);
            context.setAttribute("request", new HttpRequestTemplateObject(request), ScriptContext.ENGINE_SCOPE);
            engine.eval(template);
...

I think it will never pick up the system.properties like that.
I'm also not able to override the verlocity.properties like this.
If we could override the velocity.properties, that would surely help.

On my tomcat in the logs, I can clearly see that the property is set:

02-May-2018 09:42:57.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-May-2018 09:42:57.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.resource.loader.path=R:/apps/mockserver/config/templates

But is not being picked up by the velocity engine:

09:43:28.437 [http-nio-8080-exec-1] DEBUG org.apache.velocity - Initializing Velocity, Calling init()...
09:43:28.438 [http-nio-8080-exec-1] DEBUG org.apache.velocity - Starting Apache Velocity v2.0
09:43:28.444 [http-nio-8080-exec-1] DEBUG org.apache.velocity - Default Properties resource: org/apache/velocity/runtime/defaults/velocity.properties
09:43:28.457 [http-nio-8080-exec-1] DEBUG org.apache.velocity - ResourceLoader instantiated: org.apache.velocity.runtime.resource.loader.FileResourceLoader
09:43:28.460 [http-nio-8080-exec-1] DEBUG org.apache.velocity.loader.file - FileResourceLoader: adding path '.'
09:43:28.462 [http-nio-8080-exec-1] DEBUG org.apache.velocity - initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl) with class java.util.Collections$SynchronizedMap cache map.

Regards,

**Comment by Some-Java-Developer** [comment]
I modified the velocity.properties inside the velocity base jar (just to test if the template would be found) and this is the case.
However, it is still requires that template is escaped, which is not very logical, since the template is on the file system at the time it is being picked up (it is not send through an http request).
I think there is an issue in the usage of these vm templates. They are almost impossible to use through the rest interface.
Any ideas?
Is anybody using these effectively?

**Comment by jamesdbloom** [comment]
There is no support for specifying the location of the velocity template this was never part of the design and there is no way to specific which template to use.  I agree using the templates via the REST API is not easy.

Can you please explain what you are trying to do and whether you can use the Netty version of MockServer which has more features then the WAR version due to JEE Web Profile limitations and unnecessary complexity.
