### ISSUE TITLE
HttpRequest.replaceHeader(myHeader) is not replacing an existing header, is creating new expectation

### ISSUE THREAD

**Issue by vvargas90** [jamesdbloom/mockserver#467]
I've the following method 
```
public MockHelper setupForwardAll() {
        mockServerClient
                .when(request())
                .forward(
                        forward()
                                .withHost(hostToForward)
                                .withPort(443)
                                .withScheme(HTTPS)
                );
        return this;
    }
```
that have the aim to forward all the request if doesn't match any expectations I've previously set, so I don't need to mock everything in my tests (not the best approach maybe, but it's not the point). 

If I do this tiny modification:
```
public MockHelper setupForwardAll() {
        Header hostHeader = new Header(HOST.toString(), hostToForward);
        mockServerClient
                .when(request().replaceHeader(hostHeader))
                .forward(
                        forward()
                                .withHost(hostToForward)
                                .withPort(443)
                                .withScheme(HTTPS)
                );
        return this;
    }
```
I'm expecting that mockserver is going to replace the header "Host" (which value is my local ip machine because I'm redirecting all network requests to the mockserver) to the real host, but what actually it's doing is creating an extra expectation. See the following log:

```
2018-05-03 13:39:18,187 INFO o.m.m.HttpStateHandler request:
2018-05-03T13:39:18.201293000Z 
{
  "method" : "GET",
  "path" : "/foo/bar",
  "headers" : {
    "Authorization" : [ "Bearer someToken1234" ],
    "content-length" : [ "0" ],
    "Accept" : [ "application/json" ],
    "User-Agent" : [ "node-superagent/3.5.2" ],
    "Base-User-Id" : [ "0" ],
    "host" : [ "192.168.110.179:1080" ],
    "connection" : [ "keep-alive" ],
    "accept-encoding" : [ "gzip,deflate" ]
  },
  "keepAlive" : true,
  "secure" : false
}
2018-05-03T13:39:18.201497500Z 
 did not match expectation:
2018-05-03T13:39:18.201517000Z 
{
  "headers" : {
    "Host" : [ hostToForward ]
  }
}
2018-05-03T13:39:18.201584700Z 
 because:
2018-05-03T13:39:18.201603800Z 
method matches = true
path matches = true
query string parameters match = true
body matches = true
headers match = false
cookies match = true
keep-alive matches = true
ssl matches = true
```
**Extra information:** 
Mockserver version: 5.3.0

**Comment by jamesdbloom** [comment]
`replaceHeader(hostHeader)` replaces the header in the `HttpRequest` object created with the `request()` factory method.  The forward action you have specified doesn't update the request being forwarded in any way.  If you want the request being forwarded to be update try using one of the forward actions that updates the request, there are 5 options to choose between as detailed on the website: http://mock-server.com/mock_server/creating_expectations.html#actions

**Comment by vvargas90** [comment]
Thanks for the insight, it absolutely worked 😄
