### ISSUE TITLE
MockServerRule JUnit5 Support

### ISSUE THREAD

**Issue by acheaito** [jamesdbloom/mockserver#470]
With JUnit 5 not supporting @Rule, it is not possible to use the convenience class MockServerRule. Would be nice to have support for this using JUnit 5 extensions.

**Comment by jamesdbloom** [comment]
As I understand this requires Java 8.  Once some more issues have been resolved I will upgrade from Java 7 to 8.  I want to resolve some issues first so that users who are on Java 7 have their bugs fixed before I upgrade to Java 8 in a new major release.

**Comment by im-bhatman** [comment]
Was it added ? If yes, please point me to the implementation file.

**Comment by findusl** [comment]
@im-bhatman this solves it for me https://www.mock-server.com/mock_server/running_mock_server.html#junit_test_extension
