### ISSUE TITLE
Https when using Java MockServerClient against loadbalanced Mockserver

### ISSUE THREAD

**Issue by Tandolf** [jamesdbloom/mockserver#472]
So im running a Mockserver in an Openshift cluster (Kubernetes) and want to set up expectations from outside the cluster (travis buildserver, or any other build server).

When using the MockServerClient every request (clear, start, stop, retriveLogs, when) are done with Http.

```
//MockServerClient.class
private HttpResponse sendRequest(HttpRequest request) {
        HttpResponse response = nettyHttpClient.sendRequest(
            request.withHeader(HOST.toString(), this.host + ":" + port()),
            ConfigurationProperties.maxSocketTimeout(),
            TimeUnit.MILLISECONDS
        );
        //more code below but omitted for clarity
}
```
When the mockserver is deployed behind a loadbalancer (OpenShift) and i want to set up expectations or use any other client-feature, all requests must be made with https but currently per default are made with the "withSecure" flag set to false hence http. 

I have solved this by extending the MockServerClient, overriding and adding the "withSecure" flag to each request that gets sent.

```
public class SecureMockServerClient extends MockServerClient {
    SecureMockServerClient(String host, int port) {
        super(host, port);
    }

    @Override
    protected HttpResponse sendRequest(HttpRequest request) {
        return super.sendRequest(request.withSecure(true));
    }
}
```

Im thinking more than I must/will have this problem, and maybe there should be a configurable option for this. 

Or is this a special case?

**Comment by reitoo** [comment]
Now, the workaround doesn't work anymore because MockServerClient.sendRequest is now private :-(

**Comment by jamesdbloom** [comment]
The `MockServerClient` class now has a method `public MockServerClient withSecure(boolean secure)` this allows you to make calls using TLS.

I will also improve the documentation of this feature.
