### ISSUE TITLE
empty body matches xpath

### ISSUE THREAD

**Issue by jarekczek** [jamesdbloom/mockserver#473]
My xpath expectations started matching empty body in 5.3.1-SNAPSHOT. It was ok in 5.3.0. Attaching a patch which adds a test exposing the bug.

[xpath_empty_body_bug.zip](https://github.com/jamesdbloom/mockserver/files/2002203/xpath_empty_body_bug.zip)

**Comment by jamesdbloom** [comment]
This is now fixed in the latest SNAPSHOT version http://mock-server.com/where/maven_central.html#sonatype_snapshot and will be in the next release.
