### ISSUE TITLE
Question: how are the expectations stored internally?

### ISSUE THREAD

**Issue by michelzanini** [jamesdbloom/mockserver#475]
Hi sorry for creating an issue here, but I can't find this on documentation or anywhere, so you can close this as soon as you answer the question.

Once expectations are created against the mock server, how are they internally stored? In memory?

I am asking this because, for performance tests, I might need to run 2 or more mock server boxes behind a load balancer, to support the load. That means, if an expectation is created on box A, and the verify goes to box B, how would that work?

Is this supported?

Thanks.

**Comment by jamesdbloom** [comment]
Yes expectations are stored internally in memory.  This is currently no support for clustering multiple instances of MockServer.  I suggest if you need multiple instance please setup them up identically so they both behave in the same way (although I accept that may not always be that easy).

I'm going to close this issue but please let me know if you have any further questions (I'll respond much quicker this time).
