### ISSUE TITLE
MockServer Proxy doesn't pass POST request's parameters

### ISSUE THREAD

**Issue by mbalemezova** [jamesdbloom/mockserver#476]
I'm trying to create the following scenario:
I want to create GET request to the server which to be mocked and the returned response to be 403(this work).  After this response my application has to create login operation. In this operation POST request is sent to the server, but the request's parameters are not sent to the server via MockServer Proxy.

I'm running MockServer Proxy via command line using java and pass proxyPort, after that I'm creating expectation for the mentioned GET request.

So I want to ask am I doing the things wrong or this is a bug?

Thanks in advance.

**Comment by jamesdbloom** [comment]
I have just manually tested the proxy passing request parameters and I can't reproduce your issue.  Can you please provide some more code / examples of the problem you are having so I can understand what your issues.

**Comment by jamesdbloom** [comment]
Please provide re-open issue when requested information is provided
