### ISSUE TITLE
Mock SMTP Protocol

### ISSUE THREAD

**Issue by Brianenno2** [jamesdbloom/mockserver#477]
Hey there,

sorry for creating an issue here, but I wasn't able to find any information around the documentation/google/forum.
I would like to mock the possibility to send the email by using the SMTP protocol. Is there currently a way to do it and if not, how hard would it be to add support? 

Thanks a lot for the great work done so far!

**Comment by jamesdbloom** [comment]
Although mocking SMTP is a reasonable idea it is beyond the scope of the MockServer which is focused on mocking HTTP endpoints.  There are existing alternative solutions for mocking SMTP, such as, https://mailtrap.io/ http://nilhcem.com/FakeSMTP/
