### ISSUE TITLE
Clarification on Terminology

### ISSUE THREAD

**Issue by rk-git** [jamesdbloom/mockserver#478]
I am having trouble understanding how to use MockServer since the description is sparse 
and terminology is not clear. 

1) What is MockClient? If I am mocking a service that my system under tests uses, then the "client" of the mock is my system under test is it not? Yet, the description suggests that "client" is used to define expectations!

2) What is a MockProxy?

Regards,

Rk

**Comment by jamesdbloom** [comment]
The MockClient is used to configure the expectations that define how the mock will behave, i.e. what response to return when it receives a specific request, etc.

The proxy is used to intercept calls made from the SUT to third part non-mocked systems so you can either analyze how the SUT interacts with it dependencies or only mock specific dependencies.
