### ISSUE TITLE
Standalone MockServer: Where do I implement expectations?

### ISSUE THREAD

**Issue by rk-git** [jamesdbloom/mockserver#479]
I am running a standalone MockServer using:

```
$ java -jar ./mockserver-jetty-jar-with-dependencies.jar -serverPort 1080 -proxyPort 1090 -proxyRemotePort 80 -proxyRemoteHost www.mock-server.com
Error: Unable to access jarfile ./mockserver-jetty-jar-with-dependencies.jar
RKS-M-J0HS:mock rks$ java -jar ./mockserver-netty-5.3.0-jar-with-dependencies.jar -serverPort 1080 -proxyPort 1090 -proxyRemotePort 80 -proxyRemoteHost www.mock-server.com
2018-05-23 14:05:57,703 INFO o.m.m.MockServer MockServer started on port: 1080
2018-05-23 14:05:57,747 INFO o.m.p.d.DirectProxy MockServer started on port: 1090

```

How do I define (implement) expectations?

I have repeatedly read the documentation - while its clear on the high level,
its missing salient details.

Thanks,

Rk

**Comment by php-coder** [comment]
As far I understand, mockserver client should be used for defining expectations. See examples with code at http://www.mock-server.com/mock_server/creating_expectations.html

**Comment by jamesdbloom** [comment]
Please use the example code shown in javascript and java in the documentation: http://mock-server.com/mock_server/getting_started.html#setup_expectations
