### ISSUE TITLE
Add JsonPath support

### ISSUE THREAD

**Issue by vadim-shb** [jamesdbloom/mockserver#480]
Add body verification with jsonPath
It could look like:
```
MockServer.verify(
    request()
        .withBody(
            jsonPath("$.towns[0].id").value(100)
        ),
);
```
We can create the similar API as in Spring Test project (e.g. org.springframework.test.web.servlet.result.JsonPathResultMatchers) 
We can create the same jsonPath library: 'com.jayway.jsonpath:json-path'

**Comment by jamesdbloom** [comment]
It is a very good idea to support matchers based on jsonPath, it should be feasible to support, equals, contains, greaterThen, greaterThenOrEquals, lessThen and lessThenOrEquals.

**Comment by jamesdbloom** [comment]
added support for json path but still need to do documentation

**Comment by jamesdbloom** [comment]
competed
