### ISSUE TITLE
TLS - Allow to specify AC

### ISSUE THREAD

**Issue by xLitil** [jamesdbloom/mockserver#486]
Hi, 

is it possible to replace mock-server AC by another one (custom) ?

Regards

**Comment by jamesdbloom** [comment]
Do you mean a custom CA, if so yes this is possible, please see: http://mock-server.com/mock_server/configuration_properties.html#button_configuration_log_level#button_configuration_disable_request_audit the fragment part of that link is incorrect so after the next release that URL will change to http://mock-server.com/mock_server/configuration_properties.html#button_configuration_log_level#button_configuration_tls_certificate_authority_private_key
