### ISSUE TITLE
Implemnent a new Feature to export and import expectation to a json file

### ISSUE THREAD

**Issue by rajendrapenumalli** [jamesdbloom/mockserver#491]
Hi james,
Could you please a new feature to export and import expectation to a json file from via REST Interface.

This is lacking in Mock server and i feel it is a real weakness for Mockeserver.

Thanks
Rajendra

**Comment by Tandolf** [comment]
why don't you just read your jsonfile and then use the mockserver-client to set up your expectations?

**Comment by rajendrapenumalli** [comment]
I feel suggested approach is an  alternative!!! ,
but if this feature implemented i makes easy to use this product(ease of use).

Thanks,
Rajendra

**Comment by jamesdbloom** [comment]
This is already implemented using the REST API.

## Export

`PUT /mockserver/retrieve?type=active_expectations` returns a JSON array of the active expectations.

## Import

`PUT /mockserver/expectation` endpoint accept a JSON array of expectations (or a single expectation).
