### ISSUE TITLE
Unable to override default logging

### ISSUE THREAD

**Issue by ashimaaaa** [jamesdbloom/mockserver#492]
I am invoking mockserver programatically via API as follows:

    private ClientAndServer mockServer;
    System.setProperty("logback.configurationFile", file.getAbsolutePath());
    mockServer = ClientAndServer.startClientAndServer(1080);

Where file is example_logback.xml as stated in #309  last comment.

However no log file is created and everythign still gets dumpedto stdout.

Please guide if i am not doing it correctly.

**Comment by ashimaaaa** [comment]
Hi, Anyone knows why I am facing issues overriding logback and how can i control logging?

**Comment by jamesdbloom** [comment]
I have reinstated the `example_logback.xml` which sends logs to a file but outputs WARN and above to the console.  Please ensure you have passed the `logback.configurationFile` system properties into the JVM as follows:

```bash
java -Droot.logLevel=WARN -Dmockserver.logLevel=INFO -Dlogback.configurationFile=/Users/jamesbloom/git/mockserver/mockserver/mockserver-netty/src/main/resources/example_logback.xml -jar /Users/jamesbloom/git/mockserver/mockserver/mockserver-netty/target/mockserver-netty-5.4.2-SNAPSHOT-jar-with-dependencies.jar -serverPort 1080
```
