### ISSUE TITLE
Cannot set httpResponseTemplate response action in expectation

### ISSUE THREAD

**Issue by simoncowie** [jamesdbloom/mockserver#494]
Using the latest docker version of mock server (5.3.0), I can't set an `httpResponseTemplate` as per the example at http://www.mock-server.com/mock_server/creating_expectations.html#button_javascript_templated_response. 

I get the error message: ` - oneOf of the following must be specified "httpForward" "httpForwardTemplate" "httpClassCallback" "httpError" "httpObjectCallback"` 

`mockserver-client` and `mockserver-node` are both 5.3.0 from npm. 

My setup: 

```
var mockserver = require('mockserver-node');
var mockServerClient = require('mockserver-client').mockServerClient;
var mockserver_port = 3211;

mockserver
  .start_mockserver({ serverPort: mockserver_port, verbose: true })
  .then(
    function () {
      //General get
      mockServerClient("localhost", mockserver_port).mockAnyResponse({
        "httpRequest": { "path": "/some/path" },
        "httpResponseTemplate": {
          "template": "{\n" +
            "     \"statusCode\": 200,\n" +
            "     \"cookies\": {\n" +
            "           \"session\": \"$!request.headers['Session-Id'][0]\"\n" +
            "      },\n" +
            "     \"headers\": {\n" +
            "           \"Client-User-Agent\": [ \"$!request.headers['User-Agent'][0]\" ]\n" +
            "      },\n" +
            "     \"body\": $!request.body\n" +
            "}",
          "templateType": "VELOCITY"
        }
      }
      ).then(
        function () {
          console.log("created catch all GET sessions expectation");
        },
        function (error) {
          console.log(error.body);
        }
      );

    },
    function (error) {
      console.log(JSON.stringify(error));
    }
  );

```

**Comment by rajendrapenumalli** [comment]
Even i facing same error

**Comment by TonyBray** [comment]
I ran into the same issue today.  Also, I am not sure if template or callback is best solution for me, I need to get xml value from body and reply back with that value.  Since I get the same error as above, I cannot test templates at all.

**Comment by simoncowie** [comment]
@TonyBray I've just gone with callbacks and so far that's worked out well.

**Comment by rajendrapenumalli** [comment]
Hi Simon ,
Could you please post some example for callback expectation implementation.

Thanks,
Rajendra

**Comment by rajendrapenumalli** [comment]
Hi Tony, 
we are able to use/test JavaScript and Velocity templates successfully.
In next couple of hours I can post some sample here.

Thanks
Rajendra

**Comment by simoncowie** [comment]
Here is an example @rajendrapenumalli :  https://gist.github.com/simoncowie/f7b0eacf816914807c41c53d476d591d

**Comment by josejulio** [comment]
I have the same issue, can't use templates. @rajendrapenumalli did you solved it?

**Comment by jamesdbloom** [comment]
this is now fixed
