### ISSUE TITLE
Make logback dependency optional

### ISSUE THREAD

**Issue by aheritier** [jamesdbloom/mockserver#495]
Please make the logger implementation option (Few lines of reflection should do it I think). 
For now it [isn't](https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/logging/MockServerLogger.java#L32) which is annoying for exemple if you use mockserver in tests and you have another constraint (hello elasticsearch [22671](https://github.com/elastic/elasticsearch/issues/22671) which is bad too for the same reason) which is enforcing another logging implementation (log4j2)

Thanks

**Comment by chrisribble** [comment]
+1

**Comment by taylorp36** [comment]
+1

**Comment by Vampire** [comment]
You don't even need reflection, a simple class-present check is enough in this case.
