### ISSUE TITLE
How best to respond with values from request?

### ISSUE THREAD

**Issue by TonyBray** [jamesdbloom/mockserver#497]
I have calls that send a unique value to a server and the server responds with these values.  The values are sometimes in xmxl, and other times in form bodies.  I can see how to use matchers to match values in the xml or form but how do I return them in the response dynamically?  

Would Template responses be the best?  If so, based on the few examples, how do I access the body of the request to parse the values I want?  If callback would work better, same question.  I cannot seem to access the body from the callback.

**Comment by jamesdbloom** [comment]
I would suggest using a callback is the easiest option, as shown in the example on the website it is possible to directly access the `HttpRequest` as the parameter passed into the callback, see: http://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback.  The `HttpRequest` object has a `getBody()` function that can be used to retrieve the body of the request.
