### ISSUE TITLE
Mock server working only for the first time request 

### ISSUE THREAD

**Issue by panthasit** [jamesdbloom/mockserver#502]
I have a problem with the mock server using the docker image jamesdbloom/mockserver. After I got the success response. I try to send another request which is the same but I got 404 not found

**Comment by panthasit** [comment]
@jamesdbloom Do you have any suggestion?

**Comment by JimBobJohn** [comment]
@panthasit A suggestion would be to make the `times` attribute of `RequestResponseLogEntry` to be configurable - like `mockserver.maxExpectations` property.

@jamesdbloom Would that be feasible?

**Comment by eschumann** [comment]
did you take a look at the documentation regarding the feature for limiting hits of matching expectations? see : https://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_path_exactly_twice
adding something like : 
`"times": {
        "unlimited": true
}`

to your expectation could solve your issue.

**Comment by jamesdbloom** [comment]
I agree it sounds like @eschumann answer is correct, however the behaviour on this has changed in the recent release so that `unlimited` is set by default because several people were confused by the previous logic.
