### ISSUE TITLE
Implement a feature to make the expectations persistent.

### ISSUE THREAD

**Issue by saratchandra132** [jamesdbloom/mockserver#503]
Hi James,
As of now the expectations are stored in memory, any thoughts or future plans in integrating this with some database and load the memory on runtime so that expectations are not lost on a server restart. Any suggestions on better ways of doing this are highly appreciated.

Thanks in advance :)

**Comment by giorgiosironi** [comment]
The workaround I'll use at the moment is to store the file with `curl` requests I use to configure the Docker container, to execute it at each restart.

**Comment by jamesdbloom** [comment]
This will be implemented at part of 5.5.1 likely in the next month or two.

**Comment by giorgiosironi** [comment]
If it helps anyone in the mean time, this is my way to do this on the Docker container:
https://github.com/elifesciences/builder-base-formula/blob/master/elife/config/home-deploy-user-mockserver-docker-compose.yml
https://github.com/elifesciences/elife-bot-formula/blob/master/salt/elife-bot/config/mockserver-elife-bot.sh

This configuration, when put on a server, will survive reboots and being recreated every time the container starts.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/qOgJgBee/26-persistence-expectations

**Comment by jamesdbloom** [comment]
This issue is nearly ready, I have done the basic implementation, but there are a few more small areas as documented on https://trello.com/c/qOgJgBee/26-persistence-expectations

**Comment by jamesdbloom** [comment]
I have now completed this which is available in the SNAPSHOT version and will shortly be available in a RELEASE

**Comment by nitinkasat** [comment]
It looks like, with this feature implemented, the expectations can be saved only to a file. Is there a way to persist them say in database? We use Kubernetes and pods get created/destroyed on demand. In such cases having them persisted and loaded from say some database would be convenient.

**Comment by jamesdbloom** [comment]
@nitinkasat You could use a [statefulset](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/)?

Currently the major cloud providers support:
- AWS supports both [EBS](https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs) and EFS for StorageClasses to support a statefulset, see: https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html
- Azure supports both [File](https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file) and [Disk](https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk)
- Google supports [Persistent Disk](https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd)

The issue with support databases more generically is this add a lot of complexity and too many options, should I support:
ODBC,
JDBC,
DynamoDB
CosmosDB
BigTable
S3,
BlobStorage
CloudStorage,
etc

I'm open to the idea of separate modules / repos to provide support for DynamoDB, CosmosDB, etc however even such an approach would be fairly complex for people to use in the form of IAM Roles / Groups, Bucket Name, Schema, etc

**Comment by nitinkasat** [comment]
Thanks so much @jamesdbloom  for quick response. I will definitely look at the option of stateful set. Just in case if we still want to implement saving to database for our custom requirement, is there a way for me to subscribe to expectation addition/update events? After going through source code, I find MockServerEventLogNotifier class has registerListener, but it looks like there is not a straightforward way to get access of right weaved in MockServerEventLog class. Any pointers would really be helpful.

**Comment by jamesdbloom** [comment]
Let me take a look later today if it's not already doable I can make sure this is easy to do because it definitely makes sense to support that.  I'll also add some documentation on how to do it for expectations and log events.

**Comment by jamesdbloom** [comment]
@nitinkasat I have now added a listener for expectation modifications that can be used with ExpectationInitializer for custom expectation persistence, see the commit above this will be release later this week.

**Comment by nitinkasat** [comment]
Thanks so much @jamesdbloom . It is really helpful.

**Comment by xalakox** [comment]
Am I missing something, if I currently add persistence expectation path, the file should be updated automatically when replying a proxied request right ?

I've been trying to get the persistence file to work w/o me dumping the expectations using another script that downloads them from the endpoint.
