### ISSUE TITLE
Documentation: ProxyRule not present in version 5.4.1

### ISSUE THREAD

**Issue by RussellRC** [jamesdbloom/mockserver#508]
I tried to upgrade from 5.3.0 to 5.4.1 but some of my tests use the ProxyRule, which I noticed is no longer present as well as a bunch of other classes that The ProxyRue depends on.

I dug around in the code (documentation is not up-to-date) to see if there was a replacement or a way around it but doesn't look like it.

* Any suggestions to circumvent the lack of ProxyRule and related classes?
* Is it going to be added back in a future version?  If so, what is the expected version?

**Comment by Vampire** [comment]
I just wanted to start using this project for mocking a proxy, so I'm having the same struggle.
Considering this commit: https://github.com/jamesdbloom/mockserver/commit/50f4ddaaf5c38b8dc6f529c1f3e79deb9354c380 I'd guess that you just use a `MockServerRule` now.

**Comment by Vampire** [comment]
I'd suggest changing the title of this issue to update the docs on the website.

**Comment by jamesdbloom** [comment]
now fixed
