### ISSUE TITLE
Documentation: ClientAndProxy not available anymore

### ISSUE THREAD

**Issue by mmichaelis** [jamesdbloom/mockserver#511]
The usage documentation for [_Running Mock Server_  via Java API](http://www.mock-server.com/mock_server/running_mock_server.html#client_api) states to use

```java
import static org.mockserver.integration.ClientAndProxy.startClientAndProxy;
import static org.mockserver.integration.ClientAndServer.startClientAndServer;
```

Unfortunately `ClientAndProxy` is only available in 5.3.0 as it seems but not 5.4.1.

And updated usage example would be nice.

**Comment by Vampire** [comment]
I'd say this is basically a duplicate of #508 as the base issue is, that the docs are for 5.3.0 and are outdated.
Server and Proxy were unified into only Server.

**Comment by jamesdbloom** [comment]
now fixed
