### ISSUE TITLE
Do not pollute working directory with temporary files

### ISSUE THREAD

**Issue by Vampire** [jamesdbloom/mockserver#518]
Various files like `MockServerCertificate.pem`, `MockServerPublicKey.pem` and `MockServerPrivateKey.pem` are created in the working directory.
They are meant to be deleted on VM exit, but sometimes this does not work, e. g. if the OS has a lock on the files or if the VM closes unexpectedly.
Please do not create those files in the working directory, but in the temporary directory instead where they do not disturb anything if they cannot be deleted.

**Comment by jamesdbloom** [comment]
This is now fixed
