### ISSUE TITLE
SOCKS4 / SOCKS4a not supported

### ISSUE THREAD

**Issue by Vampire** [jamesdbloom/mockserver#528]
The port unification handler recognizes SOCKS4 and SOCKS5. Unfortunately the actual handlers later on only support SOCKS5 currently. Would be nice if SOCKS4 / SOCKS4a would also be fully supported to use it for testing.

**Comment by Vampire** [comment]
Actually also the port unification handler is wrong.
If version is either SOCKS4 or SOCKS5 it then tries to read the number of auth methods and then the auth methods while this is only the SOCKS5 protocol, not the SOCKS4 protocol.

**Comment by jamesdbloom** [comment]
fixed in merged PR
