### ISSUE TITLE
Support for SOCKS5 authentication

### ISSUE THREAD

**Issue by Vampire** [jamesdbloom/mockserver#529]
SOCKS5 is capable of doing authentication.

Would be nice if you could also support this.

Actually currently you always answer the initial SOCKS5 requests with an auth method of `00`, meaning no auth, even if `00` was not in the list sent by the client for the server to pick from which is also not according to RFC 1928.

So there are actually two issues. 1. an auth method that was not in the list from the client should not be sent back as selected method. 2. supporting authentication would be nice, at least username / password, while the RFC demands `Compliant implementations MUST support GSSAPI and SHOULD support USERNAME/PASSWORD authentication methods.`

**Comment by jamesdbloom** [comment]
fixed in merged PR
