### ISSUE TITLE
MockServerClient v 5.3.0 - httpResponse headers 'Content-Type' not getting set 

### ISSUE THREAD

**Issue by jfbourner** [jamesdbloom/mockserver#530]
Hi, 

I have an issue when trying to set the http response headers and in particular the Content-Type. 
My aim to to set the response content type to text/xml, however it always defaults to application/json. 

At first I tired the below code. Then I realised it needed to be an array so I added the headers object into an array, but this just added by my content-type and the default. 

.mockAnyResponse({
    "httpRequest": {
      "method": "POST",
      "path": "/view/cart"
    },
    "httpResponse": {
      "statusCode": 200,
      "headers": {
            "content-type": ["text/xml"]
        },
      "body": "some_response_body"
    }
  })

**Comment by jamesdbloom** [comment]
This has now been fixed and is not reproducibly in 5.4.1
