### ISSUE TITLE
PortUnificationHandler only works properly on fast / reliable connections

### ISSUE THREAD

**Issue by Vampire** [jamesdbloom/mockserver#531]
Currently `PortUnificationHandler#channelRead0` checks whether there are three readable bytes and then kicks off the evaluation which protocol is being used.

If no protocol can be identified the connection is closed.

But if there are less than three bytes, it just returns.

This means, for example this:

- `PU` is sent
- handler returns
- `T` is sent
- handler returns
- `PUT\n` is sent
- handler recognizes HTTP, configures the pipeline and continues

So actually the inputstream had `PUTPUT\n`, which was recognized and handled as if the first three bytes didn't exist.

So currently leading bytes may be ignored and thus requests answered incorrectly.
And additionally requests might not be recognized correctly and thus are either ignored or aborted while they would have been perfectly valid.

As far as I have understood it, the `PortUnificationHandler` must change to be statefull and collect the bytes until it can either clearly identify the protocol or clearly discard the request.

It would probably be easy to collect the bytes in a `ByteBuf` that can then be redispatched with a `fireChannelRead` after one of the `isXXX` methods recognized the protocol or after all `isXXX` methods gave up (`isSsl` e. g. needs at least `5` bytes to do its work.

But I might not be able to contribute this, as I'm not too familiar with netty and how you properly make this stateful.

**Comment by jamesdbloom** [comment]
fixed in merged PR
