### ISSUE TITLE
xmlSchemaFromResource and xmlSchema do not support XSD which imports other XSD files

### ISSUE THREAD

**Issue by jackiehamchen** [jamesdbloom/mockserver#534]
mockServerClient.when(
                HttpRequest.request()
                        .withMethod("POST")
                        .withBody(
                                xmlSchemaFromResource(<the path to the xsd file in the resource>)
                        )

Compilation fails while reading XSD using both methods because the XSD imports other name spaces like below:

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns
**<xs:import namespace=
<xs:import namespace=**

XmlSchemaValidator needs to be enhanced to support as follows:

Source schemaFile = new StreamSource(new File(JAXB.class
                        .getClassLoader().getResource(xsdFile.getName())
                        .toURI()));

NOTE JAXB.class is the java class resulted from converting XSD schema.

The existing API only works with XSD which does NOT import other namespaces (other XSD files).

**Comment by jamesdbloom** [comment]
this is now fixed and will available be in the next release or the SNAPSHOT version
