### ISSUE TITLE
Support Java 9 modules

### ISSUE THREAD

**Issue by andredasilvapinto** [jamesdbloom/mockserver#538]
Mock-server heavily relies on having the same packages being defined in different modules (e.g. mockserver-core and mockserver-netty). With Java 9 modules it is no longer allowed to read the same package from multiple modules.

**Comment by jamesdbloom** [comment]
This is definitely something that could be done in the future, once I have fixed some recent bugs and have upgraded to Java 8.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/PFv7YhTq/27-java-9-modules
