### ISSUE TITLE
JsTemplate: Expectation with headers are not working

### ISSUE THREAD

**Issue by bgvotes** [jamesdbloom/mockserver#541]
Create a JsTemplate expectation with header as below

PUT http://XXX:1080/expectation

	{
	  "httpRequest" : {
	    "path" : "/date"
	  },
	  "times" : {
	  	"remainingTimes" : 100,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	  	
	    "unlimited" : true
	  },
	  "httpResponseTemplate" : {
	    "templateType" : "JAVASCRIPT",
	    "template" : "var today = new Date();var dd = today.getDate();var str= 'val1,val2';var upStr=str.replace(/val/g,'srihari');var mm = today.getMonth()+1; return { 'statusCode': 200, 'headers': [{ 'Date' : Date() }], 'body': JSON.stringify(   { method: dd+'/'+mm,'test':upStr} ) }"
	  }
	}

Hit the created expectation 

GET http://slc14vny:1080/date

Reponse has only body and status of 200. But, its missing header 'Date'.

**Comment by bgvotes** [comment]
When tried with expectation = 	{
	  "httpRequest" : {
	    "path" : "/date"
	  },
	  "times" : {
	  	"remainingTimes" : 100,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	  	
	    "unlimited" : true
	  },
	  "httpResponseTemplate" : {
	    "templateType" : "JAVASCRIPT",
	    "template" : "var today = new Date();var dd = today.getDate();var str= 'val1,val2';var upStr=str.replace(/val/g,'srihari');var mm = today.getMonth()+1; return { 'statusCode': 200, 'headers': { 'Date' : Date() }, 'body': JSON.stringify(   { method: dd+'/'+mm,'test':upStr} ) }"
	  }
	}
, request exists with log as 2018-10-08 13:20:02,729 INFO o.m.m.HttpStateHandler creating expectation:

	{
	  "httpRequest" : {
	    "path" : "/date"
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponseTemplate" : {
	    "templateType" : "JAVASCRIPT",
	    "template" : "var today = new Date();var dd = today.getDate();var str= 'val1,val2';var upStr=str.replace(/val/g,'srihari');var mm = today.getMonth()+1; return { 'statusCode': 200, 'headers': { 'Date' : Date() }, 'body': JSON.stringify(   { method: dd+'/'+mm,'test':upStr} ) }"
	  }
	}

2018-10-08 13:20:06,158 INFO o.m.m.HttpStateHandler request:

	{
	  "method" : "GET",
	  "path" : "/date",
	  "headers" : {
	    "content-length" : [ "0" ],
	    "Cache-Control" : [ "no-cache" ],
	    "Accept" : [ "*/*" ],
	    "Connection" : [ "keep-alive" ],
	    "User-Agent" : [ "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" ],
	    "Host" : [ "slc14vny:1080" ],
	    "Postman-Token" : [ "2585ed30-fa2e-71ee-085e-2b6149fc5d4d" ],
	    "Accept-Encoding" : [ "gzip, deflate" ],
	    "Accept-Language" : [ "en-US,en;q=0.9" ],
	    "Content-Type" : [ "application/json" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}

 matched expectation:

	{
	  "path" : "/date"
	}

2018-10-08 13:20:06,184 INFO o.m.m.HttpStateHandler Generated output:

	{
	  "statusCode": 200,
	  "headers": {
	    "Date": "Mon Oct 08 2018 13:20:06 GMT-0700 (PDT)"
	  },
	  "body": "{\"method\":\"8/10\",\"test\":\"srihari1,srihari2\"}"
	}

 from template:

	function handle(request) {
	
		var today = new Date();var dd = today.getDate();var str= 'val1,val2';var upStr=str.replace(/val/g,'srihari');var mm = today.getMonth()+1; return { 'statusCode': 200, 'headers': { 'Date' : Date() }, 'body': JSON.stringify(   { method: dd+'/'+mm,'test':upStr} ) }
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/date",
	  "headers" : {
	    "content-length" : [ "0" ],
	    "Cache-Control" : [ "no-cache" ],
	    "Accept" : [ "*/*" ],
	    "Connection" : [ "keep-alive" ],
	    "User-Agent" : [ "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" ],
	    "Host" : [ "slc14vny:1080" ],
	    "Postman-Token" : [ "2585ed30-fa2e-71ee-085e-2b6149fc5d4d" ],
	    "Accept-Encoding" : [ "gzip, deflate" ],
	    "Accept-Language" : [ "en-US,en;q=0.9" ],
	    "Content-Type" : [ "application/json" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}

2018-10-08 13:20:06,200 ERROR o.m.m.HttpStateHandler Validation failed:

	1 error:
	 - for field "/headers" only one of the following example formats is allowed: 
	
	    "/headers" : {
	        "exampleHeaderName" : [ "exampleHeaderValue" ]
	        "exampleMultiValuedHeaderName" : [ "exampleHeaderValueOne", "exampleHeaderValueTwo" ]
	    }
	
	   or:
	
	    "/headers" : [
	        {
	            "name" : "exampleHeaderName",
	            "values" : [ "exampleHeaderValue" ]
	        },
	        {
	            "name" : "exampleMultiValuedHeaderName",
	            "values" : [ "exampleHeaderValueOne", "exampleHeaderValueTwo" ]
	        }
	    ]
for:

	{
	  "statusCode": 200,
	  "headers": {
	    "Date": "Mon Oct 08 2018 13:20:06 GMT-0700 (PDT)"
	  },
	  "body": "{\"method\":\"8/10\",\"test\":\"srihari1,srihari2\"}"
	}
against schema:

	{
	  "title" : "response to return",
	  "type" : "object",
	  "additionalProperties" : false,
	  "properties" : {
	    "body" : {
	      "$ref" : "#/definitions/bodyWithContentType"
	    },
	    "delay" : {
	      "$ref" : "#/definitions/delay"
	    },
	    "cookies" : {
	      "$ref" : "#/definitions/keyToValue"
	    },
	    "connectionOptions" : {
	      "$ref" : "#/definitions/connectionOptions"
	    },
	    "headers" : {
	      "$ref" : "#/definitions/keyToMultiValue"
	    },
	    "statusCode" : {
	      "type" : "integer"
	    },
	    "reasonPhrase" : {
	      "type" : "string"
	    }
	  },
	  "definitions" : {
	    "bodyWithContentType" : {
	      "title" : "response body",
	      "oneOf" : [ {
	        "type" : "object",
	        "additionalProperties" : false,
	        "properties" : {
	          "not" : {
	            "type" : "boolean"
	          },
	          "type" : {
	            "enum" : [ "BINARY" ]
	          },
	          "base64Bytes" : {
	            "type" : "string"
	          },
	          "contentType" : {
	            "type" : "string"
	          }
	        }
	      }, {
	        "type" : "object",
	        "additionalProperties" : false,
	        "properties" : {
	          "not" : {
	            "type" : "boolean"
	          },
	          "type" : {
	            "enum" : [ "JSON" ]
	          },
	          "json" : {
	            "type" : "string"
	          },
	          "contentType" : {
	            "type" : "string"
	          },
	          "matchType" : {
	            "enum" : [ "STRICT", "ONLY_MATCHING_FIELDS" ]
	          }
	        }
	      }, {
	        "type" : "object",
	        "additionalProperties" : false,
	        "properties" : {
	          "not" : {
	            "type" : "boolean"
	          },
	          "type" : {
	            "enum" : [ "PARAMETERS" ]
	          },
	          "parameters" : {
	            "$ref" : "#/definitions/keyToMultiValue"
	          }
	        }
	      }, {
	        "type" : "object",
	        "additionalProperties" : false,
	        "properties" : {
	          "not" : {
	            "type" : "boolean"
	          },
	          "type" : {
	            "enum" : [ "STRING" ]
	          },
	          "string" : {
	            "type" : "string"
	          },
	          "contentType" : {
	            "type" : "string"
	          }
	        }
	      }, {
	        "type" : "object",
	        "additionalProperties" : false,
	        "properties" : {
	          "not" : {
	            "type" : "boolean"
	          },
	          "type" : {
	            "enum" : [ "XML" ]
	          },
	          "xml" : {
	            "type" : "string"
	          },
	          "contentType" : {
	            "type" : "string"
	          }
	        }
	      }, {
	        "type" : "string"
	      } ]
	    },
	    "delay" : {
	      "title" : "response delay",
	      "type" : "object",
	      "additionalProperties" : false,
	      "properties" : {
	        "timeUnit" : {
	          "type" : "string"
	        },
	        "value" : {
	          "type" : "integer"
	        }
	      }
	    },
	    "connectionOptions" : {
	      "title" : "connection options",
	      "type" : "object",
	      "additionalProperties" : false,
	      "properties" : {
	        "closeSocket" : {
	          "type" : "boolean"
	        },
	        "contentLengthHeaderOverride" : {
	          "type" : "integer"
	        },
	        "suppressContentLengthHeader" : {
	          "type" : "boolean"
	        },
	        "suppressConnectionHeader" : {
	          "type" : "boolean"
	        },
	        "keepAliveOverride" : {
	          "type" : "boolean"
	        }
	      }
	    },
	    "keyToMultiValue" : {
	      "oneOf" : [ {
	        "type" : "array",
	        "additionalProperties" : false,
	        "items" : {
	          "type" : "object",
	          "properties" : {
	            "name" : {
	              "type" : "string"
	            },
	            "values" : {
	              "type" : "array",
	              "items" : {
	                "type" : "string"
	              }
	            }
	          }
	        }
	      }, {
	        "type" : "object",
	        "additionalProperties" : false,
	        "patternProperties" : {
	          "^\\S+$" : {
	            "type" : "array",
	            "items" : {
	              "type" : "string"
	            }
	          }
	        }
	      } ]
	    },
	    "keyToValue" : {
	      "oneOf" : [ {
	        "type" : "array",
	        "additionalProperties" : false,
	        "items" : {
	          "type" : "object",
	          "properties" : {
	            "name" : {
	              "type" : "string"
	            },
	            "value" : {
	              "type" : "string"
	            }
	          }
	        }
	      }, {
	        "type" : "object",
	        "additionalProperties" : false,
	        "patternProperties" : {
	          "^\\S+$" : {
	            "type" : "string"
	          }
	        }
	      } ]
	    }
	  }
	}

2018-10-08 13:20:06,202 INFO o.m.m.HttpStateHandler returning response:

	{
	  "statusCode" : 404,
	  "reasonPhrase" : "Not Found",
	  "headers" : {
	    "connection" : [ "keep-alive" ]
	  }
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/date",
	  "headers" : {
	    "content-length" : [ "0" ],
	    "Cache-Control" : [ "no-cache" ],
	    "Accept" : [ "*/*" ],
	    "Connection" : [ "keep-alive" ],
	    "User-Agent" : [ "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" ],
	    "Host" : [ "slc14vny:1080" ],
	    "Postman-Token" : [ "2585ed30-fa2e-71ee-085e-2b6149fc5d4d" ],
	    "Accept-Encoding" : [ "gzip, deflate" ],
	    "Accept-Language" : [ "en-US,en;q=0.9" ],
	    "Content-Type" : [ "application/json" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}

 for templated response action:

	{
	  "templateType" : "JAVASCRIPT",
	  "template" : "var today = new Date();var dd = today.getDate();var str= 'val1,val2';var upStr=str.replace(/val/g,'srihari');var mm = today.getMonth()+1; return { 'statusCode': 200, 'headers': { 'Date' : Date() }, 'body': JSON.stringify(   { method: dd+'/'+mm,'test':upStr} ) }"
	}

**Comment by jamesdbloom** [comment]
The template is not generating a valid format for the Date headers and thus it is ignored.  Unfortunately there was a bug in the validation so this error in headers was ignored and there was no validation error returned that would have helped you understand the header format was incorrect.  I have now fixed that so the following appears in the logs:

```javascript
23:48:42.104 [nioEventLoopGroup-3-2] ERROR org.mockserver.mock.HttpStateHandler - validation failed:

	1 error:
	 - for field "/headers" only one of the following example formats is allowed: 
	
	    "/headers" : {
	        "exampleHeaderName" : [ "exampleHeaderValue" ]
	        "exampleMultiValuedHeaderName" : [ "exampleHeaderValueOne", "exampleHeaderValueTwo" ]
	    }
	
	   or:
	
	    "/headers" : [
	        {
	            "name" : "exampleHeaderName",
	            "values" : [ "exampleHeaderValue" ]
	        },
	        {
	            "name" : "exampleMultiValuedHeaderName",
	            "values" : [ "exampleHeaderValueOne", "exampleHeaderValueTwo" ]
	        }
	    ]

 httpResponseDTO:

	{
	  "statusCode": 200,
	  "headers": [
	    {
	      "Date": "Sun Nov 11 2018 23:47:15 GMT+0000 (GMT)"
	    }
	  ],
	  "body": "{\"method\":\"11/11\",\"test\":\"srihari1,srihari2\"}"
	}
```

You need to generate output as follows, because the header value is an array:

```javascript
{
  "statusCode": 200,
  "headers": {
    "Date": ["Mon Oct 08 2018 13:20:06 GMT-0700 (PDT)"]
  },
  "body": "{\"method\":\"8/10\",\"test\":\"srihari1,srihari2\"}"
}
```
