### ISSUE TITLE
Expose UDP Port

### ISSUE THREAD

**Issue by YNedderhoff** [jamesdbloom/mockserver#542]
Is there any way of opening a UDP port instead of a TCP port using https://hub.docker.com/r/jamesdbloom/mockserver/?

**Comment by jamesdbloom** [comment]
Docker is only opening a port and not specifying if this is TCP or UDP.  Currently the Netty code used inside MockServer assume a TCP socket.  It may be possible to also add support for UDP, although wouldn't be trivial, I'm open to the idea. 

Can you please explain your use case more, and why you need UDP over TCP.

**Comment by YNedderhoff** [comment]
I am writing integration tests for a Spring service in a mocked environment using https://github.com/palantir/docker-compose-rule. The service sends metrics to InfluxDB via UDP, and I wanted to verify if metrics are sent as expected. Naturally, these tests are not critical, more a nice to have. For now I've used https://hub.docker.com/r/danielyinanc/udp-server-docker/, just to give it something to talk to so the logs are not full of errors, but I am not verifying anything. 

I'd still be interested in this, thanks for considering it!

**Comment by YNedderhoff** [comment]
On another note: I know you can specify UDP or TCP in a docker-compose file, I've done that using [danielyinanc/udp-server-docker](https://hub.docker.com/r/danielyinanc/udp-server-docker/). I thought you'd expose this in a Dockerfile like

```Dockerfile
EXPOSE 8285:8285/udp
```

based on [what I found on stackoverflow](https://stackoverflow.com/a/27596415), but I haven't tried it yet.

**Comment by jamesdbloom** [comment]
Just changing the docker port exposed to UDP should have any impact because MockServer uses Netty to listen on a TCP port and so any UDP connection wouldn't work.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/MWZ4Y0LO/39-support-udp-in-addition-to-tcp
