### ISSUE TITLE
Support for consuming OpenAPI specs

### ISSUE THREAD

**Issue by GalaxyGorilla** [jamesdbloom/mockserver#550]
Hi @jamesdbloom!

I hope I did not miss something obvious in the documentation but is it possible for the mockserver to consume API specs like swagger or RAML in some way? I have to use the REST interface for configuration and this turned out to be quite tedious using scripted curl commands and of course for larger projects this is quite hard to maintain.

Maybe I just oversee an easy solution here :)

**Comment by jamesdbloom** [comment]
Consuming OpenAPI specs is already on the backlog.  

First MockServer needs to be upgraded to use Java version to 8 (instead of Java 7) so that I can use existing OpenAPI which use Java 8.  Prior to doing this significant change I want to fix a few more bugs and release a last Java 7 version.

**Comment by GalaxyGorilla** [comment]
Ah ok :) 👍

**Comment by jamesdbloom** [comment]
Now the Java version has been upgrade this feature has now become deliverable and has been raised to close to the top of the backlog.

**Comment by jamesdbloom** [comment]
New feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/0QJAJeRw/28-openapi-specs-to-drive-expectations
