### ISSUE TITLE
Mock server port started for a particular port (3030), but while entered this command  "netstat -an " it does not show the list of that port as Listener.  I am using Mockserver version  (5.3.0),  windows : 10, Tried with Firewell off, but still not working, Pragmatically Server started , but not available in the list. I am trying to create Mockserver for Automation Testing using appium(1.7.1) and Eclipse(Oxygen).   

### ISSUE THREAD

**Issue by LucySwain** [jamesdbloom/mockserver#553]
1. What are you trying to do
1. How are you doing that
1. What client are you using
1. Can you provide the code you are using
1. Which version of MockServer are you using
1. What operating system are you using
1. Are you calling a local instance of MockServer or a remote instance of MockServer

_Originally posted by @jamesdbloom in https://github.com/jamesdbloom/mockserver/issues/408#issuecomment-357035224_

**Comment by LucySwain** [comment]
@jamesdbloom Please have a look on this, as I am new to Mockserver, so I am struggling, please help me out. I am using ngrok for create the Server.

**Comment by LucySwain** [comment]
public class StartMockServer {
	
	
   private final AppiumDriver<MobileElement> appiumDriver = PorterDriver.getInstance().getAppiumDriver();

	private ClientAndServer mockServer;
	
	HttpRequest hr = new  HttpRequest(); 
	HttpResponse hr1 = new HttpResponse();	
			
	   /* @BeforeClass
	    public void startMockServer() {
	        mockServer = ClientAndServer.startClientAndServer(3000);
	        
	        }*/
	    
	        @Test
	        private void server()
	        {
	        	System.out.println(this.appiumDriver);
	    	    mockServer = ClientAndServer.startClientAndServer(3030);
	    	}
This is my code to start mock server. anything else you want please reply me.

**Comment by jamesdbloom** [comment]
It sounds like a problem with Windows.  Can you try running MockServer will TRACE level logging on and using version 5.4.1.  Please attach the log output so I can confirm the logs look normal.

**Comment by jamesdbloom** [comment]
Clicked close by mistake.

**Comment by jamesdbloom** [comment]
Please provide re-open issue when requested information is provided
