### ISSUE TITLE
Java documentation: Referenced callback() method does not exist on ForwardChainExpectation

### ISSUE THREAD

**Issue by berniegp** [jamesdbloom/mockserver#558]
Most (all?) documentation examples for response callbacks use the `ForwardChainExpectation#callback` method which does not exist. From what I can see, this method has been replaced by a `respond()` overload starting in fb7f1796122a235d349bdd9caa83ae11e696f4cf.

See for instance:

	new MockServerClient("localhost", 1080)
		.when(
			request()
				.withPath("/some/path")
		)
		.callback(
			request -> {
				if (request.getMethod().getValue().equals("POST")) {
					return response()
						.withStatusCode(ACCEPTED_202.code())
						.withHeaders(
							header("x-object-callback", "test_object_callback_header")
						)
						.withBody("an_object_callback_response");
				} else {
					return notFoundResponse();
				}
			}
		);

**Comment by jamesdbloom** [comment]
Which version of the document are you looking at.  Can you please send me a link to the page because this has already been updated.

**Comment by berniegp** [comment]
I copy-pasted that from a page on mock-server.com. This is very strange, but I can't find that example anymore! I looked at my whole browsing history and did not find the version using `calback()`. I remember it came from your site and the example had both java 7 and 8 versions (using lamba).

The closest I could find is http://www.mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback

I guess this can be closed then.

**Comment by jamesdbloom** [comment]
Maybe I updated the documentation since you copied the code.  I certainly fixed some out of date documentation recently.
