### ISSUE TITLE
Body matcher doesn't work with ISO-8859-1 Charset

### ISSUE THREAD

**Issue by aulea** [jamesdbloom/mockserver#559]
When using value type of Body matcher and request content type is ISO-8859-1 then matching fails.

Its because:
1) [MockServerRequestDecoder](https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/server/netty/codec/MockServerRequestDecoder.java#L109-L110) will remove charset description from body, when its default HTTP charset - ISO-8859-1
2) In [HttpRequestMatcher#bodyMatches](https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/matchers/HttpRequestMatcher.java#L225) method will prepare value from raw byte array with given default charset UTF-8. It will use default, cause in 1) the charset is removed.

Now here are several possible solutions, ex. to use in 2) also default HTTP charset or in 1) not to nullify detected charset.
I changed my expectation to compare body with full BinaryBody, but i would like to use Xpath assertion.

Another thing, tried to change myself and to create pull-request. But cause I have Windows environment, then tests are failing cause of linebreaks. Here are eveywhere used OS dependent linebreaks, but from some third party libraries (like Jackson XML is using unix style linebreaks) and some tests are comparing returned messages and they are not valid cause of different linebreaks

**Comment by jamesdbloom** [comment]
Are you aware if there is a way to override Jackson to use OS dependent linebreaks?

**Comment by aulea** [comment]
[JsonParserException#getMessage()](https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/JsonParseException.java#L107)
using unix style '\n'. Maybe its just enough to handle linebreaks here in tests differently for Jackson and that's it. But i could myself come back not before December.

**Comment by jamesdbloom** [comment]
It doesn't make sense to me what is not working with a body matcher and ISO-8859-1 charset.  I have many tests that already confirm this works correctly.  These tests also pass on a windows machine.  I need more information to understand what specific problem you are having.

**Comment by aulea** [comment]
did quick pull-request with test simulating the issue "BodyMatcher encoding issue test"

**Comment by jamesdbloom** [comment]
Thank you for the reproducer you where correct about the charsets.  

I have fixed the issue by now and have cleaned up some of the duplicated code around handling charsets.
