### ISSUE TITLE
Programatically quieting logging to std* MKII

### ISSUE THREAD

**Issue by MrCreosote** [jamesdbloom/mockserver#561]
This is a followup to #318.

I recently (finally) upgraded from mockserver 3.X to 5.X and found that the previous means of quieting the logger from #318 no longer worked. It seems like this works: 

```
((ch.qos.logback.classic.Logger) org.slf4j.LoggerFactory
    .getLogger("org.mockserver.mock"))
    .setLevel(ch.qos.logback.classic.Level.OFF);
```

Just shutting off `org.mockserver` does not work in my hands, which is not what I would expect. Is this expected behavior?

Once again, mockserver is the best thing since some invention or other that was extremely useful and helpful.

**Comment by jamesdbloom** [comment]
I suspect the issue is that the package structure was refactored.  You can use the approach you have mentioned or one of the following configuration system properties:
```java
-Dmockserver.logLevel
-Dmockserver.disableRequestAudit
-Dmockserver.disableSystemOut
```
You can also use the `ConfigurationProperties` class which has the following methods (which set the same values):
```java
ConfigurationProperties.logLevel(String level);
ConfigurationProperties.disableRequestAudit(boolean disableRequestAudit);
ConfigurationProperties.disableSystemOut(boolean disableSystemOut);
```
