### ISSUE TITLE
Multiple Query String parameter in single request path not working

### ISSUE THREAD

**Issue by carburra** [jamesdbloom/mockserver#564]
Multiple Query String parameter in single request path is not working for me. Code looks like below:

`when(
                        request()
                                .withMethod("GET")
                                .withHeader("Accept", "application/json, text/plain, */*")
                                .withPath("/URL/")
                                .withQueryStringParameter("QueryParam", "fromdate=2018-11-08T02:00:00.000Z&todate=2018-11-08T02:30:00.000Z")`

QueryParam is not working with the date range. I tried withQueryStringParameters as well but it dint work. Please suggest solution to this.

**Comment by jamesdbloom** [comment]
That is not legal syntax your code should looks like the following:

```java
when(
   request()
      .withMethod("GET")
      .withHeader("Accept", "application/json, text/plain, */*")
      .withPath("/URL/")
      .withQueryStringParameter("fromdate", "2018-11-08T02:00:00.000Z")
      .withQueryStringParameter("todate", "2018-11-08T02:30:00.000Z")
)
```

or:

```java
when(
   request()
      .withMethod("GET")
      .withHeader("Accept", "application/json, text/plain, */*")
      .withPath("/URL/")
      .withQueryStringParameters(
         param("fromdate", "2018-11-08T02:00:00.000Z"),
         param("todate", "2018-11-08T02:30:00.000Z")
      )
)
```
