### ISSUE TITLE
How to log simple requests

### ISSUE THREAD

**Issue by herman-rogers** [jamesdbloom/mockserver#568]
Basically when I send requests to mock-server I would like to be able to have a debug.log from javascript for each request. I just simply want to see if my requests are being sent there or to a different API for debugging purposes.

I've tried to use `retrieveRecordedRequests `, `retrieveRecordedExpectations`, etc but seems to do nothing except log when the initial expectation is created. I've also tried to chain `retrieveRecordedRequests` with `mockAnyResponse` but I'm not sure if this is possible either. Chaining seems to break the expectation endpoint and it never gets created.

Essentially the documentation on how to do this is pretty fuzzy and I don't even know if its possible at this point. Nor do I know how to properly chain these promises together or, in fact, that's how this API is intended to be used.

**Comment by jamesdbloom** [comment]
To log your requests please see the following sections in the documentation that should provide you with the information you need on how to output the requests that MockServer has received.

The first section shows how to do this programmatically:

http://mock-server.com/mock_server/debugging_issues.html#button_retrieve_recorded_reqs_as_json

The second section shows how to do output logs to the console:

http://mock-server.com/mock_server/debugging_issues.html#logging-with-node
