### ISSUE TITLE
Forward exact request in https is not working

### ISSUE THREAD

**Issue by PrasadJayakumar** [jamesdbloom/mockserver#569]
**Usecase:**  I want to record and replay REST APIs of a SaaS application to cut-down the dependency and automate testing of my components.  

**Information about backend REST API:**
GET https://somecloud.com/services/rest/tasks/5
Authorization: Basic xyz

Please verify if I am doing correctly. I tried two options, both ended up in error.  Appreciate your help.

**Option 1:**  Started mock server from command line 
java -jar .\mockserver-netty-5.5.0-jar-with-dependencies.jar -serverPort 1080 -logLevel INFO -proxyRemotePort 443 -proxyRemoteHost somecloud.com

**Test run using**
GET http://localhost:1080/services/rest/tasks/5
Authorization: Basic xyz

**Result:** 
2018-12-05 17:19:44,510 ERROR o.m.m.HttpStateHandler org.mockserver.client.netty.SocketConnectionException: Channel closed before valid response has been received
java.util.concurrent.ExecutionException: org.mockserver.client.netty.SocketConnectionException: Channel closed before valid response has been received

**Option 2:** Started mock server from command line 
java -jar .\mockserver-netty-5.5.0-jar-with-dependencies.jar -serverPort 1080 -logLevel INFO

**Created an expectation with httpForward**
curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
    "httpRequest": {
        "path": "/services/rest/tasks/5"
    },
    "httpForward": {
        "host": "somecloud.com",
        "port": 443,
        "scheme": "HTTPS"
    }
}'

**Test run using**
GET http://localhost:1080/services/rest/tasks/5
Authorization: Basic xyz

**Result:** 
HTTP/1.1 400 Bad Request
Content-Length: 0
access-control-allow-origin: *
access-control-allow-methods: CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE
access-control-allow-headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization
access-control-expose-headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization
access-control-max-age: 300
connection: keep-alive

**Comment by PrasadJayakumar** [comment]
Thanks for your time.  I will check and upload additional log information.  

To continue our project work, we have created a small external proxy to circumvent the issue.  For now, we are using express-http-proxy module and continue to record-and-reply with your mockserver

external-proxy to convert https calls to plain http calls
`
const express = require('express');
const proxy = require('express-http-proxy');

// Custom Modules
const {
    proxy: proxyConfig,
    backendserver: backendserverConfig
} = require('./config');

const app = express();

app.use('/', proxy(`${backendserverConfig.url}`, { https: true }));
app.listen(proxyConfig.port);
`

**Comment by jamesdbloom** [comment]
I am closing this issue but please provide your logs when you have them and I can re-open the issue

**Comment by vishrantgupta** [comment]
I know it's a late response, but I came across the same issue recently, but it was not the mockserver issue but the URL that I was providing. @PrasadJayakumar check if you have provided a valid `host` to the mockserver.
