### ISSUE TITLE
Setting cookie while mocking response

### ISSUE THREAD

**Issue by shashank-g172** [jamesdbloom/mockserver#573]
Hello, 

 I'm attempting to create a really simple mock server which sets cookies when I have specific text in my POST body. When I try to create out the response, the cookie isn't being set. Am I wrong in thinking that the cookies will be set on the browser? 

Here's my code:

private static ClientAndServer mockServer;
  final static Logger logger = LoggerFactory.getLogger(MockAuthServer.class);
  
    public static void main( String[] args )
    {
      logger.info("Mock server started");
        mockServer.startClientAndServer(1080);
        createPostExpectation();
    }

    public static  void createPostExpectation() {
      logger.info("Mock server created expectation at /authenticate");
      new MockServerClient("localhost", 1080)
      .when(
          request()
              .withMethod("POST")
              .withPath("/authenticate")
              .withBody("username:user")
      )
      .respond(
          response()
              .withStatusCode(200)
              .withBody("The POST request contained the sequence user. Setting the cookie")
              .withCookie("login", "mockCookie")
      );
    }
    

I'm using the shade plugin to point the class where this code lives, and then running java -jar from within a Docker container. 

When I hit the POST endpoint, I see the response body, but the cookie isn't set. 

If the cookie isn't set in the browser this way, is there a recommended way that I could do that for the duration of the session?

Thanks,
Shashank

**Comment by jamesdbloom** [comment]
I can not reproduce you issue.  I can use MockServer to create a cookie in the browser which is show in the screen shot below from Chrome:

![screenshot 2018-12-23 at 06 00 33](https://user-images.githubusercontent.com/733179/50381191-47aef000-0678-11e9-9de1-5a491aa5614c.png)

I am using the following code, I changed the `POST` to a `GET` to make it simple to hit from Chrome but otherwise I code is identical:

```java
package org.mockserver;

import org.mockserver.integration.ClientAndServer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static java.util.concurrent.TimeUnit.MINUTES;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

/**
 * @author jamesdbloom
 */
public class Bug573 {
    private final static ClientAndServer clientAndServer = ClientAndServer.startClientAndServer(1080);
    private final static Logger logger = LoggerFactory.getLogger(Bug573.class);

    public static void main(String[] args) throws InterruptedException {
        createPostExpectation();
        MINUTES.sleep(10);
    }

    private static void createPostExpectation() {
        logger.info("Mock server created expectation at /authenticate");
        clientAndServer
            .when(
                request()
                    .withPath("/authenticate")
            )
            .respond(
                response()
                    .withStatusCode(200)
                    .withBody("The POST request contained the sequence user. Setting the cookie")
                    .withCookie("login", "mockCookie")
            );
    }
}
```
In addition if I use your exact code with curl I get the following output which shows the correct `set-cookie` header being added:

```bash
$curl -v -k https://localhost:1080/authenticate --data 'username:user'; echo
> POST /authenticate HTTP/1.1
> Host: localhost:1080
> User-Agent: curl/7.61.0
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 200 OK
< connection: keep-alive
< content-length: 64
< set-cookie: login=mockCookie
< 
* Connection #0 to host localhost left intact
The POST request contained the sequence user. Setting the cookie
```

Please provide more information to help me understand what your issue is.

**Comment by shashank-g172** [comment]
Hi James, 

 Thank you for the quick reply. I was using the POSTMAN chrome app to check whether the cookie was being set or not, and it wasn't. When I tried with curl, I see the cookie being set, and the see the cookie being set when I use curl. 

Maybe it's just a POSTMAN thing, I believe the tool is doing the right thing here. 

Thank you for your time, I'll mark this question as answered. 

Thanks,
Shashank
