### ISSUE TITLE
Is support available for stateful mocks?

### ISSUE THREAD

**Issue by nycjoker** [jamesdbloom/mockserver#593]
I would like to create stateful mocks for CRUD testing. Does mockserver have support for such use cases?

**Comment by jamesdbloom** [comment]
I think there are two ways to achieve what you need.
   
# method callbacks (simplest approach)

The easiest way to create stateful mocks is to use method callbacks as shown on the website at: http://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback

This allows you to manage state locally in your test i.e. using local variables and use methods / closures to create dynamic responses to expectations.

# limited matches using `Times` (more complex)

The other approach is to create multiple expectations using the `Times` value to specify the number of times that expectation is matched, as follows: http://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_path_exactly_twice

Although this approach is more complex it would allow you to create expectations that simulate CRUD scenarios, for example, you could mock the follow:
1. GET that returns 404
1. PUT / POST thats creates resource
1. GET that now returns created resource
