### ISSUE TITLE
Respond when request doesn't match

### ISSUE THREAD

**Issue by allnex** [jamesdbloom/mockserver#594]
Hello,

what I need to do to respond another body when the request doesn't match my needs?

For example, lets say `openid_assoc_handle` is `12345`. How can I respond `{"ok":false}`?

Here is my code:

    val mockRequest = mockServer.`when`(
        request()
            .withMethod("POST")
            .withPath("/")
            .withQueryStringParameter("openid_assoc_handle", "1234567890")
            ...
    )

    mockRequest.respond(
        response()
            .withBody("{\"ok\":true}")
    )

Thanks.

**Comment by jamesdbloom** [comment]
Just create multiple expectations, you could also create a more generic expectation that catches request that don't match the more specific expectations.
