### ISSUE TITLE
add support for signing certificate to resolve unknown certificate issues

### ISSUE THREAD

**Issue by jamesdbloom** [jamesdbloom/mockserver#6]
sign auto-generated certificates with MockServer CA Root Certificate so that it is possible to import this into a browser and / or java code to ensure the auto-generated certificates are automatically accepted

**Comment by ganskef** [comment]
I've built it for adamfisk/LittleProxy and I would put it in your KeyStoreFactory too. I'm working on a PR for mockserver.

It initialize a Certificate Authority key store. The exported PEM can be imported into browsers, to accept dynamicly generated certs.

For a preview see https://github.com/ganskef/LittleProxy-mitm/commit/7915bb1b6de92e4a0288ab36d1f0665b8cb83ad2

**Comment by jamesdbloom** [comment]
done
