### ISSUE TITLE
Is it possible to uniquely identify an expectation, so that it can be cleared without using the request matcher?

### ISSUE THREAD

**Issue by kiyanwang** [jamesdbloom/mockserver#602]
We are trying to use MockServer to create some expectations that will return pre-canned responses while we are running some tests, and that part of it works fine. 

The problem we have is that we run many different tests in parallel, and some of these will set up similar expectations. i.e. The expectation might have all the same request properties but for that particular test we'd like to return a different response (the test might be an integration test that makes a series of request to verify a workflow). The difficulty I'm running into is that when you clear expectations you do so based on a request matcher i.e. properties in the request. 

Is there any way to uniquely identify an Expectation, and clear it, that doesn't rely on request properties? If not is this a use case that anyone else might find useful?

**Comment by jamesdbloom** [comment]
The typical approach to this is to inject a test specific header into requests being sent to the mockserver.  This way all expectations for a test can be setup and cleared in complete isolation from other test.  For example if your application under test uses a correlation id for each request this can be used by forcing the correlation id to a know value for the test.  Using such a correlation id is also typically good practise to help with effective logging and distributed tracing.  Please also see: http://mock-server.com/mock_server/running_tests_in_parallel.html

Does this answer your question?

**Comment by kiyanwang** [comment]
@jamesdbloom it does answer the question

In our case the problem is that we can't currently add a correlation-id/test specific header. Because the test itself is an to end test where the service we are mocking isn't called directly from the test itself but as part of a series of things that happen under the hood when a page is loaded.  

We'll need to rethink our strategy, but thank you for the response,
