### ISSUE TITLE
proxyRemotePort, proxyRemoteHost usage in the docker image CMD

### ISSUE THREAD

**Issue by tetanuss** [jamesdbloom/mockserver#603]
We want to use the helm chart for deploying mockserver and also want to use the two properties proxyRemotePort, proxyRemoteHast to set the destination server for forwarding. Is it correct that this is not possible in the current version of the docker image / helm chart combination? We could not find a place where we can set those parameters when using the helm chart. Or have we missed something?

**Comment by jamesdbloom** [comment]
This is not current exposed but I have just committed a fix for this.  This will be available in the next released version of the helm chart.  Or use the helm chart directly from the git repo by checking out the repo.

**Comment by tetanuss** [comment]
TX a lot! We will try it!
