### ISSUE TITLE
any exception in ExpectationResponseCallback.handle results in timeout without any signs

### ISSUE THREAD

**Issue by SandorDobos** [jamesdbloom/mockserver#606]
Hi,

Any exception thrown in callback method will be simply swallowed.
There is a "matched expectation" block in log, but after it there are no signs of errors visible.

Client never gets a response and connection terminates with timeout.

`
public static class GetBalanceResponseCallback implements ExpectationResponseCallback {
        @Override
        public HttpResponse handle(HttpRequest httpRequest) {
            throw new RuntimeException("for example...");
        }
    }
`

I think the reason is the callback is called via `scheduler.submit(...)` without any exception listeners.
I would add at least a `try-catch` block inside each `scheduler.submit(...)` of `ActionHandler` class with a 
`ActionHandler.this.mockServerLogger.error(LogMessageType.EXCEPTION, ...`-like line.

Happy coding! :)
Sandor

ps: version 5.5.1

**Comment by jamesdbloom** [comment]
This is now fixed in the latest SNAPSHOT version http://mock-server.com/where/maven_central.html#sonatype_snapshot and will be in the next release.
