### ISSUE TITLE
Request timeout when using JAVASCRIPT template

### ISSUE THREAD

**Issue by georgewilk01** [jamesdbloom/mockserver#610]
I am attempting to mock response with some values coming in the request.  The idea is to use JAVASCRIPT template to grab a field from the JSON body of the request and return it.  Expectation is created w/o any issues but when I send my request it times out after a long wait.  There are no errors in the logs.  Here is my expectation:

`curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
"httpRequest": {
        "path": "/test",
        "body" : {
            "type" : "JSON"
        }
},
"httpResponseTemplate": {
       "template": "return { statusCode: 200, body: JSON.stringify({id: JSON.parse(request.body).id}) };",
       "templateType": "JAVASCRIPT"
   }
}'`

And here is my request I am trying to mock:

`curl -v -H "Accept: application/json" -H "Content-Type: application/json" -X "POST" "http://localhost:1080/test" -d '{"id": "1234"}'`

Somehow my request content type is being handled as TEXT.  Here is the corresponding log entry showing the incoming request:

`INFO o.m.m.HttpStateHandler request:

        {
          "method" : "POST",
          "path" : "/test",
          "headers" : {
            "Host" : [ "localhost:1080" ],
            "User-Agent" : [ "curl/7.54.0" ],
            "Accept" : [ "application/json" ],
            "Content-Type" : [ "application/json" ],
            "Content-Length" : [ "14" ]
          },
          "keepAlive" : true,
          "secure" : false,
          "body" : {
            "type" : "STRING",
            "string" : "{\"id\": \"1234\"}",
            "contentType" : "text/plain; charset=utf-8"
          }
        }`

**Comment by tetanuss** [comment]
I think you have to return the json object and not JSON.stringify(...). I had the same problem a while ago. Check the logs of the server. As I remember there should be a message - somthing like "must be an object instead of string"

```
return { statusCode: 200, body: {id: JSON.parse(request.body).id} };
```

**Comment by tetanuss** [comment]
I played a bit with your example. stringify is not the problem.

And now i see the problem, too. If you acces the 'string' attribute your remplate works... But this should not be the solution...

**Comment by georgewilk01** [comment]
I received some help on https://gitter.im/jamesdbloom/mockserver to get around this limitation.  Here is a working set including reset, expectation and the request being mocked:

`
curl -X PUT "http://localhost:1080/mockserver/reset" && \
curl -X PUT "http://localhost:1080/mockserver/expectation" -d '{
    "httpRequest": {
        "path": "/test",
        "body" : {
              "type" : "JSON"
        }
    },
    "httpResponseTemplate": {
            "template": "return { statusCode: 200, headers: { Date: [ Date() ] }, body: JSON.stringify({the_received_id: JSON.parse(request.body.string).id}) };",
            "templateType": "JAVASCRIPT"
    }
}' && \
curl "http://localhost:1080/test" -d '{"id": "1234"}'
`

It would be great to get the content-type header recognition fixed so that we can create the expectations w/o using a workaround.

**Comment by beachygreg** [comment]
Would it be possible to not hang when something is wrong with a javascript template?

**Comment by jamesdbloom** [comment]
Yes, I can add some additional error checking and return a failure response and add log events to aid the debugging the issue.  I'll look into this issue and try to resolve what is going on here in the next few days.

**Comment by jamesdbloom** [comment]
This is now fixed, when there is a template rendering failure due to an error in the template a 404 is returned and the error is logged to the event log and to the console (unless console logging is disabled).

The fix is available in the latest SNAPSHOT release http://mock-server.com/where/maven_central.html#sonatype_snapshot or will be available in the next RELEASE.
