### ISSUE TITLE
Is it possible to create expectation for an endpoint with path variables?

### ISSUE THREAD

**Issue by OrlandoHVProg** [jamesdbloom/mockserver#611]
How can I create the expectation for an endpoint with path variables? I did not find any examples in documentation.

**Comment by jamesdbloom** [comment]
This should not be a problem.  If you can tell a little more about your use case I can add some related examples to the website.  In particular how do the path variables vary in relation to each expectation and its response.

**Comment by jamesdbloom** [comment]
I'm closing this as there hasn't been a response to the request for more information.  If this is still a question please open a new issue.
