### ISSUE TITLE
Migrate to Jakarta EE's JAXB

### ISSUE THREAD

**Issue by triceo** [jamesdbloom/mockserver#612]
JAXB was recently moved to the Jakarta EE project and with that came new Maven GAV. Their [new Github](https://github.com/eclipse-ee4j/jaxb-ri) now specifies [the correct way to use their stuff](https://github.com/eclipse-ee4j/jaxb-ri#examples).

Can we please have mockserver migrated to these new GAV coordinates?

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/loRLGpln/35-migrate-to-jakarta-ees-jaxb
