### ISSUE TITLE
Add new configuration property for request queue

### ISSUE THREAD

**Issue by nycjoker** [jamesdbloom/mockserver#614]
MockServer currently supports a property `maxExpectations`. 

It seems this setting is used in 2 places:

1. The maximum active expectation to hold in memory. If the project initialize expectations then they will be added to a queue of the defined maximum size.

2. The request log queue which captures logs, requests, and recorded expectations. This queue is defined with size of `maxExpectations * 2`.

It would be great if a new property can be defined specifically for use case 2. Here is why:

- In my project I have ~500 active expectations that are registered at startup with `maxExpectations` set to 500. During initialization memory space is taken up as these expectation are registered.

- As the MockServer proxy runs and forwards all requests that do not have matching expectations it automatically captures it in memory for record/replay purposes. The size of this queue in my case is a 1000 (500 * 2). 

- In this case, there are a total of 1500 objects in memory.

- If anyone uses the REST API to retrieve recorded expectations or requests the code traverses the request log queue (size 1000) and adds matching requests to an ArrayList. As items are added to the ArrayList memory space temporarily grows. Worst case, in a single thread, you will fetch all 1000 recorded expectations. Although GC will clean up the objects the memory usage will become very high. In a multi-threaded operation of hitting REST API to fetch recordings it will be even higher.

- If a new property is introduced to set the maximum size of the request log queue then behavior can be controlled. For example, if the request log queue max size is set to 0 then nothing will be held in memory for recordings. Yet, the active expectations queue (ones registered at startup) would not be impacted.

Would it be possible to add the new property?

**Comment by jamesdbloom** [comment]
This makes sense I can add this in the new release, likely in the next few weeks.

**Comment by nycjoker** [comment]
@jamesdbloom Any ETA on this enhancement?

**Comment by jamesdbloom** [comment]
I'll do this in the next few days before doing a new release

**Comment by jamesdbloom** [comment]
This is now done, the web site documentation will be updated after the next release likely in the next few days.  In the meantime the code is available via the SNAPSHOT version: http://mock-server.com/where/maven_central.html#sonatype_snapshot

The new property added is called `mockserver.maxLogEntries`
