### ISSUE TITLE
Filter on more than just the request matcher in Dashboard

### ISSUE THREAD

**Issue by tiaankruger** [jamesdbloom/mockserver#616]
The Dashboard is really an amazing tools for developers to see all the data.

And being able to filter it based on the request matcher is quite useful.

I would, however, like to to be able to filter the log messages on more than just the request matcher stuff.
I would like to, for example, be able to only see the requests where the message is 
   

>   "no expectation for:"

I could write my own code to get this (and already did partially, but no front end yet) using something like 
  

>   .includes('no expectation for')   with string being made dinamic for the app

But I think that it would be a useful feature in the Dashboard anyway for all use cases.

We would prefer to stay as close to the master code as possible, and not have it branch off from the main development that you are doing. (ends up being a headache to main with updates, etc).

So I guess my question is this.
Is there a way to filter for something like that that isnt in the request matcher that I am missing?
If there is, how do i use it?
And if there isnt, any plans on including this?

just to have more info in one place, if use retrieveLogMessages messages, we get a bunch of messages.
and the one I am looking to filter for (or multiple of them on the dashboard) looks like this, and I want to filter for the "no expectation for"

> 
> "
> 2019-04-17 11:24:49 - no expectation for:
> 
> 	{
> 	  "method" : "POST",
> 	  "path" : "/1ASIWNXGAML",
> 	  "headers" : {
> 	    "Content-Type" : [ "text/xml; charset=utf-8" ],
> 	    "SOAPAction" : [ "\"http://webservices._somewebservice_.com/_some_more_stuff_\"" ],
> 	    "host" : [ "mockserver:1080" ],
> 	    "accept-encoding" : [ "gzip,deflate" ],
> 	    "content-length" : [ "3534" ],
> 	    "connection" : [ "keep-alive" ],
> 	    "cookie" : [ "TestRunContext=%7b%22ScenarioId%22%3a%22scenario1%22%2c%22TestId%22%3a%22test1%22%2c%22RunId%22%3a%221%22%7d" ]
> 	  },
> 	  "cookies" : {
> 	    "TestRunContext" : "%7b%22ScenarioId%22%3a%22scenario1%22%2c%22TestId%22%3a%22test1%22%2c%22RunId%22%3a%221%22%7d"
> 	  },
> 	  "keepAlive" : true,
> 	  "secure" : false,
> 	  "body" : {
> 	    "type" : "STRING",
> 	    "string" : "**_someDataForOurApplicationHidden_**",
> 	    "contentType" : "text/plain; charset=utf-8"
> 	  }
> 	}
> 
>  returning response:
> 
> 	{
> 	  "statusCode" : 404,
> 	  "reasonPhrase" : "Not Found"
> 	}
> 
> "
>

**Comment by jamesdbloom** [comment]
Yes I agree adding more filters to the dashboard would be a good idea.  I should be able to look into doing this soon (in about a month), although currently I'm just resolving some other issues.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/UNE8i0zh/29-filter-on-more-than-just-the-request-matcher-in-dashboard
