### ISSUE TITLE
Negated matcher not working in httpRequest body

### ISSUE THREAD

**Issue by neXussT** [jamesdbloom/mockserver#617]
Hi,

I need to ignore IP addresses in the 10.x.x.x range, while processing all others. I first tried "^(?!10\.)", which works in Perl, but it doesn't seem to be supported by mock-server. I then tried the negated matcher as shown below, but it doesn't seem to work while using regex in the body. When I send "text '10.0.0.1'" at it, it matches, whether or not the negated matcher is there, and there are no errors when I load the config via mockserver-client (nodejs). It's as if the presence of "'not': true" makes no difference. Am I doing something wrong here? Is negated matching not supported by regex in the body?

`            'httpRequest': {
                'method': 'POST',
                'path': '/',
                'body': {
                    'not': true,
                    'type': "REGEX",
                    'regex': ".*'10\..*"
                }
            },`

**Comment by jamesdbloom** [comment]
There was an issue with double negation which I have now fixed and is available in the latest SNAPSHOT version or will be released in the next few weeks.

In addition for the regex you need to use one of the following two syntaxes:

```json
{
    "httpRequest": {
        "method": "POST", 
        "path": "/notBody", 
        "body": {
            "not": true, 
            "type": "REGEX", 
            "regex": "10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"
        }
    }, 
    "httpResponse": {
        "statusCode": 200
    }, 
    "times": {
        "unlimited": true
    }
}
```

or 

```json
{
    "httpRequest": {
        "method": "POST", 
        "path": "/notBody", 
        "body": {
            "not": true, 
            "type": "REGEX", 
            "regex": "10\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"
        }
    }, 
    "httpResponse": {
        "statusCode": 200
    }, 
    "times": {
        "unlimited": true
    }
}
```

The escaped values need a `\\` because they are being passed inside a JavaScript string value.
