### ISSUE TITLE
Log file not created by default

### ISSUE THREAD

**Issue by Weetbix** [jamesdbloom/mockserver#620]
Based on the docs it seems that by default, mockserver _should_ create a mockserver.log file in the current working directory: http://www.mock-server.com/mock_server/debugging_issues.html#logging-levels

But when I run: 
`java -jar ./mockserver-netty-5.5.1-jar-with-dependencies.jar -serverPort 4000 -logLevel DEBUG`
or: `java -Dmockserver.logLevel=INFO -jar ./mockserver-netty-5.5.1-jar-with-dependencies.jar -serverPort 4000` 

The mockserver.log file never seems to be created. This also extends to `mockserver-node`, which does not produce the log file either. 

I have only been able to produce the log by adding a custom `logback.xml` and passing that on the commandline, but this option does not work for `mockserver-node` as this cmdline option is not configurable.

**Comment by jamesdbloom** [comment]
I have now resolved this issue which is available in the SNAPSHOT version.  I will do a release and update `mockserver-node` within the next week.

**Comment by rrovensky** [comment]
Until now I was using `java -jar ./mockserver-netty-5.6.1-jar-with-dependencies.jar -serverPort 1080`, and the mockserver.log was always created in the current dir. As soon as I switched to the latest version `java -jar ./mockserver-netty-5.7.0-jar-with-dependencies.jar -serverPort 1080`, mockserver.log no more gets created. Perhaps the same bug has re-occured ?

**Comment by jamesdbloom** [comment]
No log file is created any more in the latest version.  If you want to access the log either pipe the output from standard out or use the query REST API to retrieve the log events and other data such as requests received: http://mock-server.com/mock_server/debugging_issues.html
