### ISSUE TITLE
5.5.4 on DockerHub

### ISSUE THREAD

**Issue by YNedderhoff** [jamesdbloom/mockserver#622]
Hey 👋 Thanks for the great work! Quick question: Will you release 5.5.4 to DockerHub? No worries if you don't. Thanks! :)

**Comment by lanwen** [comment]
Seems after breach it was simply disconnected

**Comment by YNedderhoff** [comment]
Ah I see. Will you release it to Dockerhub now or will you only do it again for future versions?

**Comment by jamesdbloom** [comment]
5.5.4 is now release on DockerHub

**Comment by YNedderhoff** [comment]
@jamesdbloom is it possible this is happening again right now?

**Comment by jamesdbloom** [comment]
Yes because the release process is automated due to the incredibly complexity involved in doing this. This is however on the todo list competing with all the other items. This will be updated in the next few days once the remaining half of the release steps have been completed
