### ISSUE TITLE
Allow to exclude/not match on some path(s)

### ISSUE THREAD

**Issue by x80486** [jamesdbloom/mockserver#623]
I'm currently using MockServer (Netty) version `5.5.4` with Spring Boot `2.1.4.RELEASE`. Everything is all right, until I enabled `spring-boot-starter-actuator` :smile:

I basically want to get the output from those endpoints (`/health`, `/info`, etc), but MockServer is trying to match onto those path(s) and I'm currently getting an HTTP `404` (expected, but not desired).

So I wonder if there is a way to exclude/skip some specific path(s), or alternatively to match from a specific root path(s) only (and onward) – something like `/api/*` (and everything else is skipped).

**Comment by jamesdbloom** [comment]
I'm not sure I understand what you problem is?

You can use match paths using a partial match as, see http://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_regex_path.

You can also forward some requests to a real non-mocked service and only mock other requests if you only want to mock specific paths, see http://mock-server.com/mock_server/creating_expectations.html#button_forward_exactly
