### ISSUE TITLE
Verify sequence REST API sample incorrect 

### ISSUE THREAD

**Issue by ronanbarrett** [jamesdbloom/mockserver#624]
Whilst writing our go client for mock-server (https://github.com/sandvikcode/mockserver-client-go) we noted the REST API example for /verifySequence at http://www.mock-server.com/mock_server/verification.html is incorrect. The example should be 
`curl -v -X PUT "http://0.0.0.0:1080/mockserver/verifySequence" -d '{
"httpRequests": [
    {"path": "/some/path/one"},
    {"path": "/some/path/two"},
    {"path": "/some/path/three"}
]}'`

**Comment by jamesdbloom** [comment]
Fixed
