### ISSUE TITLE
MockServer:117 BindException thrown on thread

### ISSUE THREAD

**Issue by CC007** [jamesdbloom/mockserver#628]
When trying to bind a MockServer, when a port is already bound (for instance by another MockServer), An exception is thrown on the main thread (to the caller of `ClientAndServer.startClientAndServer()`), but also on the thread that is created in `MockServer.bindToPorts` (line 117), because of the logger on line 113.

In my case it is often already expected that the port could be bound. The problem is that while I am able to catch the exception on the main thread, I am unable to catch the exception of the thread that is created in `MockServer.bindToPorts`.

I think that the issue could be fixed if line 113 was moved to line 105

**Comment by jamesdbloom** [comment]
Which version of MockServer are you using because the line numbers and method names don't match the current code base.  Can you please try upgrading to the latest version 5.5.4 and check if you still have the same issue.

**Comment by CC007** [comment]
It looks like the log statement was removed in a newer version, but you still catch an exception in `LifeCycle:157` which can't be caught from the main thread. You already seem to have a channelOpened Future, so instead of throwing the exception you could change this to `∆channelOpened.setException(...)` I believe.

**Comment by jamesdbloom** [comment]
I have fixed your issue, I still need to add some test coverage then shortly I will release a new version
