### ISSUE TITLE
Ability to set JVM arguments like Xmx from Maven plugin

### ISSUE THREAD

**Issue by jocull** [jamesdbloom/mockserver#632]
I wasn't able to find a way to limit the memory consumed by MockServer's JVM when started from the Maven plugin. Is there a way to do this? I have a 32GB host and the JVM is quite greedy by default.

Thanks, and I'd be able to open a PR with a suggested fix if needed :smile:

**Comment by jamesdbloom** [comment]
This would make sense for the forked version of the MockServer using `runForked`.  For the none forked version they values provided to maven should apply to MockServer as well.

A PR would be happily welcomed, likely your'll only have to edit MockServerRunForkedMojo and MockServerAbstractMojo.

**Comment by jamesdbloom** [comment]
I am currently adding some logic to the plugin so I will also add a property `jvmOptions` to allow arbitrary options to be specified.

**Comment by jamesdbloom** [comment]
This is now committed to the plugin repo and will be release in the next few days once I have updated the documentation.

An example of how to use this is as follows:

```xml
<plugin>
    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-maven-plugin</artifactId>
    <version>5.5.5-SNAPSHOT</version>
    <configuration>
        <logLevel>DEBUG</logLevel>
        <pipeLogToConsole>true</pipeLogToConsole>
        <serverPort>1080,2080</serverPort>
        <jvmOptions>-Dfoo=bar</jvmOptions>
        <pipeLogToConsole>false</pipeLogToConsole>
    </configuration>
    <executions>
        <execution>
            <id>initialize</id>
            <phase>initialize</phase>
            <goals>
                <goal>runForked</goal>
            </goals>
        </execution>
        <execution>
            <id>pre-integration-test</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>stopForked</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
