### ISSUE TITLE
Healthcheck GET endpoint when running as web server

### ISSUE THREAD

**Issue by pnsantos** [jamesdbloom/mockserver#635]
We run mock server in kubernetes and it's useful to have a readiness/liveness probe configured (i.e. provide a GET endpoint on mock server that returns a 2xx code when mock server is "ready" to serve requests).

I looked through the documentation but wasn't able to find if mock server provides such an endpoint. Right now we are using a static expectation to return 204, however when we do a reset, that also get's cleared which is inconvenient (as we need to keep setting that expectation over and over).

Does mock server have an endpoint to call that provides this functionality? 

If not would it be possible to add one? Say a `GET /health-check` that returns 204 when mock server has been properly initialized (possibly in a different port so that there is no conflict possible with expectations being set?)

**Comment by jamesdbloom** [comment]
Yes I agree this makes sense, this is not currently supported but I can look into adding a second port for the entire control plane.  That way a health check could be easily achieved.

**Comment by scierniak** [comment]
Voting for this issue too, got same issue and same solution with expectation GET /health.

We could transform the PUT /status into GET /status as there is no body to provide for this request

**Comment by ThibaultPatoux** [comment]
+1
Same issue for me and totally agree with @scierniak 
By the way Thank you @jamesdbloom for your work! Really useful.

**Comment by tetanuss** [comment]
+1 we have the same issues with k8s. and solved it the same way with an 'special' expectation. And when ussing this work arround with a 'special' expectation you also get this log entries from the heath checks which are quite often in an k8s environment.

**Comment by scierniak** [comment]
FYI as another workaround, we solved this issue by using a "command" instead of a "httpGet" into readiness/liveness probe:

"exec": {                            
      "command": [
        "/bin/bash",
        "-c",
        "curl -v -X PUT http://localhost:1080/mockserver/status"
      ]
}

Note: this solution does not increase logs

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/11gZo41b/34-healthcheck-get-endpoint

**Comment by jamesdbloom** [comment]
This issue has now been fixed and will be in the next release.
