### ISSUE TITLE
Step 2 missing from "PROXY - HOW? > Getting Started" 

### ISSUE THREAD

**Issue by udev** [jamesdbloom/mockserver#637]
"1. Configure Clients" is immediately followed by "3. Analysing Behaviour"

"2. Run Test Scenarios" appears in the table of contents but there is no link and the section is noticeably absent.

http://www.mock-server.com/proxy/getting_started.html

**Comment by jamesdbloom** [comment]
I can add something to explain as perhaps it is not as clear as I thought, but this section is where a user runs their own test scenarios that they want recorded in the proxy.

**Comment by jamesdbloom** [comment]
I've added a line item to the documentation issue to cover this so closing this issue.
