### ISSUE TITLE
A typo in the docs

### ISSUE THREAD

**Issue by maseev** [jamesdbloom/mockserver#639]
From the documentation [page](https://github.com/jamesdbloom/mockserver/blob/6eb2be27019dacd2ca5878fbfc4a4a633c474366/jekyll-www.mock-server.com/index.html#L28):

> **An** expectation**s** defines the action that is taken, for example, a response could be returned

I guess, it should be:

> **An** expectation defines the action that is taken, for example, a response could be returned

**Comment by jamesdbloom** [comment]
now fixed in code soon this will be deployed the website
