### ISSUE TITLE
Constructor Arguments Out of Order

### ISSUE THREAD

**Issue by aamarill** [jamesdbloom/mockserver#642]
Constructor arguments in sample code are out of order 😅 
See [here](http://www.mock-server.com/mock_server/running_mock_server.html#junit_rule)

From docs (this doesn't work)
```java
public MockServerRule mockServerRule = new MockServerRule(portNumber, this);
```

this works
```java
public MockServerRule mockServerRule = new MockServerRule(this, portNumber);
```

**Comment by jamesdbloom** [comment]
This is now fixed and will be deployed in the next few days when I do the next release.
