### ISSUE TITLE
Authentication on control plane API

### ISSUE THREAD

**Issue by aukevanleeuwen** [jamesdbloom/mockserver#643]
Hello,

First things first: thanks for the effort on this project, really awesome.

I have a question? Is it possible to have the 'instruct' part of mockserver behind some kind of authentication? I want to use the mockserver as part of a let's say `smoke-test` environment where mockserver would be mocking the external (saas) services of this complete landscape. This landscape is running in AWS, where mockserver is running as a Fargate task (or at least that's envisioned for now).

We can quite easily limit the access to the 'replying with mocked responses' phase of the mockserver because the invocations are coming from the landscape itself and we can put some measures in place on the networking level basically. However the 'instruct' part of the mockserver API should be more open, accessible from developers laptops and CI servers etc. However we don't want it to be publicly available either because of insight in the information that people will have when they will for example hit the `PUT "http://x.x.x.x:1080/retrieve"` endpoint or similar. Or any sort of modification they will be able to do that will break our tests and cost us time.

So I was hoping there was some ability to have some kind of authentication on the 'instruct' API of mockserver, but couldn't find it. I had a look [here (java)](https://github.com/jamesdbloom/mockserver/blob/master/mockserver-client-java/src/main/java/org/mockserver/client/MockServerClient.java#L158-L162) and [here (javascript)](https://github.com/jamesdbloom/mockserver-client-node/blob/master/mockServerClient.js#L20-L39) and it does seem to be rather hard-coded. Even adding an `X-API-KEY` header would already be great I guess.

Am I correct that it currently isn't possible?

If I'm correct would it be a suggestion to have the ability to inject your own http client or have some kind of interceptor to be able to add some headers? For the AWS case it would even be quite awesome if we have the ability to read the current url / body / headers so we can do some v4 signature calculation on it.

Thanks,

--
Auke

**Comment by jamesdbloom** [comment]
This is something that hasn't been previously considered but certainly could be added if done in the correct way.  Although I don't like mTLS this may be the simplest solution to put in place.  mTLS is not ideal because its hard to do things like rotation of certificates, etc without a lot of extra effort / complexity and certificate management in place.  However, I suspect rotation of certificates may not be as important in this scenario.  I'm happy to take a look and see if mTLS or an API key based approach are feasible and how long it would take to implement.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/5AncVp5r/33-control-plane-api-authentication
