### ISSUE TITLE
Configure mockserver expectations using json file in Java (programmatically)

### ISSUE THREAD

**Issue by RedRoses1234** [jamesdbloom/mockserver#644]
Hello,

I would like to know if it's possible to configure mockserver with a json file programatically?

This can be done using command line:
`java -Dmockserver.initializationJsonPath="org/mockserver/server/initialize/initializerJson.json" -jar ~/Downloads/mockserver-netty-5.6.0-jar-with-dependencies.jar -serverPort 1080 -logLevel INFO`

Can we load the file programmatically, create Expectations out of it and configure ClientAndServer?

**Comment by jamesdbloom** [comment]
yes for example the following command works on my local machine:

```bash
java -Dmockserver.initializationJsonPath=/Users/jamesbloom/git/mockserver/mockserver/mockserver-core/src/test/resources/org/mockserver/server/initialize/initializerJson.json -jar ~/Downloads/remotecontent.jar -serverPort 1080 -logLevel INFO
```

I have also added an extra log output to make it clearer what expectations have been created by the file initialiser.

**Comment by A4L** [comment]
Hey @jamesdbloom, I might be overlooking something, but how is your example showing how to do it programatically? It's just a command that can be executed from a shell. I was expecting something like:

```
ExpectationSerializer expectationSerializer =
    new ExpectationSerializer(new MockServerLogger(log));

mockServer
    .upsert( // insert or update
        readExpectations(testcase) // read expectations as stream JsonNode(s) 
            .map(this::toString) // serialize parsed node to string (again :( )
            .map(expectationSerializer::deserialize) // deserialize using mockserver's ExpectationSerializer 
            .toArray(Expectation[]::new)); // collect to an array
```
