### ISSUE TITLE
client hangs while making more than one request served by javascript template engine

### ISSUE THREAD

**Issue by yutu3** [jamesdbloom/mockserver#649]
In my use case, there are three GET requests (A,B,C).
A and B are served by Javascript template response. C is served by normal http response.
When the client makes three GET requests simultaneously, client can get stuck because one of the requests (A) does not return response and hangs.  I was able to consistently reproduce the issue. 

Upon further investigating into the code, problem lies at 
https://github.com/jamesdbloom/mockserver/blob/210ec3faa81da319bdfedab94f95d63a46669c98/mockserver-core/src/main/java/org/mockserver/templates/engine/javascript/JavaScriptTemplateEngine.java

I suspect that the following code is not thread-safe. When two threads are executing it simultaneously, one of the threads got stuck and is not able to provide response.

I pulled a copy of source code. After adding synchronized (engine) {...} to following block and rebuilt the jar, the problem completely disappeared.

       ```
     if (engine != null) {
                engine.eval(script + " function serialise(request) { return JSON.stringify(handle(JSON.parse(request)), null, 2); }");
                // HttpResponse handle(HttpRequest httpRequest) - ES5
                Object stringifiedResponse = ((Invocable) engine).invokeFunction("serialise", new HttpRequestTemplateObject(request));
                logFormatter.info(TEMPLATE_GENERATED, request, "generated output:{}from template:{}for request:{}", stringifiedResponse, script, request);
                result = httpTemplateOutputDeserializer.deserializer(request, (String) stringifiedResponse, dtoClass);
} 
```

**Comment by jamesdbloom** [comment]
The ScriptEngine is thread safe but the bindings are not as per the quote below.  Add the synchronised block is not ideal because the performance impact on multiple requests is very high.  However I have ensure that new bindings and script context are created on every request.  I have also added a test which attempts to prove parallel request work, obviously it is not easy to test this with 100% guarantee.

> You can share a ScriptEngine and CompiledScript objects across threads. They are threadsafe. Actually, you should share them, as a single engine instance is a holder for a class cache and for JavaScript objects' hidden classes, so by having only one you cut down on repeated compilation.

> What you can't share is Bindings objects. The bindings object basically corresponds to the JavaScript runtime environment's Global object.

from https://stackoverflow.com/questions/30140103/should-i-use-a-separate-scriptengine-and-compiledscript-instances-per-each-threa/30159424#30159424

**Comment by yutu3** [comment]
@jamesdbloom I am still able to reproduce the hanging problem using the latest build.
Could you please reopen this issue?

**Comment by jamesdbloom** [comment]
Can you please provide an example I can use to reproduce the issue because I am unable to reproduce this.

**Comment by yutu3** [comment]
Did you get a chance to run the examples I provided? I think the problem of hanging is because that wrong javascript template is getting invoked when simultaneous calls are made. 
In my case, call2 and call3 were somehow wrongly invoking call1 template (without the required input parameter), thus hang.

Please let me know if you need further information. Thanks!

**Comment by yutu3** [comment]
@jamesdbloom Please let me know in case you need further info. Appreciate that you look into the issue and see if any portion of binding run into issue, or synchronization issue due to multi-threading. Thanks!

**Comment by yutu3** [comment]
closing this old issue and replaced with a new one https://github.com/jamesdbloom/mockserver/issues/683. Thanks!
