### ISSUE TITLE
Hot loading Initialization Json file

### ISSUE THREAD

**Issue by DavyGarcon** [jamesdbloom/mockserver#653]
Hi James,

I'm using your product since several months yet, and i try to spread the use in my company.
Currently i work with the mockserver-node and a json initialization file. And i wondered if a feature allowing the hot loading of the file (during change on it) could be implemented ?

Again thanks you for your job.

**Comment by jamesdbloom** [comment]
Yes this could make sense and shouldn't be too hard to implement.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/MN3KRvau/32-hot-load-expectation-initialization-file

**Comment by jamesdbloom** [comment]
I am currently working on this and it will be releasing the next few weeks.
