### ISSUE TITLE
Extract response for request

### ISSUE THREAD

**Issue by carbonrider** [jamesdbloom/mockserver#654]
I am using the following API to get the requests

http://localhost:8764/mockserver/retrieve?type=REQUESTS&format=JSON

While it does return an array of requests, I do not see what responses were returned to these requests. I went through the documentation but didn't see any handy options to extract responses for a given request.

Is there any way to get a response for a given request OR does above API accepts any additional argument to return response along with requests?

**Comment by jamesdbloom** [comment]
```bash
curl -v -k -X PUT "https://localhost:1080/mockserver/retrieve?type=logs&format=json"
```

The above command provides you with the requests and response but unfortunately not in a format that was easy to process programmatically.

I can see how this could be useful and I don't think it would be too hard to extend the type options to provide what you need.  I assume you want to see all the requests and their responses in the sequence they were recorded even if there are duplicates.  I will add an extension to implement that but please add an additional comment if you need something slightly different.

**Comment by jamesdbloom** [comment]
I have now added support to retrieve the requests and responses as follows:

```bash
curl -v -k -X PUT "https://localhost:1080/mockserver/retrieve?type=request_responses&format=json"
```

However, I still need to add documentation to the website for this new response type.

**Comment by carbonrider** [comment]
Thats awesome @jamesdbloom I truly appreciate your efforts. I will go through the changes.

**Comment by jamesdbloom** [comment]
I have now updated the documentation (not yet committed) and I am in the process of updating the java and javascript clients.

An example response is:

```javascript
[ {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/path",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "body" : "some_response_body"
  }
}, {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/otherPath",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "body" : "some_response_body"
  }
}, {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/otherPath",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "body" : "some_response_body"
  }
}, {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/otherPath",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "statusCode" : 404,
    "reasonPhrase" : "Not Found"
  }
}, {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/path",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "body" : "some_response_body"
  }
}, {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/path",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "body" : "some_response_body"
  }
}, {
  "httpRequest" : {
    "method" : "GET",
    "path" : "/some/path",
    "headers" : {
      "Host" : [ "localhost:1080" ],
      "User-Agent" : [ "curl/7.64.1" ],
      "Accept" : [ "*/*" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  },
  "timestamp" : "2019-10-27 22:09:23",
  "httpResponse" : {
    "body" : "some_response_body"
  }
} ]
```

**Comment by jamesdbloom** [comment]
This is now completed for all clients and fully implemented

**Comment by ankitkumarit** [comment]
How do i get latest reposnse of an expectation? 
When i set an expecation with existing URL but new response

URL: http://localhost:55001/mockserver/expectation
Body:
{
  "httpRequest" : {
    "method" : "GET",
    "path" : "/member/details"
  },
  "httpResponse" : {
    "body" : "{\"id\": \"Sampleid\",\"status\": \"submitted\",\"result\": \"afterclearpersonaltryit\"}"
  }
}

where as 
http://localhost:55001/member/details

returns old response:
{"id": "Sampleid","status": "submitted","result": "afterclearpersonal"}
