### ISSUE TITLE
Dashboard not working for version 5.6.1

### ISSUE THREAD

**Issue by vvargas90** [jamesdbloom/mockserver#667]
Last version I tried dashboard and was working is 5.5.0. 
When I upgraded everything to version 5.6.1 I couldn't see any request. Filters were all off. 

As an example, for the very same tested scenario what I get with 5.5.0:
![Screen Shot 2019-09-05 at 11 54 09](https://user-images.githubusercontent.com/26199608/64413202-5b2caa80-d091-11e9-93ef-09f2af92717e.png)

And what I see with 5.6.1 version:
![Screen Shot 2019-09-06 at 10 30 56](https://user-images.githubusercontent.com/26199608/64413240-6da6e400-d091-11e9-99a3-7b175a00dff5.png)

**Comment by Graynder** [comment]
Hi @vvargas90, I encountered the same problem as you. I was able to find the solution thanks to this issue (add the certificate) ( see #584 )

**Comment by vvargas90** [comment]
Thanks for your comment @Graynder 🙌
