### ISSUE TITLE
Question about mock encrypted request

### ISSUE THREAD

**Issue by coolxll** [jamesdbloom/mockserver#668]
Hello, I meet a problem with mock server. The problem is that I have a finance service to mock(something like paypal or alipay). Since it is related to money, the request was signed and encrypted.
So before the request the perform the rule I want to decrypt it, to transform it to the plain text and then pass through the rule, which maybe forward or just respond.
If the rule choose to respond, the response need to be encrypted first.
The decrypt and encrypt method can be customized and provide with jar or in class.
But I want to know how to do it with mock server is the best practise, Thank you.

**Comment by jamesdbloom** [comment]
I would suggest the best way to implement this would be to encrypt the request and response bodies .  It won't be possible to encrypt other parts of the request or response, but as the sensitive data is likely in the body this should be acceptable.

If you follow this approach then you can define the expectation using a ClassCallback action as described here: http://mock-server.com/mock_server/getting_started.html#button_response_class_callback.  This would allow you to provide any arbitrary logic to decrypt the body and encrypt a response body.  Given an encrypted body is ciphertext and is binary you can use the `getRawBytes()` of the body to retrieve the `byte[]` for the request body.
