### ISSUE TITLE
Add default expectation (that performs action when no other expectation match)

### ISSUE THREAD

**Issue by kongqueshi** [jamesdbloom/mockserver#671]

**Comment by jamesdbloom** [comment]
yes you just need to create a default forward rule (i.e. one with no conditions for the request) as the last expectation you specify then if no earlier expectations match it'll fall through to that one.

```java
MockServerClient mockServerClient = new MockServerClient("localhost", 1080)
// other expectations ....

// forward all requests to specify host and port
mockServerClient
    .when(
        request()
    )
    .forward(
        forward()
            .withHost("some-host")
            .withPort(443)
    );
```

**Comment by kongqueshi** [comment]
First of all, thank you for your quick response. ：）

Yes, if you expectations to be initialized only once this problem can can be resolved in your way. But in my case, expectations will be updated by user's actions (remov the old expectations and then add the updated expectations). Now the default forward rule is not the last expectation. 

The above content is translated by Google, may be difficult to read ：）

**Comment by jamesdbloom** [comment]
I agree what you said makes sense and should be added as an explicit concept.  I'll look into do that in the next few weeks.

**Comment by kongqueshi** [comment]
Thank you, I'm looking forward to this feature.

**Comment by kiwidan** [comment]
Hi @jamesdbloom, will this new concept support different defaults for different routes?

e.g:
- `/api/v1/driver-licence` always defaults to `api.driver-licence-check.com`, and
- `/api/v1/credit-check` always defaults to `api.credit-check.com`.

We've recently found MockServer and it's working really well for us, thanks! This would save us from needing to run individual MockServer instances for each API.

**Comment by chris0385** [comment]
I'm also interested in such feature. Maybe some generic numeric priority could be added, the expectations being then sorted by (<priority>, <time the expectation was added>).

But a default expectation would be good enough to cover my use-case too.

**Comment by jamesdbloom** [comment]
I could certainly add support for this, perhaps as suggested using a prior for expectations.  However currently as expectations are applied in order if you want a default expectation just create an expectation very relaxed request matcher and add that first, this means when other expectations don't match that expectation added first will be matched.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/9G3Hkdu3/31-default-expectation-or-expectation-priority

**Comment by jamesdbloom** [comment]
I have now added support for expectation priority which can be used to change the matching order or expectations.  Now matching priority is considered first before the creation order. This means a default expectation can be created at any time by creating a new higher priority expectation that is guaranteed to be matched first (if its priority is higher then all other expectations)
