### ISSUE TITLE
random outcome when making more than one request served by javascript template engine

### ISSUE THREAD

**Issue by yutu3** [jamesdbloom/mockserver#683]
The previous issue was months ago and did not get update so I am opening a separate one for follow up. Thanks for the help!

Please use expectations1.json to create expectations.
Then run "node test01.js" multiple times, and comment/uncomment the simultaneous calls.
getCall1(id),
getCall2(id),
getCall3(id)

Notice that you will see following result:

call1 get stuck sometime if running call2 and call3 together. All 3 calls sometime return wrong results.
It seems like call1 is stuck because the input of other calls are wrongly routed to call1 expectation instead. Inside call1 implementation, the code is designed to parse some input field (i.e. "expert" field values like _id:test12345). That failure caused call1 to be hanging, because wrong client request with *no parameter* was fed to this expectation code.
[test1.zip](https://github.com/jamesdbloom/mockserver/files/3784126/test1.zip)

link to previously opened issue:
https://github.com/jamesdbloom/mockserver/issues/649

**Comment by jamesdbloom** [comment]
This is a duplicate and that issue is now resolved.  I did a release of version `5.7.0` today with that fix, but I haven't updated the website yet to indicate that.  Please use that version to get the fix you need.
