### ISSUE TITLE
Install custom SSL certificate or PIN SSL certificate

### ISSUE THREAD

**Issue by sym-bolic-link** [jamesdbloom/mockserver#684]
I understand we have some parameters to specify keystores, but they don't seem to be producing the effects that I want. The effect I hope to accomplish is for mock-sever to present the same SSL certificate each time it is started, and for each request that it serves. The need for this arises from some clients doing "certificate pinning".

This means I can either install my own SSL certificate, or somehow ask Mock Server to reuse a previously generated certificate. I believed the latter option is easier, but it seems as though no matter what I do, Mock Server presents a new certificate for each request. I have tried the following options in the properties file:
1)
`mockserver.javaKeyStoreFilePath="C:\\Users\\lwong\\Documents\\Programs\\mockserver\\KeyStore.jks"
mockserver.javaKeyStorePassword=changeit
mockserver.javaKeyStoreType=jks
mockserver.deleteGeneratedKeyStoreOnExit=false
mockserver.sslCertificateDomainName=localhost
mockserver.sslSubjectAlternativeNameDomains=www.example.com,www.another.com,www.pik.com
mockserver.sslSubjectAlternativeNameIps=127.0.0.1`
2)
`mockserver.javaKeyStoreFilePath="C:\Users\lwong\Documents\Programs\mockserver\KeyStore.jks"
mockserver.javaKeyStorePassword=changeit
mockserver.javaKeyStoreType=jks
mockserver.deleteGeneratedKeyStoreOnExit=false
mockserver.sslCertificateDomainName=localhost
mockserver.sslSubjectAlternativeNameDomains=www.example.com,www.another.com,www.pik.com
mockserver.sslSubjectAlternativeNameIps=127.0.0.1`
3)
`mockserver.javaKeyStoreFilePath="C:/Users/lwong/Documents/Programs/mockserver/KeyStore.jks"
mockserver.javaKeyStorePassword=changeit
mockserver.javaKeyStoreType=jks
mockserver.deleteGeneratedKeyStoreOnExit=false
mockserver.sslCertificateDomainName=localhost
mockserver.sslSubjectAlternativeNameDomains=www.example.com,www.another.com,www.pik.com
mockserver.sslSubjectAlternativeNameIps=127.0.0.1`

With and without a pre-generated keystore (using java keytool) in the directory. Without pre-generated keystore, no keystore file is generated by Mock Server on startup nor after the first HTTPs request to it; with a pre-generated keystore, Mock Server doesn't seem to be adding any certificates to it. 

The mock server was started with the command: java -jar .\mockserver-netty-5.6.1-jar-with-dependencies.jar -serverPort 1080 -Dmockserver.propertyFile=mockserver.properties

Would you be able to help? Either provide instructions on how to get mock-server to present a self-signed certificate or have it use the same certificate across restarts and requests?

Thanks!

**Comment by jamesdbloom** [comment]
I have now added a configuration property `mockserver.preventCertificateDynamicUpdate`  this can be set by either:
- the properties files, 
- a java system property
   ```bash
   -Dmockserver.preventCertificateDynamicUpdate=false
   ```
   or, 
- using the Java method 
   ```java
   ConfigurationProperties.preventCertificateDynamicUpdate(boolean preventCertificateDynamicUpdate)
   ```
**Note:** the certificate will now be created once the first time it is needed (i.e. the first TLS socket connection) at this point the Subject Alternative Names will be fixed, so if you need specific names in the certificate to support server validation / authentication then please make sure you specify them using the `mockserver.sslSubjectAlternativeNameDomains` property.

I also notice a small bug (which I fixed) that was recreating the certificate even when the subject alternative names were not changing.

This will be available in the next release which won't be for a few weeks as I just already made a release today.  In the meantime, you can use the SNAPSHOT version as documented
