### ISSUE TITLE
not working example from http://www.mock-server.com

### ISSUE THREAD

**Issue by senegal8green** [jamesdbloom/mockserver#689]
Hi James, i could not reproduce example for the rule about regex in request body (http://www.mock-server.com/mock_server/creating_expectations.html#button_match_request_by_regex_body)

But structure like this works ok:

```javascript
{
  "httpRequest" : {
    "path": "/some/path",
    "body" : {
    	"type": "REGEX",
    	"regex": "\\d{5}"
    }
  },
  "httpResponse" : {
    "body" : "some_response_body"
  }
}
```

Thanks man!

**Comment by jamesdbloom** [comment]
This is now fixed and deployed to the website.  You will need to do a hard refresh to update your browser cache to see the new version.

**Comment by senegal8green** [comment]
James, your version is not working for me again. (It behaviours now like there is no any expected body at all). Regex for body again works only with schema like
`"body" : {
    	"type": "REGEX",
    	"regex": "starts_with_.*"
}`
No 'body' key into body but 'regex' instead.
