### ISSUE TITLE
Allow tests to specify relaxed or strict header matching.

### ISSUE THREAD

**Issue by DominicCliftonNEKTAN** [jamesdbloom/mockserver#75]
The presence of duplicate headers or missing headers can cause problems with interactions to remote systems.

Currently if a header is received by mock server that was not specified it is ignored instead of causing a verification/interaction failure.

It would be nice to say:
* Header X with value = (pattern) is required and must occur n times.
* Header Y with value = (pattern) is optional and can occur n times.
* No other headers are allowed.

Similar to how one might setup spock interaction expectations.

It may also be worth considering the order of headers. 

I'll quote from the HTTP spec:

"The order in which header fields with differing field names are received is not significant. However, it is "good practice" to send general-header fields first, followed by request-header or response- header fields, and ending with the entity-header fields.

Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded."

http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by jamesdbloom** [comment]
This is a good idea but it will be covered in #180, please add any additional comments to that ticket
