### ISSUE TITLE
Port ruby client and node client to use new verification approach

### ISSUE THREAD

**Issue by jamesbloomnektan** [jamesdbloom/mockserver#84]

**Comment by dbyron0** [comment]
Is there some branch where this ruby work is happening?

**Comment by jamesdbloom** [comment]
No all work is done in the master branch but it fully covered by extensive tests.

James D Bloom
http://blog.jamesdbloom.com/ <http://blog.jamesdbloom.com/>

**Comment by vk2sky** [comment]
Hi James, several mockserver-client-ruby unit tests are failing under Ruby 2.2.2.

One failure that comes up several times involves comparing JS object literals with JSON, e.g. in the spec "MockServer::Model::DSL / generates times correctly", the return value from first call to "to_camelised_hash" is being compared to the fixture "times.once.json":

{
    "times": {
        "remainingTimes": 1,
        "unlimited": false
    }
}

If the above is valid JSON, I would expect the *false* to have quotes around it.

(I'm brand new to this project, so I'm not game to suggest specific code changes yet :-)

Cheers,
Richard

**Comment by jamesbloomnektan** [comment]
Hmm I'm currently focusing on improving the web site, once I've finished I look into this when I update the ruby client.

**Comment by richardPFisk** [comment]
I experienced the same issue vk2sky did. The ```!``` operator was being applied to the custom Boolean class on line 105 of ```abstract_client``` which made is_exact false regardless of whether ```times.unlimited``` was true or false.

**Comment by jamesdbloom** [comment]
Closing as covered by #181 and #182
