### ISSUE TITLE
Allow users to specify that an HttpHeader in an expectation is strict or otherwise.

### ISSUE THREAD

**Issue by DominicCliftonNEKTAN** [jamesdbloom/mockserver#88]
Currently the HttpHeader uses a regular expression pattern.

this simple use case caused confusion due to the expectation containing the * character.

```
new Header("accept", "application/json, text/plain, */*")
```

When the requests were verified it was not clear why the headers didn't match since the contents of the actual and expected in the intellij comparison dialog were identical.

**Comment by jamesdbloom** [comment]
This is a good idea but it will be covered in #180, please add any additional comments to that ticket
