### ISSUE TITLE
Inclusion of logback.xml in mockserver-netty

### ISSUE THREAD

**Issue by brcolow** [jamesdbloom/mockserver#89]
Hello,

After doing some research I have come to the conclusion that it is standard practice for libraries to exclude their logback.xml's from .jar's that go in Maven Central (or any repo for that matter). Because mockserver-netty has logback.xml in the .jar, I get the following warnings:

16:28:19,353 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:28:19,353 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/C:/Code/cryptodash/core/target/classes/logback.xml]
16:28:19,353 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/brcolow/.m2/repository/org/mock-server/mockserver-netty/3.9.1/mockserver-netty-3.9.1.jar!/logback.xml]
16:28:19,447 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set

This wouldn't be so bad but logback has this thing where after a WARNing has occured, no matter what local settings one has, all further logging gets output to the console (as you can see from the one INFO log statement I included after the WARNs).

I am requesting that you exclude logback.xml from the final JAR for mockserver-netty.

(Just want to say as an aside that I really love working with this library so far, it is amazing).

Thanks very much.

**Comment by flozano** [comment]
:+1: for this, I just experienced some weirdness because of the logback.xml in the classpath

**Comment by 2082** [comment]
I will fix (and release) this early in the next week or so once I'm back after Christmas holidays.

Cheers,

James

**Comment by flozano** [comment]
thanks!

**Comment by jamesdbloom** [comment]
Sorry for the delay but I've been trying to work on this. The main remaining issue is that the jar-with-dependencies used in a number of other tools that use MockServer requires the logback jars and xml file.

I just need to resolve this then I can remove both the jars and the xml file so that only slf4j will be present and any underlying logging framework can be plugged in.

**Comment by jamesdbloom** [comment]
This fix is in version 3.9.2 which I am releasing right now, but it'll take about 2 hours to appear on maven central.
