### ISSUE TITLE
Multipart and regex

### ISSUE THREAD

**Issue by danidemi** [jamesdbloom/mockserver#93]
Hi.

I'm getting this exception following an assertion.

	java.lang.AssertionError: Request not found exactly once, expected:<{
	  "method" : "POST",
	  "body" : {
	    "type" : "REGEX",
	    "value" : "XMLSIP"
	  }
	}> but was:<{
	  "method" : "POST",
	  "path" : "/",
	  "body" : "--_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6\r\nContent-Disposition: form-data; name=\"VERSIONE\"\r\n\r\nversione\r\n--_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6\r\nContent-Disposition: form-data; name=\"LOGINNAME \"\r\n\r\nlogin\r\n--_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6\r\nContent-Disposition: form-data; name=\"PASSWORD \"\r\n\r\npassword\r\n--_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6\r\nContent-Disposition: form-data; name=\"XMLSIP\"\r\n\r\n<xml>\r\n--_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6\r\nContent-Disposition: form-data; name=\"ID1\"; filename=\"filename\"\r\nContent-Type: application/octet-stream\r\n\r\n\r\n--_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6--\r\n",
	  "headers" : [ {
	    "name" : "Content-Type",
	    "values" : [ "multipart/form-data; boundary=_Ts2FnAsKewlbhGOMZZ0hpCevvSIMOfq4Wf6" ]
	  }, {
	    "name" : "Host",
	    "values" : [ "localhost:53588" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.3.6 (java 1.5)" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "590" ]
	  } ]
	}>

What it's strange is that I specified this assertion on the body...

	  "body" : {
	    "type" : "REGEX",
	    "value" : "XMLSIP"
	  }

...and if you check the body the XMLSIP string is actually there. So, if I'm getting the whole thing properly, it should not raise that exception, shouldn't it ?

**Comment by danidemi** [comment]
Ok, so I don't get the meaning of the regex() method...

Here another example... here I would like to assert that the body matches the regex `.+`. Now... obviously the body should match it because `.+` matches all.

java.lang.AssertionError: Request not found exactly once, expected:<{
  "method" : "POST",
  "body" : {
    "type" : "REGEX",
    "value" : ".+"
  }
}> but was:<{
  "method" : "POST",
  "path" : "/",
  "body" : "--ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3\r\nContent-Disposition: form-data; name=\"VERSIONE\"\r\n\r\nversione\r\n--ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3\r\nContent-Disposition: form-data; name=\"LOGINNAME \"\r\n\r\nlogin\r\n--ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3\r\nContent-Disposition: form-data; name=\"PASSWORD \"\r\n\r\npassword\r\n--ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3\r\nContent-Disposition: form-data; name=\"XMLSIP\"\r\n\r\n<xml>\r\n--ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3\r\nContent-Disposition: form-data; name=\"ID1\"; filename=\"filename\"\r\nContent-Type: application/octet-stream\r\n\r\n\r\n--ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3--\r\n",
  "headers" : [ {
    "name" : "Content-Type",
    "values" : [ "multipart/form-data; boundary=ipL-ZAWLTXJsVcr0mD7neREQXV5KxOCfedJjpBy3" ]
  }, {
    "name" : "Host",
    "values" : [ "localhost:46440" ]
  }, {
    "name" : "User-Agent",
    "values" : [ "Apache-HttpClient/4.3.6 (java 1.5)" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "614" ]
  } ]
}

**Comment by danidemi** [comment]
Ok, I got it. The reg ex should match the whole body. 

Here is how I fixed it...

		mockServerClient.verify(
				request().withMethod("POST").withBody(regex("[\\n.\\w\\W]*VERSIONE[\\n.\\w\\W]*versione[\\n.\\w\\W]*")),
				VerificationTimes.exactly(1)
		);

**Comment by radarsh** [comment]
Or you can use multiline regexes that consider newlines as whitespaces by employing the `(?ms)` flag at the beginning of your regex.
