### ISSUE TITLE
request setPath doesn't support regex, although it's stated in javadoc 

### ISSUE THREAD

**Issue by jcetkov** [jamesdbloom/mockserver#98]
mockServer.when(HttpRequest.request().withPath("/*_something")).respond(HttpResponse.response().withStatusCode(200));

returns 200 @ /something, but 404 on /anything_something.

not sure if this method is used to evaluate, but if it is, there is no Matcher anywhere

//org.mockserver.model.HttpRequest @ line 90
    public boolean matches(String method, String path) {
        return this.method.equals(method) && this.path.equals(path);
    }

using
      <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>3.9.1</version>
            <scope>test</scope>
        </dependency>

**Comment by belun** [comment]
this does not seem like valid regex to me:    /*_something
i am bad at regex, however i do not see that pattern working
how about    /.*_?something      , meaning : starting with /, then any number or none (*) of any chars (.), then char "_" existing once or not existing, followed by something

right now      /*_something    means :    any number or none of "/" followed by "_something"

**Comment by jcetkov** [comment]
sorry, my bad, I was recently working with regular expressions of a different syntax. You are right, it is working correctly.
